

import React, { PropTypes } from 'react';
import Helmet from 'react-helmet';
import _ from 'lodash';
//
import * as Basic from '../../components/basic';
import * as Advanced from '../../components/advanced';
import DecisionButtons from './DecisionButtons';

/**
 * Default component for render task detail.
 * Detail is compound from basic fields (name of task, name of applicant ...) and
 * dynamic compoentns. Dynamic components are generated by task definition.
 */
class DynamicTaskDetail extends Basic.AbstractContent {

  constructor(props) {
    super(props);
    this.state = {showLoading: props.showLoading, readOnly: true};
  }

  getContentKey() {
    return 'content.task.instance';
  }

  _toFormDataValues(formDatas) {
    const result = {};
    for (const formData of formDatas) {
      result[formData.id] = formData.value;
    }
    return result;
  }

  _toFormData(formDataValues, formDatas) {
    const result = _.merge({}, formDataValues);
    for (const formData of formDatas) {
      if (!formData.writable && !formData.required) {
        delete result[formData.id];
      }
    }
    return result;
  }

  _validateAndCompleteTask(decision) {
    if (!this.refs.form.isFormValid()) {
      return;
    }
    if (!this.refs.formData.isFormValid()) {
      return;
    }
    this.setState({
      showLoading: true
    });
    if (decision.showWarning) {
      this.refs.confirm.show(this.i18n(decision.warningMessage ? decision.warningMessage : 'completeTaskConfirmDetail'), this.i18n('completeTaskConfirmTitle'))
      .then(() => {
        this._completeTask(decision);
      }, () => {
        // Rejected
        this.setState({
          showLoading: false
        });
      });
    } else {
      this._completeTask(decision);
    }
  }

  _completeTask(decision) {
    const formDataValues = this.refs.formData.getData();
    const task = this.refs.form.getData();
    const formData = {'decision': decision.id, 'formData': this._toFormData(formDataValues, task.formData)};
    const { taskManager, uiKey } = this.props;
    this.context.store.dispatch(taskManager.completeTask(task, formData, `${uiKey}`, this._afterComplete.bind(this)));
  }

  _afterComplete(task, error) {
    if (error) {
      this.setState({
        showLoading: false
      });
      this.refs.form.processEnded();
      this.addError(error);
      return;
    }
    this.addMessage({ message: this.i18n('successComplete', { name: task.name }) });
    this.context.router.goBack();
  }

  _getFormDataComponents(task) {
    if (!task) {
      return null;
    }
    const formDatas = task.formData;
    const formDataComponents = [];
    for (const formData of formDatas) {
      switch (formData.type) {
        case 'textField': {
          formDataComponents.push(
            <Basic.TextField
              key={formData.id}
              ref={formData.id}
              readOnly={!formData.writable}
              required={formData.required}
              tooltip={this.i18n(formData.tooltip ? formData.tooltip : `formData.${formData.id}.tooltip`)}
              placeholder={this.i18n(formData.placeholder ? formData.placeholder : `formData.${formData.id}.placeholder`)}
              label={this.i18n(formData.name ? formData.name : `formData.${formData.id}.name`)}/>
          );
          break;
        }
        case 'date':
        case 'localDate': {
          formDataComponents.push(
            <Basic.DateTimePicker
              key={formData.id}
              ref={formData.id}
              mode="date"
              readOnly={!formData.writable}
              required={formData.required}
              tooltip={this.i18n(formData.tooltip ? formData.tooltip : `formData.${formData.id}.tooltip`)}
              placeholder={this.i18n(formData.placeholder ? formData.placeholder : `formData.${formData.id}.placeholder`)}
              label={this.i18n(formData.name ? formData.name : `formData.${formData.id}.name`)}/>
          );
          break;
        }
        case 'checkbox': {
          formDataComponents.push(
            <Basic.Checkbox
              key={formData.id}
              ref={formData.id}
              readOnly={!formData.writable}
              required={formData.required}
              tooltip={this.i18n(formData.tooltip ? formData.tooltip : `formData.${formData.id}.tooltip`)}
              placeholder={this.i18n(formData.placeholder ? formData.placeholder : `formData.${formData.id}.placeholder`)}
              label={this.i18n(formData.name ? formData.name : `formData.${formData.id}.name`)}/>
          );
          break;
        }
        case 'textArea': {
          formDataComponents.push(
            <Basic.TextArea
              key={formData.id}
              ref={formData.id}
              readOnly={!formData.writable}
              required={formData.required}
              tooltip={this.i18n(formData.tooltip ? formData.tooltip : `formData.${formData.id}.tooltip`)}
              placeholder={this.i18n(formData.placeholder ? formData.placeholder : `formData.${formData.id}.placeholder`)}
              label={this.i18n(formData.name ? formData.name : `formData.${formData.id}.name`)}/>
          );
          break;
        }
        default: {
          formDataComponents.push(
            <Basic.TextField
              key={formData.id}
              ref={formData.id}
              readOnly={!formData.writable}
              required={formData.required}
              tooltip={this.i18n(formData.tooltip ? formData.tooltip : `formData.${formData.id}.tooltip`)}
              placeholder={this.i18n(formData.placeholder ? formData.placeholder : `formData.${formData.id}.placeholder`)}
              label={this.i18n(formData.name ? formData.name : `formData.${formData.id}.name`)}/>
          );
        }
      }
    }
    return formDataComponents;
  }

  render() {
    const {task, taskManager} = this.props;
    const { showLoading} = this.state;
    const showLoadingInternal = task ? showLoading : true;
    const formDataValues = this._toFormDataValues(task.formData);
    return (
      <div>
        <Helmet title={this.i18n('title')} />
        <Basic.Confirm ref="confirm"/>
        <Basic.PageHeader>{task.taskName}
          <small> {this.i18n('header')}</small>
        </Basic.PageHeader>
        <Basic.Panel showLoading = {showLoadingInternal}>
          <Basic.PanelHeader text={<span>{taskManager.getNiceLabel(task)} <small>this.i18n('taskDetail')</small></span>} className="hidden">
          </Basic.PanelHeader>
          <Basic.AbstractForm className="panel-body" ref="form" data={task}>
            <Basic.TextField ref="taskDescription" readOnly label={this.i18n('description')}/>
            <Basic.LabelWrapper rendered={task.applicant} readOnly ref="applicant" label={this.i18n('applicant')}>
              <Advanced.IdentityInfo username={task.applicant} showLoading={!task} className="no-margin" style={{ width: '50%' }}/>
            </Basic.LabelWrapper>
            <Basic.DateTimePicker ref="taskCreated" readOnly label={this.i18n('createdDate')}/>
          </Basic.AbstractForm>
          <Basic.AbstractForm ref="formData" data={formDataValues} className="panel-body">
            {this._getFormDataComponents(task)}
          </Basic.AbstractForm>
          <Basic.PanelFooter>
            <DecisionButtons task={task} onClick={this._validateAndCompleteTask.bind(this)}/>
          </Basic.PanelFooter>
        </Basic.Panel>
      </div>
    );
  }
}

DynamicTaskDetail.propTypes = {
  task: PropTypes.object,
  readOnly: PropTypes.bool,
  taskManager: PropTypes.object.isRequired
};

DynamicTaskDetail.defaultProps = {
  task: null,
  readOnly: false
};

export default DynamicTaskDetail;
