/**
 * Config action types
 *
 * @author Radek Tomiška
 */
export default {
  // action constants
  Actions: {
    SELECT_NAVIGATION_ITEMS: 'SELECT_NAVIGATION_ITEMS',
    SELECT_NAVIGATION_ITEM: 'SELECT_NAVIGATION_ITEM',
    I18N_INIT: 'I18N_INIT',
    I18N_READY: 'I18N_READY',
    APP_INIT: 'APP_INIT',
    APP_READY: 'APP_READY',
    APP_UNAVAILABLE: 'APP_UNAVAILABLE',
    NAVIGATION_INIT: 'NAVIGATION_INIT',
    NAVIGATION_READY: 'NAVIGATION_READY',
    MODULES_INIT: 'MODULES_INIT',
    MODULES_READY: 'MODULES_READY',
    CONFIGURATION_INIT: 'CONFIGURATION_INIT',
    CONFIGURATION_RECEIVED: 'CONFIGURATION_RECEIVED',
    CONFIGURATION_READY: 'CONFIGURATION_READY',
    COLLAPSE_NAVIGATION: 'COLLAPSE_NAVIGATION'
  },
  // redux properties
  Properties: {
    PROPERITES: 'properties',
    NAVIGATION: 'navigation'
  }
};
