--
-- CzechIdM 9.0 Flyway script 
-- BCV solutions s.r.o.
--
-- This is initial SQL script for SQL Server

CREATE TABLE vs_account (
	id binary(16) NOT NULL,
	created datetime2(6) NOT NULL,
	creator NVARCHAR(255) NOT NULL,
	creator_id binary(16),
	modified datetime2(6),
	modifier NVARCHAR(255),
	modifier_id binary(16),
	original_creator NVARCHAR(255),
	original_creator_id binary(16),
	original_modifier NVARCHAR(255),
	original_modifier_id binary(16),
	realm_id binary(16),
	transaction_id binary(16),
	connector_key NVARCHAR(255) NOT NULL,
	enable bit NOT NULL,
	system_id binary(255) NOT NULL,
	uid NVARCHAR(255) NOT NULL,
	CONSTRAINT vs_account_pkey PRIMARY KEY (id)
);
CREATE INDEX idx_vs_account_system ON vs_account (system_id);
CREATE INDEX idx_vs_account_uid ON vs_account (uid);
CREATE UNIQUE INDEX ux_vs_account_uid ON vs_account (uid,system_id,connector_key);


CREATE TABLE vs_account_form_value (
	id binary(16) NOT NULL,
	created datetime2(6) NOT NULL,
	creator NVARCHAR(255) NOT NULL,
	creator_id binary(16),
	modified datetime2(6),
	modifier NVARCHAR(255),
	modifier_id binary(16),
	original_creator NVARCHAR(255),
	original_creator_id binary(16),
	original_modifier NVARCHAR(255),
	original_modifier_id binary(16),
	realm_id binary(16),
	transaction_id binary(16),
	boolean_value bit,
	byte_value varbinary(255),
	confidential bit NOT NULL,
	date_value datetime2(6),
	double_value numeric(38,4),
	long_value numeric(19,0),
	persistent_type NVARCHAR(45) NOT NULL,
	seq smallint,
	short_text_value NVARCHAR(2000),
	string_value nvarchar(MAX),
	uuid_value binary(16),
	attribute_id binary(16) NOT NULL,
	owner_id binary(16) NOT NULL,
	CONSTRAINT vs_account_form_value_pkey PRIMARY KEY (id),
	CONSTRAINT vs_account_form_value_seq_check CHECK ((seq <= 99999))
);
CREATE INDEX idx_vs_account_form_a ON vs_account_form_value (owner_id);
CREATE INDEX idx_vs_account_form_a_def ON vs_account_form_value (attribute_id);
CREATE INDEX idx_vs_account_form_uuid ON vs_account_form_value (uuid_value);


CREATE TABLE vs_request (
	id binary(16) NOT NULL,
	created datetime2(6) NOT NULL,
	creator NVARCHAR(255) NOT NULL,
	creator_id binary(16),
	modified datetime2(6),
	modifier NVARCHAR(255),
	modifier_id binary(16),
	original_creator NVARCHAR(255),
	original_creator_id binary(16),
	original_modifier NVARCHAR(255),
	original_modifier_id binary(16),
	realm_id binary(16),
	transaction_id binary(16),
	connector_conf image,
	connector_key NVARCHAR(255) NOT NULL,
	connector_object image,
	duplicate_to_request_id binary(255),
	execute_immediately bit NOT NULL,
	operation_type NVARCHAR(255) NOT NULL,
	reason NVARCHAR(255),
	state NVARCHAR(255) NOT NULL,
	uid NVARCHAR(255) NOT NULL,
	previous_request_id binary(16),
	system_id binary(16) NOT NULL,
	CONSTRAINT vs_request_pkey PRIMARY KEY (id)
);
CREATE INDEX idx_vs_request_system ON vs_request (system_id);
CREATE INDEX idx_vs_request_uid ON vs_request (uid);


CREATE TABLE vs_system_implementer (
	id binary(16) NOT NULL,
	created datetime2(6) NOT NULL,
	creator NVARCHAR(255) NOT NULL,
	creator_id binary(16),
	modified datetime2(6),
	modifier NVARCHAR(255),
	modifier_id binary(16),
	original_creator NVARCHAR(255),
	original_creator_id binary(16),
	original_modifier NVARCHAR(255),
	original_modifier_id binary(16),
	realm_id binary(16),
	transaction_id binary(16),
	identity_id binary(16),
	role_id binary(16),
	system_id binary(16) NOT NULL,
	CONSTRAINT vs_system_implementer_pkey PRIMARY KEY (id)
);
CREATE INDEX idx_vs_sys_imple_identity ON vs_system_implementer (identity_id);
CREATE INDEX idx_vs_sys_imple_role ON vs_system_implementer (role_id);
CREATE INDEX idx_vs_sys_imple_system ON vs_system_implementer (system_id);


-- AUDIT TABLES

CREATE TABLE vs_account_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	revtype smallint,
	created datetime2(6),
	created_m bit,
	creator NVARCHAR(255),
	creator_m bit,
	creator_id binary(16),
	creator_id_m bit,
	modifier NVARCHAR(255),
	modifier_m bit,
	modifier_id binary(16),
	modifier_id_m bit,
	original_creator NVARCHAR(255),
	original_creator_m bit,
	original_creator_id binary(16),
	original_creator_id_m bit,
	original_modifier NVARCHAR(255),
	original_modifier_m bit,
	original_modifier_id binary(16),
	original_modifier_id_m bit,
	realm_id binary(16),
	realm_id_m bit,
	transaction_id binary(16),
	transaction_id_m bit,
	connector_key NVARCHAR(255),
	connector_key_m bit,
	enable bit,
	enable_m bit,
	system_id binary(255),
	system_id_m bit,
	uid NVARCHAR(255),
	uid_m bit,
	CONSTRAINT vs_account_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_vs_acc_a_idm_audit FOREIGN KEY (rev) REFERENCES idm_audit(id)
);



CREATE TABLE vs_account_form_value_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	revtype smallint,
	created datetime2(6),
	created_m bit,
	creator NVARCHAR(255),
	creator_m bit,
	creator_id binary(16),
	creator_id_m bit,
	modifier NVARCHAR(255),
	modifier_m bit,
	modifier_id binary(16),
	modifier_id_m bit,
	original_creator NVARCHAR(255),
	original_creator_m bit,
	original_creator_id binary(16),
	original_creator_id_m bit,
	original_modifier NVARCHAR(255),
	original_modifier_m bit,
	original_modifier_id binary(16),
	original_modifier_id_m bit,
	realm_id binary(16),
	realm_id_m bit,
	transaction_id binary(16),
	transaction_id_m bit,
	boolean_value bit,
	boolean_value_m bit,
	byte_value varbinary(255),
	byte_value_m bit,
	confidential bit,
	confidential_m bit,
	date_value datetime2(6),
	date_value_m bit,
	double_value numeric(38,4),
	double_value_m bit,
	long_value numeric(19,0),
	long_value_m bit,
	persistent_type NVARCHAR(45),
	persistent_type_m bit,
	seq smallint,
	seq_m bit,
	short_text_value NVARCHAR(2000),
	short_text_value_m bit,
	string_value nvarchar(MAX),
	string_value_m bit,
	uuid_value binary(16),
	uuid_value_m bit,
	attribute_id binary(16),
	form_attribute_m bit,
	owner_id binary(16),
	owner_m bit,
	CONSTRAINT vs_account_form_value_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_vs_acc_fvalue_a_audit FOREIGN KEY (rev) REFERENCES idm_audit(id)
);


CREATE TABLE vs_request_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	revtype smallint,
	created datetime2(6),
	created_m bit,
	creator NVARCHAR(255),
	creator_m bit,
	creator_id binary(16),
	creator_id_m bit,
	modifier NVARCHAR(255),
	modifier_m bit,
	modifier_id binary(16),
	modifier_id_m bit,
	original_creator NVARCHAR(255),
	original_creator_m bit,
	original_creator_id binary(16),
	original_creator_id_m bit,
	original_modifier NVARCHAR(255),
	original_modifier_m bit,
	original_modifier_id binary(16),
	original_modifier_id_m bit,
	realm_id binary(16),
	realm_id_m bit,
	transaction_id binary(16),
	transaction_id_m bit,
	connector_conf image,
	configuration_m bit,
	connector_key NVARCHAR(255),
	connector_key_m bit,
	connector_object image,
	connector_object_m bit,
	duplicate_to_request_id binary(255),
	duplicate_to_request_m bit,
	execute_immediately bit,
	execute_immediately_m bit,
	operation_type NVARCHAR(255),
	operation_type_m bit,
	reason NVARCHAR(255),
	reason_m bit,
	state NVARCHAR(255),
	state_m bit,
	uid NVARCHAR(255),
	uid_m bit,
	previous_request_id binary(16),
	previous_request_m bit,
	system_id binary(16),
	system_m bit,
	CONSTRAINT vs_request_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_request_a_idm_audit FOREIGN KEY (rev) REFERENCES idm_audit(id)
);


CREATE TABLE vs_system_implementer_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	revtype smallint,
	created datetime2(6),
	created_m bit,
	creator NVARCHAR(255),
	creator_m bit,
	creator_id binary(16),
	creator_id_m bit,
	modifier NVARCHAR(255),
	modifier_m bit,
	modifier_id binary(16),
	modifier_id_m bit,
	original_creator NVARCHAR(255),
	original_creator_m bit,
	original_creator_id binary(16),
	original_creator_id_m bit,
	original_modifier NVARCHAR(255),
	original_modifier_m bit,
	original_modifier_id binary(16),
	original_modifier_id_m bit,
	realm_id binary(16),
	realm_id_m bit,
	transaction_id binary(16),
	transaction_id_m bit,
	identity_id binary(16),
	identity_m bit,
	role_id binary(16),
	role_m bit,
	system_id binary(16),
	system_m bit,
	CONSTRAINT vs_system_implementer_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_ar40qritwofj5acof4vk9l6bq FOREIGN KEY (rev) REFERENCES idm_audit(id)
);
