--
-- CzechIdM 10 Flyway script 
-- BCV solutions s.r.o.
--
-- Long running task audit

CREATE TABLE idm_long_running_task_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	revtype smallint NULL,
	created datetime2(6) NULL,
	created_m bit NULL,
	creator nvarchar(255) NULL,
	creator_m bit NULL,
	creator_id binary(16) NULL,
	creator_id_m bit NULL,
	modifier nvarchar(255) NULL,
	modifier_m bit NULL,
	modifier_id binary(16) NULL,
	modifier_id_m bit NULL,
	original_creator nvarchar(255) NULL,
	original_creator_m bit NULL,
	original_creator_id binary(16) NULL,
	original_creator_id_m bit NULL,
	original_modifier nvarchar(255) NULL,
	original_modifier_m bit NULL,
	original_modifier_id binary(16) NULL,
	original_modifier_id_m bit NULL,
	realm_id binary(16) NULL,
	realm_id_m bit NULL,
	dry_run bit NULL,
	dry_run_m bit NULL,
	instance_id nvarchar(255) NULL,
	instance_id_m bit NULL,
	recoverable bit NULL,
	recoverable_m bit NULL,
	result_cause nvarchar(MAX) NULL,
	result_code nvarchar(255) NULL,
	result_model binary(16) NULL,
	result_state nvarchar(45) NULL,
	result_m bit NULL,
	running bit NULL,
	running_m bit NULL,
	stateful bit NULL,
	stateful_m bit NULL,
	task_description varchar(2000) NULL,
	task_description_m bit NULL,
	task_properties image NULL,
	task_properties_m bit NULL,
	task_started datetime2(6) NULL,
	task_started_m bit NULL,
	task_type nvarchar(255) NULL,
	task_type_m bit NULL,
	thread_id numeric(19,0) NULL,
	thread_id_m bit NULL,
	thread_name nvarchar(255) NULL,
	thread_name_m bit NULL,
	scheduled_task_id binary(16) NULL,
	scheduled_task_m bit NULL,
	CONSTRAINT idm_long_running_task_a_pkey PRIMARY KEY (id, rev),
	CONSTRAINT fk6libuw83ga8itsldmrgmc7v0v FOREIGN KEY (rev) REFERENCES idm_audit(id)
);


