--
-- CzechIdM 9.0 Flyway script 
-- BCV solutions s.r.o.
--
-- This SQL script creates the required audit tables by CzechIdM (module core)

CREATE TABLE idm_audit (
	id numeric(19,0) NOT NULL IDENTITY(1,1),
	changed_attributes varchar(2000),
	entity_id binary(255),
	modification varchar(255),
	modifier varchar(255),
	modifier_id binary(255),
	original_modifier varchar(255),
	original_modifier_id binary(255),
	owner_code varchar(255),
	owner_id varchar(255),
	owner_type varchar(255),
	realm_id binary(255),
	sub_owner_code varchar(255),
	sub_owner_id varchar(255),
	sub_owner_type varchar(255),
	[timestamp] numeric(19,0) NOT NULL,
	[type] varchar(255),
	CONSTRAINT idm_audit_pkey PRIMARY KEY (id)
);
CREATE INDEX idx_idm_audit_changed_attributes ON idm_audit (changed_attributes);
CREATE INDEX idx_idm_audit_entity_id ON idm_audit (entity_id);
CREATE INDEX idx_idm_audit_modification ON idm_audit (modification);
CREATE INDEX idx_idm_audit_modifier ON idm_audit (modifier);
CREATE INDEX idx_idm_audit_original_modifier ON idm_audit (original_modifier);
CREATE INDEX idx_idm_audit_owner_code ON idm_audit (owner_code);
CREATE INDEX idx_idm_audit_owner_id ON idm_audit (owner_id);
CREATE INDEX idx_idm_audit_owner_type ON idm_audit (owner_type);
CREATE INDEX idx_idm_audit_sub_owner_code ON idm_audit (sub_owner_code);
CREATE INDEX idx_idm_audit_sub_owner_id ON idm_audit (sub_owner_id);
CREATE INDEX idx_idm_audit_sub_owner_type ON idm_audit (sub_owner_type);
CREATE INDEX idx_idm_audit_timestamp ON idm_audit ([timestamp]);


CREATE TABLE idm_authorization_policy_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	revtype smallint,
	created datetime,
	created_m bit,
	creator varchar(255),
	creator_m bit,
	creator_id binary(16),
	creator_id_m bit,
	modifier varchar(255),
	modifier_m bit,
	modifier_id binary(16),
	modifier_id_m bit,
	original_creator varchar(255),
	original_creator_m bit,
	original_creator_id binary(16),
	original_creator_id_m bit,
	original_modifier varchar(255),
	original_modifier_m bit,
	original_modifier_id binary(16),
	original_modifier_id_m bit,
	realm_id binary(16),
	realm_id_m bit,
	transaction_id binary(16),
	transaction_id_m bit,
	authorizable_type varchar(255),
	authorizable_type_m bit,
	base_permissions varchar(255),
	base_permissions_m bit,
	description varchar(2000),
	description_m bit,
	disabled bit,
	disabled_m bit,
	evaluator_properties image,
	evaluator_properties_m bit,
	evaluator_type varchar(255),
	evaluator_type_m bit,
	group_permission varchar(255),
	group_permission_m bit,
	seq smallint,
	seq_m bit,
	role_id binary(16),
	role_m bit,
	CONSTRAINT idm_authorization_policy_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_gobi05mdqmnq11h8n409tsqmm FOREIGN KEY (rev) REFERENCES idm_audit(id)
);


CREATE TABLE idm_auto_role_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	revtype smallint,
	created datetime,
	created_m bit,
	creator varchar(255),
	creator_m bit,
	creator_id binary(16),
	creator_id_m bit,
	modifier varchar(255),
	modifier_m bit,
	modifier_id binary(16),
	modifier_id_m bit,
	original_creator varchar(255),
	original_creator_m bit,
	original_creator_id binary(16),
	original_creator_id_m bit,
	original_modifier varchar(255),
	original_modifier_m bit,
	original_modifier_id binary(16),
	original_modifier_id_m bit,
	realm_id binary(16),
	realm_id_m bit,
	transaction_id binary(16),
	transaction_id_m bit,
	name varchar(255),
	name_m bit,
	role_id binary(16),
	role_m bit,
	CONSTRAINT idm_auto_role_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_a5dnmuabje245da81j1mtv1id FOREIGN KEY (rev) REFERENCES idm_audit(id)
);


CREATE TABLE idm_auto_role_att_rule_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	revtype smallint,
	created datetime,
	created_m bit,
	creator varchar(255),
	creator_m bit,
	creator_id binary(16),
	creator_id_m bit,
	modifier varchar(255),
	modifier_m bit,
	modifier_id binary(16),
	modifier_id_m bit,
	original_creator varchar(255),
	original_creator_m bit,
	original_creator_id binary(16),
	original_creator_id_m bit,
	original_modifier varchar(255),
	original_modifier_m bit,
	original_modifier_id binary(16),
	original_modifier_id_m bit,
	realm_id binary(16),
	realm_id_m bit,
	transaction_id binary(16),
	transaction_id_m bit,
	attribute_name varchar(255),
	attribute_name_m bit,
	comparison varchar(255),
	comparison_m bit,
	[type] varchar(255),
	type_m bit,
	value varchar(2000),
	value_m bit,
	auto_role_att_id binary(16),
	automatic_role_attribute_m bit,
	form_attribute_id binary(16),
	form_attribute_m bit,
	CONSTRAINT idm_auto_role_att_rule_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_4h00l1b06fwkwi26fed2xq8p4 FOREIGN KEY (rev) REFERENCES idm_audit(id)
);


CREATE TABLE idm_auto_role_att_rule_req_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	revtype smallint,
	created datetime,
	created_m bit,
	creator varchar(255),
	creator_m bit,
	creator_id binary(16),
	creator_id_m bit,
	modifier varchar(255),
	modifier_m bit,
	modifier_id binary(16),
	modifier_id_m bit,
	original_creator varchar(255),
	original_creator_m bit,
	original_creator_id binary(16),
	original_creator_id_m bit,
	original_modifier varchar(255),
	original_modifier_m bit,
	original_modifier_id binary(16),
	original_modifier_id_m bit,
	realm_id binary(16),
	realm_id_m bit,
	transaction_id binary(16),
	transaction_id_m bit,
	attribute_name varchar(255),
	attribute_name_m bit,
	comparison varchar(255),
	comparison_m bit,
	operation varchar(255),
	operation_m bit,
	[type] varchar(255),
	type_m bit,
	value varchar(2000),
	value_m bit,
	form_attribute_id binary(16),
	form_attribute_m bit,
	auto_role_att_id binary(16),
	request_m bit,
	rule_id binary(16),
	rule_m bit,
	CONSTRAINT idm_auto_role_att_rule_req_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_h5wcaotvqs4m7pf0siqfr27u4 FOREIGN KEY (rev) REFERENCES idm_audit(id)
);


CREATE TABLE idm_auto_role_attribute_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	concept bit,
	concept_m bit,
	CONSTRAINT idm_auto_role_attribute_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_otby9l02vverqso9ejrgeabj2 FOREIGN KEY (id,rev) REFERENCES idm_auto_role_a(id,rev)
);


CREATE TABLE idm_auto_role_request_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	revtype smallint,
	created datetime,
	created_m bit,
	creator varchar(255),
	creator_m bit,
	creator_id binary(16),
	creator_id_m bit,
	modifier varchar(255),
	modifier_m bit,
	modifier_id binary(16),
	modifier_id_m bit,
	original_creator varchar(255),
	original_creator_m bit,
	original_creator_id binary(16),
	original_creator_id_m bit,
	original_modifier varchar(255),
	original_modifier_m bit,
	original_modifier_id binary(16),
	original_modifier_id_m bit,
	realm_id binary(16),
	realm_id_m bit,
	transaction_id binary(16),
	transaction_id_m bit,
	description varchar(2000),
	description_m bit,
	execute_immediately bit,
	execute_immediately_m bit,
	name varchar(255),
	name_m bit,
	operation varchar(255),
	operation_m bit,
	recursion_type varchar(255),
	recursion_type_m bit,
	request_type varchar(255),
	request_type_m bit,
	state varchar(255),
	state_m bit,
	wf_process_id varchar(255),
	wf_process_id_m bit,
	auto_role_att_id binary(16),
	automatic_role_m bit,
	role_id binary(16),
	role_m bit,
	tree_node_id binary(16),
	tree_node_m bit,
	CONSTRAINT idm_auto_role_request_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_3c5uwgj4whal2entaae9xsros FOREIGN KEY (rev) REFERENCES idm_audit(id)
);


CREATE TABLE idm_con_slice_form_value_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	revtype smallint,
	created datetime,
	created_m bit,
	creator varchar(255),
	creator_m bit,
	creator_id binary(16),
	creator_id_m bit,
	modifier varchar(255),
	modifier_m bit,
	modifier_id binary(16),
	modifier_id_m bit,
	original_creator varchar(255),
	original_creator_m bit,
	original_creator_id binary(16),
	original_creator_id_m bit,
	original_modifier varchar(255),
	original_modifier_m bit,
	original_modifier_id binary(16),
	original_modifier_id_m bit,
	realm_id binary(16),
	realm_id_m bit,
	transaction_id binary(16),
	transaction_id_m bit,
	boolean_value bit,
	boolean_value_m bit,
	byte_value varbinary(255),
	byte_value_m bit,
	confidential bit,
	confidential_m bit,
	date_value datetime,
	date_value_m bit,
	double_value numeric(38,4),
	double_value_m bit,
	long_value numeric(19,0),
	long_value_m bit,
	persistent_type varchar(45),
	persistent_type_m bit,
	seq smallint,
	seq_m bit,
	short_text_value varchar(2000),
	short_text_value_m bit,
	string_value text,
	string_value_m bit,
	uuid_value binary(16),
	uuid_value_m bit,
	attribute_id binary(16),
	form_attribute_m bit,
	owner_id binary(16),
	owner_m bit,
	CONSTRAINT idm_con_slice_form_value_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_pq67ujqv1s2xmdkl80j36dvhp FOREIGN KEY (rev) REFERENCES idm_audit(id)
);


CREATE TABLE idm_concept_role_request_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	revtype smallint,
	created datetime,
	created_m bit,
	creator varchar(255),
	creator_m bit,
	creator_id binary(16),
	creator_id_m bit,
	modifier varchar(255),
	modifier_m bit,
	modifier_id binary(16),
	modifier_id_m bit,
	original_creator varchar(255),
	original_creator_m bit,
	original_creator_id binary(16),
	original_creator_id_m bit,
	original_modifier varchar(255),
	original_modifier_m bit,
	original_modifier_id binary(16),
	original_modifier_id_m bit,
	realm_id binary(16),
	realm_id_m bit,
	transaction_id binary(16),
	transaction_id_m bit,
	operation varchar(255),
	operation_m bit,
	state varchar(255),
	state_m bit,
	valid_from datetime,
	valid_from_m bit,
	valid_till datetime,
	valid_till_m bit,
	wf_process_id varchar(255),
	wf_process_id_m bit,
	automatic_role_id binary(16),
	automatic_role_m bit,
	identity_contract_id binary(16),
	identity_contract_m bit,
	identity_role_id binary(16),
	identity_role_m bit,
	role_id binary(16),
	role_m bit,
	request_role_id binary(16),
	role_request_m bit,
	CONSTRAINT idm_concept_role_request_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_s00svvhj93oge2mlgotun5nuv FOREIGN KEY (rev) REFERENCES idm_audit(id)
);


CREATE TABLE idm_confidential_storage_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	revtype smallint,
	created datetime,
	created_m bit,
	creator varchar(255),
	creator_m bit,
	creator_id binary(16),
	creator_id_m bit,
	modifier varchar(255),
	modifier_m bit,
	modifier_id binary(16),
	modifier_id_m bit,
	original_creator varchar(255),
	original_creator_m bit,
	original_creator_id binary(16),
	original_creator_id_m bit,
	original_modifier varchar(255),
	original_modifier_m bit,
	original_modifier_id binary(16),
	original_modifier_id_m bit,
	realm_id binary(16),
	realm_id_m bit,
	transaction_id binary(16),
	transaction_id_m bit,
	storage_key varchar(255),
	key_m bit,
	owner_id binary(16),
	owner_id_m bit,
	owner_type varchar(255),
	owner_type_m bit,
	CONSTRAINT idm_confidential_storage_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_agmqlakgyyjnhyx4up05iim52 FOREIGN KEY (rev) REFERENCES idm_audit(id)
);


CREATE TABLE idm_configuration_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	revtype smallint,
	created datetime,
	created_m bit,
	creator varchar(255),
	creator_m bit,
	creator_id binary(16),
	creator_id_m bit,
	modifier varchar(255),
	modifier_m bit,
	modifier_id binary(16),
	modifier_id_m bit,
	original_creator varchar(255),
	original_creator_m bit,
	original_creator_id binary(16),
	original_creator_id_m bit,
	original_modifier varchar(255),
	original_modifier_m bit,
	original_modifier_id binary(16),
	original_modifier_id_m bit,
	realm_id binary(16),
	realm_id_m bit,
	transaction_id binary(16),
	transaction_id_m bit,
	confidential bit,
	confidential_m bit,
	name varchar(255),
	name_m bit,
	secured bit,
	secured_m bit,
	value varchar(255),
	value_m bit,
	CONSTRAINT idm_configuration_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_i8it9y3yjy5196fbs7cpn7faq FOREIGN KEY (rev) REFERENCES idm_audit(id)
);


CREATE TABLE idm_contract_guarantee_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	revtype smallint,
	created datetime,
	created_m bit,
	creator varchar(255),
	creator_m bit,
	creator_id binary(16),
	creator_id_m bit,
	modifier varchar(255),
	modifier_m bit,
	modifier_id binary(16),
	modifier_id_m bit,
	original_creator varchar(255),
	original_creator_m bit,
	original_creator_id binary(16),
	original_creator_id_m bit,
	original_modifier varchar(255),
	original_modifier_m bit,
	original_modifier_id binary(16),
	original_modifier_id_m bit,
	realm_id binary(16),
	realm_id_m bit,
	transaction_id binary(16),
	transaction_id_m bit,
	external_id varchar(255),
	external_id_m bit,
	guarantee_id binary(16),
	guarantee_m bit,
	identity_contract_id binary(16),
	identity_contract_m bit,
	CONSTRAINT idm_contract_guarantee_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_dglppsjqr3kdnqtdbfipbtma5 FOREIGN KEY (rev) REFERENCES idm_audit(id)
);


CREATE TABLE idm_contract_slice_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	revtype smallint,
	created datetime,
	created_m bit,
	creator varchar(255),
	creator_m bit,
	creator_id binary(16),
	creator_id_m bit,
	modifier varchar(255),
	modifier_m bit,
	modifier_id binary(16),
	modifier_id_m bit,
	original_creator varchar(255),
	original_creator_m bit,
	original_creator_id binary(16),
	original_creator_id_m bit,
	original_modifier varchar(255),
	original_modifier_m bit,
	original_modifier_id binary(16),
	original_modifier_id_m bit,
	realm_id binary(16),
	realm_id_m bit,
	transaction_id binary(16),
	transaction_id_m bit,
	contract_code varchar(255),
	contract_code_m bit,
	contract_valid_from datetime,
	contract_valid_from_m bit,
	contract_valid_till datetime,
	contract_valid_till_m bit,
	description varchar(2000),
	description_m bit,
	disabled bit,
	disabled_m bit,
	external_id varchar(255),
	external_id_m bit,
	externe bit,
	externe_m bit,
	main bit,
	main_m bit,
	[position] varchar(255),
	position_m bit,
	state varchar(45),
	state_m bit,
	using_as_contract bit,
	using_as_contract_m bit,
	valid_from datetime,
	valid_from_m bit,
	valid_till datetime,
	valid_till_m bit,
	identity_id binary(16),
	identity_m bit,
	parent_contract_id binary(16),
	parent_contract_m bit,
	work_position_id binary(16),
	work_position_m bit,
	CONSTRAINT idm_contract_slice_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_fdq20kiyy3x2ly1meht7exxd1 FOREIGN KEY (rev) REFERENCES idm_audit(id)
);


CREATE TABLE idm_contract_slice_guarantee_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	revtype smallint,
	created datetime,
	created_m bit,
	creator varchar(255),
	creator_m bit,
	creator_id binary(16),
	creator_id_m bit,
	modifier varchar(255),
	modifier_m bit,
	modifier_id binary(16),
	modifier_id_m bit,
	original_creator varchar(255),
	original_creator_m bit,
	original_creator_id binary(16),
	original_creator_id_m bit,
	original_modifier varchar(255),
	original_modifier_m bit,
	original_modifier_id binary(16),
	original_modifier_id_m bit,
	realm_id binary(16),
	realm_id_m bit,
	transaction_id binary(16),
	transaction_id_m bit,
	contract_slice_id binary(16),
	contract_slice_m bit,
	guarantee_id binary(16),
	guarantee_m bit,
	CONSTRAINT idm_contract_slice_guarantee_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_nbb01g3t4g9o0hlcxxq7e75ci FOREIGN KEY (rev) REFERENCES idm_audit(id)
);


CREATE TABLE idm_form_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	revtype smallint,
	created datetime,
	created_m bit,
	creator varchar(255),
	creator_m bit,
	creator_id binary(16),
	creator_id_m bit,
	modifier varchar(255),
	modifier_m bit,
	modifier_id binary(16),
	modifier_id_m bit,
	original_creator varchar(255),
	original_creator_m bit,
	original_creator_id binary(16),
	original_creator_id_m bit,
	original_modifier varchar(255),
	original_modifier_m bit,
	original_modifier_id binary(16),
	original_modifier_id_m bit,
	realm_id binary(16),
	realm_id_m bit,
	transaction_id binary(16),
	transaction_id_m bit,
	name varchar(255),
	name_m bit,
	owner_code varchar(255),
	owner_code_m bit,
	owner_id binary(16),
	owner_id_m bit,
	owner_type varchar(255),
	owner_type_m bit,
	CONSTRAINT idm_form_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_idm_form_rev FOREIGN KEY (rev) REFERENCES idm_audit(id)
);


CREATE TABLE idm_form_attribute_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	revtype smallint,
	created datetime,
	created_m bit,
	creator varchar(255),
	creator_m bit,
	creator_id binary(16),
	creator_id_m bit,
	modifier varchar(255),
	modifier_m bit,
	modifier_id binary(16),
	modifier_id_m bit,
	original_creator varchar(255),
	original_creator_m bit,
	original_creator_id binary(16),
	original_creator_id_m bit,
	original_modifier varchar(255),
	original_modifier_m bit,
	original_modifier_id binary(16),
	original_modifier_id_m bit,
	realm_id binary(16),
	realm_id_m bit,
	transaction_id binary(16),
	transaction_id_m bit,
	code varchar(255),
	code_m bit,
	confidential bit,
	confidential_m bit,
	default_value text,
	default_value_m bit,
	description varchar(2000),
	description_m bit,
	face_type varchar(45),
	face_type_m bit,
	multiple bit,
	multiple_m bit,
	name varchar(255),
	name_m bit,
	persistent_type varchar(45),
	persistent_type_m bit,
	placeholder varchar(255),
	placeholder_m bit,
	readonly bit,
	readonly_m bit,
	required bit,
	required_m bit,
	seq smallint,
	seq_m bit,
	unmodifiable bit,
	unmodifiable_m bit,
	definition_id binary(16),
	form_definition_m bit,
	CONSTRAINT idm_form_attribute_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_87mqe2oxk3u5udokcqbpmd1s5 FOREIGN KEY (rev) REFERENCES idm_audit(id)
);


CREATE TABLE idm_form_definition_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	revtype smallint,
	created datetime,
	created_m bit,
	creator varchar(255),
	creator_m bit,
	creator_id binary(16),
	creator_id_m bit,
	modifier varchar(255),
	modifier_m bit,
	modifier_id binary(16),
	modifier_id_m bit,
	original_creator varchar(255),
	original_creator_m bit,
	original_creator_id binary(16),
	original_creator_id_m bit,
	original_modifier varchar(255),
	original_modifier_m bit,
	original_modifier_id binary(16),
	original_modifier_id_m bit,
	realm_id binary(16),
	realm_id_m bit,
	transaction_id binary(16),
	transaction_id_m bit,
	code varchar(255),
	code_m bit,
	description varchar(2000),
	description_m bit,
	main bit,
	main_m bit,
	name varchar(255),
	name_m bit,
	definition_type varchar(255),
	type_m bit,
	CONSTRAINT idm_form_definition_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_mpbe9mt8v8mbmomjiftoxftlf FOREIGN KEY (rev) REFERENCES idm_audit(id)
);


CREATE TABLE idm_form_value_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	revtype smallint,
	created datetime,
	created_m bit,
	creator varchar(255),
	creator_m bit,
	creator_id binary(16),
	creator_id_m bit,
	modifier varchar(255),
	modifier_m bit,
	modifier_id binary(16),
	modifier_id_m bit,
	original_creator varchar(255),
	original_creator_m bit,
	original_creator_id binary(16),
	original_creator_id_m bit,
	original_modifier varchar(255),
	original_modifier_m bit,
	original_modifier_id binary(16),
	original_modifier_id_m bit,
	realm_id binary(16),
	realm_id_m bit,
	transaction_id binary(16),
	transaction_id_m bit,
	boolean_value bit,
	boolean_value_m bit,
	byte_value varbinary(255),
	byte_value_m bit,
	confidential bit,
	confidential_m bit,
	date_value datetime,
	date_value_m bit,
	double_value numeric(38,4),
	double_value_m bit,
	long_value numeric(19,0),
	long_value_m bit,
	persistent_type varchar(45),
	persistent_type_m bit,
	seq smallint,
	seq_m bit,
	short_text_value varchar(2000),
	short_text_value_m bit,
	string_value text,
	string_value_m bit,
	uuid_value binary(16),
	uuid_value_m bit,
	attribute_id binary(16),
	form_attribute_m bit,
	owner_id binary(16),
	owner_m bit,
	CONSTRAINT idm_form_value_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_idm_form_value_rev FOREIGN KEY (rev) REFERENCES idm_audit(id)
);


CREATE TABLE idm_i_contract_form_value_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	revtype smallint,
	created datetime,
	created_m bit,
	creator varchar(255),
	creator_m bit,
	creator_id binary(16),
	creator_id_m bit,
	modifier varchar(255),
	modifier_m bit,
	modifier_id binary(16),
	modifier_id_m bit,
	original_creator varchar(255),
	original_creator_m bit,
	original_creator_id binary(16),
	original_creator_id_m bit,
	original_modifier varchar(255),
	original_modifier_m bit,
	original_modifier_id binary(16),
	original_modifier_id_m bit,
	realm_id binary(16),
	realm_id_m bit,
	transaction_id binary(16),
	transaction_id_m bit,
	boolean_value bit,
	boolean_value_m bit,
	byte_value varbinary(255),
	byte_value_m bit,
	confidential bit,
	confidential_m bit,
	date_value datetime,
	date_value_m bit,
	double_value numeric(38,4),
	double_value_m bit,
	long_value numeric(19,0),
	long_value_m bit,
	persistent_type varchar(45),
	persistent_type_m bit,
	seq smallint,
	seq_m bit,
	short_text_value varchar(2000),
	short_text_value_m bit,
	string_value text,
	string_value_m bit,
	uuid_value binary(16),
	uuid_value_m bit,
	attribute_id binary(16),
	form_attribute_m bit,
	owner_id binary(16),
	owner_m bit,
	CONSTRAINT idm_i_contract_form_value_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_qu8vg2k1wembpdp2jj1smb5s5 FOREIGN KEY (rev) REFERENCES idm_audit(id)
);


CREATE TABLE idm_identity_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	revtype smallint,
	created datetime,
	created_m bit,
	creator varchar(255),
	creator_m bit,
	creator_id binary(16),
	creator_id_m bit,
	modifier varchar(255),
	modifier_m bit,
	modifier_id binary(16),
	modifier_id_m bit,
	original_creator varchar(255),
	original_creator_m bit,
	original_creator_id binary(16),
	original_creator_id_m bit,
	original_modifier varchar(255),
	original_modifier_m bit,
	original_modifier_id binary(16),
	original_modifier_id_m bit,
	realm_id binary(16),
	realm_id_m bit,
	transaction_id binary(16),
	transaction_id_m bit,
	description varchar(2000),
	description_m bit,
	disabled bit,
	disabled_m bit,
	email varchar(255),
	email_m bit,
	external_code varchar(255),
	external_code_m bit,
	external_id varchar(255),
	external_id_m bit,
	first_name varchar(255),
	first_name_m bit,
	last_name varchar(255),
	last_name_m bit,
	phone varchar(30),
	phone_m bit,
	state varchar(45),
	state_m bit,
	title_after varchar(100),
	title_after_m bit,
	title_before varchar(100),
	title_before_m bit,
	username varchar(255),
	username_m bit,
	CONSTRAINT idm_identity_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_4pm45eprpsmhy5qnrkbgua56c FOREIGN KEY (rev) REFERENCES idm_audit(id)
);


CREATE TABLE idm_identity_contract_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	revtype smallint,
	created datetime,
	created_m bit,
	creator varchar(255),
	creator_m bit,
	creator_id binary(16),
	creator_id_m bit,
	modifier varchar(255),
	modifier_m bit,
	modifier_id binary(16),
	modifier_id_m bit,
	original_creator varchar(255),
	original_creator_m bit,
	original_creator_id binary(16),
	original_creator_id_m bit,
	original_modifier varchar(255),
	original_modifier_m bit,
	original_modifier_id binary(16),
	original_modifier_id_m bit,
	realm_id binary(16),
	realm_id_m bit,
	transaction_id binary(16),
	transaction_id_m bit,
	description varchar(2000),
	description_m bit,
	disabled bit,
	disabled_m bit,
	external_id varchar(255),
	external_id_m bit,
	externe bit,
	externe_m bit,
	main bit,
	main_m bit,
	[position] varchar(255),
	position_m bit,
	state varchar(45),
	state_m bit,
	valid_from datetime,
	valid_from_m bit,
	valid_till datetime,
	valid_till_m bit,
	identity_id binary(16),
	identity_m bit,
	work_position_id binary(16),
	work_position_m bit,
	CONSTRAINT idm_identity_contract_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_o27u52ytamblwynwf958a7rna FOREIGN KEY (rev) REFERENCES idm_audit(id)
);


CREATE TABLE idm_identity_form_value_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	revtype smallint,
	created datetime,
	created_m bit,
	creator varchar(255),
	creator_m bit,
	creator_id binary(16),
	creator_id_m bit,
	modifier varchar(255),
	modifier_m bit,
	modifier_id binary(16),
	modifier_id_m bit,
	original_creator varchar(255),
	original_creator_m bit,
	original_creator_id binary(16),
	original_creator_id_m bit,
	original_modifier varchar(255),
	original_modifier_m bit,
	original_modifier_id binary(16),
	original_modifier_id_m bit,
	realm_id binary(16),
	realm_id_m bit,
	transaction_id binary(16),
	transaction_id_m bit,
	boolean_value bit,
	boolean_value_m bit,
	byte_value varbinary(255),
	byte_value_m bit,
	confidential bit,
	confidential_m bit,
	date_value datetime,
	date_value_m bit,
	double_value numeric(38,4),
	double_value_m bit,
	long_value numeric(19,0),
	long_value_m bit,
	persistent_type varchar(45),
	persistent_type_m bit,
	seq smallint,
	seq_m bit,
	short_text_value varchar(2000),
	short_text_value_m bit,
	string_value text,
	string_value_m bit,
	uuid_value binary(16),
	uuid_value_m bit,
	attribute_id binary(16),
	form_attribute_m bit,
	owner_id binary(16),
	owner_m bit,
	CONSTRAINT idm_identity_form_value_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_j85k7gu9fuv136lcim1yf442d FOREIGN KEY (rev) REFERENCES idm_audit(id)
);


CREATE TABLE idm_identity_role_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	revtype smallint,
	created datetime,
	created_m bit,
	creator varchar(255),
	creator_m bit,
	creator_id binary(16),
	creator_id_m bit,
	modifier varchar(255),
	modifier_m bit,
	modifier_id binary(16),
	modifier_id_m bit,
	original_creator varchar(255),
	original_creator_m bit,
	original_creator_id binary(16),
	original_creator_id_m bit,
	original_modifier varchar(255),
	original_modifier_m bit,
	original_modifier_id binary(16),
	original_modifier_id_m bit,
	realm_id binary(16),
	realm_id_m bit,
	transaction_id binary(16),
	transaction_id_m bit,
	external_id varchar(255),
	external_id_m bit,
	valid_from datetime,
	valid_from_m bit,
	valid_till datetime,
	valid_till_m bit,
	automatic_role_id binary(16),
	automatic_role_m bit,
	identity_contract_id binary(16),
	identity_contract_m bit,
	role_id binary(16),
	role_m bit,
	CONSTRAINT idm_identity_role_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_6f8hi53e37sxhyti4xlxx0k34 FOREIGN KEY (rev) REFERENCES idm_audit(id)
);


CREATE TABLE idm_notification_configuration_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	revtype smallint,
	created datetime,
	created_m bit,
	creator varchar(255),
	creator_m bit,
	creator_id binary(16),
	creator_id_m bit,
	modifier varchar(255),
	modifier_m bit,
	modifier_id binary(16),
	modifier_id_m bit,
	original_creator varchar(255),
	original_creator_m bit,
	original_creator_id binary(16),
	original_creator_id_m bit,
	original_modifier varchar(255),
	original_modifier_m bit,
	original_modifier_id binary(16),
	original_modifier_id_m bit,
	realm_id binary(16),
	realm_id_m bit,
	transaction_id binary(16),
	transaction_id_m bit,
	description varchar(2000),
	description_m bit,
	notification_type varchar(255),
	notification_type_m bit,
	topic varchar(255),
	topic_m bit,
	template_id binary(16),
	template_m bit,
	CONSTRAINT idm_notification_configuration_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_198fj5oy8o3fejsnhvryul3p8 FOREIGN KEY (rev) REFERENCES idm_audit(id)
);


CREATE TABLE idm_notification_template_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	revtype smallint,
	created datetime,
	created_m bit,
	creator varchar(255),
	creator_m bit,
	creator_id binary(16),
	creator_id_m bit,
	modifier varchar(255),
	modifier_m bit,
	modifier_id binary(16),
	modifier_id_m bit,
	original_creator varchar(255),
	original_creator_m bit,
	original_creator_id binary(16),
	original_creator_id_m bit,
	original_modifier varchar(255),
	original_modifier_m bit,
	original_modifier_id binary(16),
	original_modifier_id_m bit,
	realm_id binary(16),
	realm_id_m bit,
	transaction_id binary(16),
	transaction_id_m bit,
	body_html text,
	body_html_m bit,
	body_text text,
	body_text_m bit,
	code varchar(255),
	code_m bit,
	module varchar(255),
	module_m bit,
	name varchar(255),
	name_m bit,
	[parameter] varchar(255),
	parameter_m bit,
	sender varchar(255),
	sender_m bit,
	subject varchar(255),
	subject_m bit,
	CONSTRAINT idm_notification_template_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_pxuc0kajt3bs0malyc4iy86tt FOREIGN KEY (rev) REFERENCES idm_audit(id)
);

CREATE TABLE idm_password_policy_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	revtype smallint,
	created datetime,
	created_m bit,
	creator varchar(255),
	creator_m bit,
	creator_id binary(16),
	creator_id_m bit,
	modifier varchar(255),
	modifier_m bit,
	modifier_id binary(16),
	modifier_id_m bit,
	original_creator varchar(255),
	original_creator_m bit,
	original_creator_id binary(16),
	original_creator_id_m bit,
	original_modifier varchar(255),
	original_modifier_m bit,
	original_modifier_id binary(16),
	original_modifier_id_m bit,
	realm_id binary(16),
	realm_id_m bit,
	transaction_id binary(16),
	transaction_id_m bit,
	block_login_time int,
	block_login_time_m bit,
	default_policy bit,
	default_policy_m bit,
	description varchar(2000),
	description_m bit,
	disabled bit,
	disabled_m bit,
	enchanced_control bit,
	enchanced_control_m bit,
	generate_type varchar(255),
	generate_type_m bit,
	identity_attribute_check varchar(255),
	identity_attribute_check_m bit,
	lower_char_base varchar(255),
	lower_char_base_m bit,
	lower_char_required bit,
	lower_char_required_m bit,
	max_history_similar int,
	max_history_similar_m bit,
	max_password_age int,
	max_password_age_m bit,
	max_password_length int,
	max_password_length_m bit,
	max_unsuccessful_attempts int,
	max_unsuccessful_attempts_m bit,
	min_lower_char int,
	min_lower_char_m bit,
	min_number int,
	min_number_m bit,
	min_password_age int,
	min_password_age_m bit,
	min_password_length int,
	min_password_length_m bit,
	min_rules_to_fulfill int,
	min_rules_to_fulfill_m bit,
	min_special_char int,
	min_special_char_m bit,
	min_upper_char int,
	min_upper_char_m bit,
	name varchar(255),
	name_m bit,
	number_base varchar(255),
	number_base_m bit,
	number_required bit,
	number_required_m bit,
	passphrase_words int,
	passphrase_words_m bit,
	password_length_required bit,
	password_length_required_m bit,
	prohibited_characters varchar(255),
	prohibited_characters_m bit,
	special_char_base varchar(255),
	special_char_base_m bit,
	special_char_required bit,
	special_char_required_m bit,
	[type] varchar(255),
	type_m bit,
	upper_char_base varchar(255),
	upper_char_base_m bit,
	upper_char_required bit,
	upper_char_required_m bit,
	weak_pass varchar(255),
	weak_pass_m bit,
	weak_pass_required bit,
	weak_pass_required_m bit,
	CONSTRAINT idm_password_policy_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_swya50ugpjfiuh5hdw1k1wgbm FOREIGN KEY (rev) REFERENCES idm_audit(id)
);


CREATE TABLE idm_profile_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	revtype smallint,
	created datetime,
	created_m bit,
	creator varchar(255),
	creator_m bit,
	creator_id binary(16),
	creator_id_m bit,
	modifier varchar(255),
	modifier_m bit,
	modifier_id binary(16),
	modifier_id_m bit,
	original_creator varchar(255),
	original_creator_m bit,
	original_creator_id binary(16),
	original_creator_id_m bit,
	original_modifier varchar(255),
	original_modifier_m bit,
	original_modifier_id binary(16),
	original_modifier_id_m bit,
	realm_id binary(16),
	realm_id_m bit,
	transaction_id binary(16),
	transaction_id_m bit,
	preferred_language varchar(45),
	preferred_language_m bit,
	identity_id binary(16),
	identity_m bit,
	image_id binary(16),
	image_m bit,
	CONSTRAINT idm_profile_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_l70tqy66dd7lcx5by8egpg11a FOREIGN KEY (rev) REFERENCES idm_audit(id)
);



CREATE TABLE idm_password_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	revtype smallint,
	created datetime,
	created_m bit,
	creator varchar(255),
	creator_m bit,
	creator_id binary(16),
	creator_id_m bit,
	modifier varchar(255),
	modifier_m bit,
	modifier_id binary(16),
	modifier_id_m bit,
	original_creator varchar(255),
	original_creator_m bit,
	original_creator_id binary(16),
	original_creator_id_m bit,
	original_modifier varchar(255),
	original_modifier_m bit,
	original_modifier_id binary(16),
	original_modifier_id_m bit,
	realm_id binary(16),
	realm_id_m bit,
	transaction_id binary(16),
	transaction_id_m bit,
	block_login_date datetime,
	block_login_date_m bit,
	last_successful_login datetime,
	last_successful_login_m bit,
	must_change bit,
	must_change_m bit,
	unsuccessful_attempts int,
	unsuccessful_attempts_m bit,
	valid_from datetime,
	valid_from_m bit,
	valid_till datetime,
	valid_till_m bit,
	identity_id binary(16),
	identity_m bit,
	CONSTRAINT idm_password_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_1t5dpjknl7r4lxhfauqu1h2tm FOREIGN KEY (rev) REFERENCES idm_audit(id)
);


CREATE TABLE idm_role_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	revtype smallint,
	created datetime,
	created_m bit,
	creator varchar(255),
	creator_m bit,
	creator_id binary(16),
	creator_id_m bit,
	modifier varchar(255),
	modifier_m bit,
	modifier_id binary(16),
	modifier_id_m bit,
	original_creator varchar(255),
	original_creator_m bit,
	original_creator_id binary(16),
	original_creator_id_m bit,
	original_modifier varchar(255),
	original_modifier_m bit,
	original_modifier_id binary(16),
	original_modifier_id_m bit,
	realm_id binary(16),
	realm_id_m bit,
	transaction_id binary(16),
	transaction_id_m bit,
	approve_remove bit,
	approve_remove_m bit,
	can_be_requested bit,
	can_be_requested_m bit,
	description varchar(2000),
	description_m bit,
	disabled bit,
	disabled_m bit,
	external_id varchar(255),
	external_id_m bit,
	name varchar(255),
	name_m bit,
	priority int,
	priority_m bit,
	role_type varchar(255),
	role_type_m bit,
	CONSTRAINT idm_role_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_nwuujf2vpbphudbfcvxdj3exp FOREIGN KEY (rev) REFERENCES idm_audit(id)
);


CREATE TABLE idm_role_catalogue_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	revtype smallint,
	created datetime,
	created_m bit,
	creator varchar(255),
	creator_m bit,
	creator_id binary(16),
	creator_id_m bit,
	modifier varchar(255),
	modifier_m bit,
	modifier_id binary(16),
	modifier_id_m bit,
	original_creator varchar(255),
	original_creator_m bit,
	original_creator_id binary(16),
	original_creator_id_m bit,
	original_modifier varchar(255),
	original_modifier_m bit,
	original_modifier_id binary(16),
	original_modifier_id_m bit,
	realm_id binary(16),
	realm_id_m bit,
	transaction_id binary(16),
	transaction_id_m bit,
	code varchar(255),
	code_m bit,
	description varchar(2000),
	description_m bit,
	external_id varchar(255),
	external_id_m bit,
	name varchar(255),
	name_m bit,
	url varchar(255),
	url_m bit,
	url_title varchar(255),
	url_title_m bit,
	parent_id binary(16),
	parent_m bit,
	CONSTRAINT idm_role_catalogue_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_pirc5x13v836h3hmyt0cc42kv FOREIGN KEY (rev) REFERENCES idm_audit(id)
);


CREATE TABLE idm_role_catalogue_role_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	revtype smallint,
	created datetime,
	created_m bit,
	creator varchar(255),
	creator_m bit,
	creator_id binary(16),
	creator_id_m bit,
	modifier varchar(255),
	modifier_m bit,
	modifier_id binary(16),
	modifier_id_m bit,
	original_creator varchar(255),
	original_creator_m bit,
	original_creator_id binary(16),
	original_creator_id_m bit,
	original_modifier varchar(255),
	original_modifier_m bit,
	original_modifier_id binary(16),
	original_modifier_id_m bit,
	realm_id binary(16),
	realm_id_m bit,
	transaction_id binary(16),
	transaction_id_m bit,
	role_id binary(16),
	role_m bit,
	role_catalogue_id binary(16),
	role_catalogue_m bit,
	CONSTRAINT idm_role_catalogue_role_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_l085dvgnnwk6e46daedndy6sr FOREIGN KEY (rev) REFERENCES idm_audit(id)
);


CREATE TABLE idm_role_composition_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	revtype smallint,
	created datetime,
	created_m bit,
	creator varchar(255),
	creator_m bit,
	creator_id binary(16),
	creator_id_m bit,
	modifier varchar(255),
	modifier_m bit,
	modifier_id binary(16),
	modifier_id_m bit,
	original_creator varchar(255),
	original_creator_m bit,
	original_creator_id binary(16),
	original_creator_id_m bit,
	original_modifier varchar(255),
	original_modifier_m bit,
	original_modifier_id binary(16),
	original_modifier_id_m bit,
	realm_id binary(16),
	realm_id_m bit,
	transaction_id binary(16),
	transaction_id_m bit,
	sub_id binary(16),
	sub_m bit,
	superior_id binary(16),
	superior_m bit,
	CONSTRAINT idm_role_composition_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_a8jshb3t1vrfp1vp0819x6h8q FOREIGN KEY (rev) REFERENCES idm_audit(id)
);


CREATE TABLE idm_role_form_value_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	revtype smallint,
	created datetime,
	created_m bit,
	creator varchar(255),
	creator_m bit,
	creator_id binary(16),
	creator_id_m bit,
	modifier varchar(255),
	modifier_m bit,
	modifier_id binary(16),
	modifier_id_m bit,
	original_creator varchar(255),
	original_creator_m bit,
	original_creator_id binary(16),
	original_creator_id_m bit,
	original_modifier varchar(255),
	original_modifier_m bit,
	original_modifier_id binary(16),
	original_modifier_id_m bit,
	realm_id binary(16),
	realm_id_m bit,
	transaction_id binary(16),
	transaction_id_m bit,
	boolean_value bit,
	boolean_value_m bit,
	byte_value varbinary(255),
	byte_value_m bit,
	confidential bit,
	confidential_m bit,
	date_value datetime,
	date_value_m bit,
	double_value numeric(38,4),
	double_value_m bit,
	long_value numeric(19,0),
	long_value_m bit,
	persistent_type varchar(45),
	persistent_type_m bit,
	seq smallint,
	seq_m bit,
	short_text_value varchar(2000),
	short_text_value_m bit,
	string_value text,
	string_value_m bit,
	uuid_value binary(16),
	uuid_value_m bit,
	attribute_id binary(16),
	form_attribute_m bit,
	owner_id binary(16),
	owner_m bit,
	CONSTRAINT idm_role_form_value_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_gfx77xleqng5i3jipnm4648sr FOREIGN KEY (rev) REFERENCES idm_audit(id)
);


CREATE TABLE idm_role_guarantee_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	revtype smallint,
	created datetime,
	created_m bit,
	creator varchar(255),
	creator_m bit,
	creator_id binary(16),
	creator_id_m bit,
	modifier varchar(255),
	modifier_m bit,
	modifier_id binary(16),
	modifier_id_m bit,
	original_creator varchar(255),
	original_creator_m bit,
	original_creator_id binary(16),
	original_creator_id_m bit,
	original_modifier varchar(255),
	original_modifier_m bit,
	original_modifier_id binary(16),
	original_modifier_id_m bit,
	realm_id binary(16),
	realm_id_m bit,
	transaction_id binary(16),
	transaction_id_m bit,
	guarantee_id binary(16),
	guarantee_m bit,
	role_id binary(16),
	role_m bit,
	CONSTRAINT idm_role_guarantee_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_spgix52wl4u4ajm06ha9jiajv FOREIGN KEY (rev) REFERENCES idm_audit(id)
);


CREATE TABLE idm_role_guarantee_role_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	revtype smallint,
	created datetime,
	created_m bit,
	creator varchar(255),
	creator_m bit,
	creator_id binary(16),
	creator_id_m bit,
	modifier varchar(255),
	modifier_m bit,
	modifier_id binary(16),
	modifier_id_m bit,
	original_creator varchar(255),
	original_creator_m bit,
	original_creator_id binary(16),
	original_creator_id_m bit,
	original_modifier varchar(255),
	original_modifier_m bit,
	original_modifier_id binary(16),
	original_modifier_id_m bit,
	realm_id binary(16),
	realm_id_m bit,
	transaction_id binary(16),
	transaction_id_m bit,
	guarantee_role_id binary(16),
	guarantee_role_m bit,
	role_id binary(16),
	role_m bit,
	CONSTRAINT idm_role_guarantee_role_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_52w0m9i93h9galqewk813qqd3 FOREIGN KEY (rev) REFERENCES idm_audit(id)
);


CREATE TABLE idm_role_request_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	revtype smallint,
	created datetime,
	created_m bit,
	creator varchar(255),
	creator_m bit,
	creator_id binary(16),
	creator_id_m bit,
	modifier varchar(255),
	modifier_m bit,
	modifier_id binary(16),
	modifier_id_m bit,
	original_creator varchar(255),
	original_creator_m bit,
	original_creator_id binary(16),
	original_creator_id_m bit,
	original_modifier varchar(255),
	original_modifier_m bit,
	original_modifier_id binary(16),
	original_modifier_id_m bit,
	realm_id binary(16),
	realm_id_m bit,
	transaction_id binary(16),
	transaction_id_m bit,
	description varchar(255),
	description_m bit,
	execute_immediately bit,
	execute_immediately_m bit,
	requested_by_type varchar(255),
	requested_by_type_m bit,
	state varchar(255),
	state_m bit,
	wf_process_id varchar(255),
	wf_process_id_m bit,
	applicant_id binary(16),
	applicant_m bit,
	duplicated_to_request binary(16),
	duplicated_to_request_m bit,
	CONSTRAINT idm_role_request_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_o61enmny8d3wffg87pvfhi2m3 FOREIGN KEY (rev) REFERENCES idm_audit(id)
);


CREATE TABLE idm_role_tree_node_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	recursion_type varchar(255),
	recursion_type_m bit,
	tree_node_id binary(16),
	tree_node_m bit,
	CONSTRAINT idm_role_tree_node_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_gvppr8wma5biag712dyjedvjf FOREIGN KEY (id,rev) REFERENCES idm_auto_role_a(id,rev)
);


CREATE TABLE idm_scheduled_task_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	revtype smallint,
	created datetime,
	created_m bit,
	creator varchar(255),
	creator_m bit,
	creator_id binary(16),
	creator_id_m bit,
	modifier varchar(255),
	modifier_m bit,
	modifier_id binary(16),
	modifier_id_m bit,
	original_creator varchar(255),
	original_creator_m bit,
	original_creator_id binary(16),
	original_creator_id_m bit,
	original_modifier varchar(255),
	original_modifier_m bit,
	original_modifier_id binary(16),
	original_modifier_id_m bit,
	realm_id binary(16),
	realm_id_m bit,
	transaction_id binary(16),
	transaction_id_m bit,
	quartz_task_name varchar(255),
	quartz_task_name_m bit,
	CONSTRAINT idm_scheduled_task_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_mdjjd0gqna0tw0ewqf571abj5 FOREIGN KEY (rev) REFERENCES idm_audit(id)
);


CREATE TABLE idm_script_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	revtype smallint,
	created datetime,
	created_m bit,
	creator varchar(255),
	creator_m bit,
	creator_id binary(16),
	creator_id_m bit,
	modifier varchar(255),
	modifier_m bit,
	modifier_id binary(16),
	modifier_id_m bit,
	original_creator varchar(255),
	original_creator_m bit,
	original_creator_id binary(16),
	original_creator_id_m bit,
	original_modifier varchar(255),
	original_modifier_m bit,
	original_modifier_id binary(16),
	original_modifier_id_m bit,
	realm_id binary(16),
	realm_id_m bit,
	transaction_id binary(16),
	transaction_id_m bit,
	category varchar(255),
	category_m bit,
	code varchar(255),
	code_m bit,
	description varchar(2000),
	description_m bit,
	name varchar(255),
	name_m bit,
	script text,
	script_m bit,
	CONSTRAINT idm_script_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_a0o0bhr6om9dd80tdawuennqp FOREIGN KEY (rev) REFERENCES idm_audit(id)
);


CREATE TABLE idm_script_authority_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	revtype smallint,
	created datetime,
	created_m bit,
	creator varchar(255),
	creator_m bit,
	creator_id binary(16),
	creator_id_m bit,
	modifier varchar(255),
	modifier_m bit,
	modifier_id binary(16),
	modifier_id_m bit,
	original_creator varchar(255),
	original_creator_m bit,
	original_creator_id binary(16),
	original_creator_id_m bit,
	original_modifier varchar(255),
	original_modifier_m bit,
	original_modifier_id binary(16),
	original_modifier_id_m bit,
	realm_id binary(16),
	realm_id_m bit,
	transaction_id binary(16),
	transaction_id_m bit,
	class_name varchar(255),
	class_name_m bit,
	service varchar(255),
	service_m bit,
	[type] varchar(255),
	type_m bit,
	script_id binary(16),
	script_m bit,
	CONSTRAINT idm_script_authority_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_idm_script_authority_a_rev FOREIGN KEY (rev) REFERENCES idm_audit(id)
);


CREATE TABLE idm_tree_node_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	revtype smallint,
	created datetime,
	created_m bit,
	creator varchar(255),
	creator_m bit,
	creator_id binary(16),
	creator_id_m bit,
	modifier varchar(255),
	modifier_m bit,
	modifier_id binary(16),
	modifier_id_m bit,
	original_creator varchar(255),
	original_creator_m bit,
	original_creator_id binary(16),
	original_creator_id_m bit,
	original_modifier varchar(255),
	original_modifier_m bit,
	original_modifier_id binary(16),
	original_modifier_id_m bit,
	realm_id binary(16),
	realm_id_m bit,
	transaction_id binary(16),
	transaction_id_m bit,
	code varchar(255),
	code_m bit,
	disabled bit,
	disabled_m bit,
	external_id varchar(255),
	external_id_m bit,
	name varchar(255),
	name_m bit,
	parent_id binary(16),
	parent_m bit,
	tree_type_id binary(16),
	tree_type_m bit,
	CONSTRAINT idm_tree_node_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_pfe3d9yuunnvu0caum686sji8 FOREIGN KEY (rev) REFERENCES idm_audit(id)
);


CREATE TABLE idm_tree_node_form_value_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	revtype smallint,
	created datetime,
	created_m bit,
	creator varchar(255),
	creator_m bit,
	creator_id binary(16),
	creator_id_m bit,
	modifier varchar(255),
	modifier_m bit,
	modifier_id binary(16),
	modifier_id_m bit,
	original_creator varchar(255),
	original_creator_m bit,
	original_creator_id binary(16),
	original_creator_id_m bit,
	original_modifier varchar(255),
	original_modifier_m bit,
	original_modifier_id binary(16),
	original_modifier_id_m bit,
	realm_id binary(16),
	realm_id_m bit,
	transaction_id binary(16),
	transaction_id_m bit,
	boolean_value bit,
	boolean_value_m bit,
	byte_value varbinary(255),
	byte_value_m bit,
	confidential bit,
	confidential_m bit,
	date_value datetime,
	date_value_m bit,
	double_value numeric(38,4),
	double_value_m bit,
	long_value numeric(19,0),
	long_value_m bit,
	persistent_type varchar(45),
	persistent_type_m bit,
	seq smallint,
	seq_m bit,
	short_text_value varchar(2000),
	short_text_value_m bit,
	string_value text,
	string_value_m bit,
	uuid_value binary(16),
	uuid_value_m bit,
	attribute_id binary(16),
	form_attribute_m bit,
	owner_id binary(16),
	owner_m bit,
	CONSTRAINT idm_tree_node_form_value_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_82r94pui8abb9sapy4y2a07g7 FOREIGN KEY (rev) REFERENCES idm_audit(id)
);


CREATE TABLE idm_tree_type_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	revtype smallint,
	created datetime,
	created_m bit,
	creator varchar(255),
	creator_m bit,
	creator_id binary(16),
	creator_id_m bit,
	modifier varchar(255),
	modifier_m bit,
	modifier_id binary(16),
	modifier_id_m bit,
	original_creator varchar(255),
	original_creator_m bit,
	original_creator_id binary(16),
	original_creator_id_m bit,
	original_modifier varchar(255),
	original_modifier_m bit,
	original_modifier_id binary(16),
	original_modifier_id_m bit,
	realm_id binary(16),
	realm_id_m bit,
	transaction_id binary(16),
	transaction_id_m bit,
	code varchar(255),
	code_m bit,
	external_id varchar(255),
	external_id_m bit,
	name varchar(255),
	name_m bit,
	CONSTRAINT idm_tree_type_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_f9ipost6xa40kv7bu5gqti3sa FOREIGN KEY (rev) REFERENCES idm_audit(id)
);


CREATE TABLE revchanges (
	rev numeric(19,0) NOT NULL,
	modified_entity_names varchar(255),
	CONSTRAINT fk_et6b2lrkqkab5mhvxkv861n8h FOREIGN KEY (rev) REFERENCES idm_audit(id)
);
CREATE INDEX idx_revchanges ON revchanges (rev);
