--
-- CzechIdM 9.0 Flyway script 
-- BCV solutions s.r.o.
--
-- This is initial SQL script for Sql Server

CREATE TABLE acc_account (
	id binary(16) NOT NULL,
	created datetime2(6) NOT NULL,
	creator NVARCHAR(255) NOT NULL,
	creator_id binary(16),
	modified datetime2(6),
	modifier NVARCHAR(255),
	modifier_id binary(16),
	original_creator NVARCHAR(255),
	original_creator_id binary(16),
	original_modifier NVARCHAR(255),
	original_modifier_id binary(16),
	realm_id binary(16),
	transaction_id binary(16),
	account_type NVARCHAR(255) NOT NULL,
	end_of_protection datetime2(6),
	entity_type NVARCHAR(255),
	in_protection bit,
	uid NVARCHAR(1000) NOT NULL,
	system_id binary(16) NOT NULL,
	system_entity_id binary(16),
	CONSTRAINT acc_account_pkey PRIMARY KEY (id)
);
CREATE INDEX idx_acc_account_sys_entity ON acc_account (system_entity_id);
CREATE INDEX idx_acc_account_sys_id ON acc_account (system_id);
CREATE UNIQUE INDEX ux_acc_account_sys_entity ON acc_account (system_entity_id);
CREATE UNIQUE INDEX ux_account_uid ON acc_account (uid,system_id);


CREATE TABLE acc_contract_account (
	id binary(16) NOT NULL,
	created datetime2(6) NOT NULL,
	creator NVARCHAR(255) NOT NULL,
	creator_id binary(16),
	modified datetime2(6),
	modifier NVARCHAR(255),
	modifier_id binary(16),
	original_creator NVARCHAR(255),
	original_creator_id binary(16),
	original_modifier NVARCHAR(255),
	original_modifier_id binary(16),
	realm_id binary(16),
	transaction_id binary(16),
	ownership bit NOT NULL,
	account_id binary(16) NOT NULL,
	contract_id binary(16) NOT NULL,
	CONSTRAINT acc_contract_account_pkey PRIMARY KEY (id)
);
CREATE INDEX idx_acc_contr_acc_acc ON acc_contract_account (account_id);
CREATE INDEX idx_acc_contr_acc_contr ON acc_contract_account (contract_id);


CREATE TABLE acc_contract_slice_account (
	id binary(16) NOT NULL,
	created datetime2(6) NOT NULL,
	creator NVARCHAR(255) NOT NULL,
	creator_id binary(16),
	modified datetime2(6),
	modifier NVARCHAR(255),
	modifier_id binary(16),
	original_creator NVARCHAR(255),
	original_creator_id binary(16),
	original_modifier NVARCHAR(255),
	original_modifier_id binary(16),
	realm_id binary(16),
	transaction_id binary(16),
	ownership bit NOT NULL,
	account_id binary(16) NOT NULL,
	contract_slice_id binary(16) NOT NULL,
	CONSTRAINT acc_contract_slice_account_pkey PRIMARY KEY (id)
);
CREATE INDEX idx_acc_contr_sli_acc ON acc_contract_slice_account (account_id);
CREATE INDEX idx_acc_contr_sli_contr ON acc_contract_slice_account (contract_slice_id);


CREATE TABLE acc_identity_account (
	id binary(16) NOT NULL,
	created datetime2(6) NOT NULL,
	creator NVARCHAR(255) NOT NULL,
	creator_id binary(16),
	modified datetime2(6),
	modifier NVARCHAR(255),
	modifier_id binary(16),
	original_creator NVARCHAR(255),
	original_creator_id binary(16),
	original_modifier NVARCHAR(255),
	original_modifier_id binary(16),
	realm_id binary(16),
	transaction_id binary(16),
	ownership bit NOT NULL,
	account_id binary(16) NOT NULL,
	identity_id binary(16) NOT NULL,
	identity_role_id binary(16),
	role_system_id binary(16),
	CONSTRAINT acc_identity_account_pkey PRIMARY KEY (id)
);
CREATE INDEX idx_acc_identity_account_acc ON acc_identity_account (account_id);
CREATE INDEX idx_acc_identity_account_ident ON acc_identity_account (identity_id);
CREATE INDEX idx_acc_identity_identity_role ON acc_identity_account (identity_role_id);
CREATE UNIQUE INDEX ux_identity_account ON acc_identity_account (identity_id,account_id,role_system_id,identity_role_id);


CREATE TABLE acc_role_account (
	id binary(16) NOT NULL,
	created datetime2(6) NOT NULL,
	creator NVARCHAR(255) NOT NULL,
	creator_id binary(16),
	modified datetime2(6),
	modifier NVARCHAR(255),
	modifier_id binary(16),
	original_creator NVARCHAR(255),
	original_creator_id binary(16),
	original_modifier NVARCHAR(255),
	original_modifier_id binary(16),
	realm_id binary(16),
	transaction_id binary(16),
	ownership bit NOT NULL,
	account_id binary(16) NOT NULL,
	role_id binary(16) NOT NULL,
	CONSTRAINT acc_role_account_pkey PRIMARY KEY (id)
);
CREATE INDEX idx_acc_role_account_acc ON acc_role_account (account_id);
CREATE INDEX idx_acc_role_account_role ON acc_role_account (role_id);


CREATE TABLE acc_role_catalogue_account (
	id binary(16) NOT NULL,
	created datetime2(6) NOT NULL,
	creator NVARCHAR(255) NOT NULL,
	creator_id binary(16),
	modified datetime2(6),
	modifier NVARCHAR(255),
	modifier_id binary(16),
	original_creator NVARCHAR(255),
	original_creator_id binary(16),
	original_modifier NVARCHAR(255),
	original_modifier_id binary(16),
	realm_id binary(16),
	transaction_id binary(16),
	ownership bit NOT NULL,
	account_id binary(16) NOT NULL,
	role_catalogue_id binary(16) NOT NULL,
	role_system_id binary(16),
	CONSTRAINT acc_role_catalogue_account_pkey PRIMARY KEY (id)
);
CREATE INDEX idx_acc_cat_account_acc ON acc_role_catalogue_account (account_id);
CREATE INDEX idx_acc_cat_account_tree ON acc_role_catalogue_account (role_catalogue_id);


CREATE TABLE acc_tree_account (
	id binary(16) NOT NULL,
	created datetime2(6) NOT NULL,
	creator NVARCHAR(255) NOT NULL,
	creator_id binary(16),
	modified datetime2(6),
	modifier NVARCHAR(255),
	modifier_id binary(16),
	original_creator NVARCHAR(255),
	original_creator_id binary(16),
	original_modifier NVARCHAR(255),
	original_modifier_id binary(16),
	realm_id binary(16),
	transaction_id binary(16),
	ownership bit NOT NULL,
	account_id binary(16) NOT NULL,
	role_system_id binary(16),
	tree_node_id binary(16) NOT NULL,
	CONSTRAINT acc_tree_account_pkey PRIMARY KEY (id)
);
CREATE INDEX idx_acc_tree_account_acc ON acc_tree_account (account_id);
CREATE INDEX idx_acc_tree_account_tree ON acc_tree_account (tree_node_id);


CREATE TABLE sys_provisioning_archive (
	id binary(16) NOT NULL,
	created datetime2(6) NOT NULL,
	creator NVARCHAR(255) NOT NULL,
	creator_id binary(16),
	modified datetime2(6),
	modifier NVARCHAR(255),
	modifier_id binary(16),
	original_creator NVARCHAR(255),
	original_creator_id binary(16),
	original_modifier NVARCHAR(255),
	original_modifier_id binary(16),
	realm_id binary(16),
	transaction_id binary(16),
	entity_identifier binary(255),
	entity_type NVARCHAR(255) NOT NULL,
	operation_type NVARCHAR(255) NOT NULL,
	provisioning_context image NOT NULL,
	result_cause nvarchar(MAX),
	result_code NVARCHAR(255),
	result_model image,
	result_state NVARCHAR(45) NOT NULL,
	system_entity_uid NVARCHAR(255),
	system_id binary(16) NOT NULL,
	CONSTRAINT sys_provisioning_archive_pkey PRIMARY KEY (id)
);
CREATE INDEX idx_sys_p_o_arch_created ON sys_provisioning_archive (created);
CREATE INDEX idx_sys_p_o_arch_entity_identifier ON sys_provisioning_archive (entity_identifier);
CREATE INDEX idx_sys_p_o_arch_entity_type ON sys_provisioning_archive (entity_type);
CREATE INDEX idx_sys_p_o_arch_operation_type ON sys_provisioning_archive (operation_type);
CREATE INDEX idx_sys_p_o_arch_system ON sys_provisioning_archive (system_id);
CREATE INDEX idx_sys_p_o_arch_uid ON sys_provisioning_archive (system_entity_uid);


CREATE TABLE sys_provisioning_batch (
	id binary(16) NOT NULL,
	created datetime2(6) NOT NULL,
	creator NVARCHAR(255) NOT NULL,
	creator_id binary(16),
	modified datetime2(6),
	modifier NVARCHAR(255),
	modifier_id binary(16),
	original_creator NVARCHAR(255),
	original_creator_id binary(16),
	original_modifier NVARCHAR(255),
	original_modifier_id binary(16),
	realm_id binary(16),
	transaction_id binary(16),
	next_attempt datetime2(6),
	system_entity_id binary(16) NOT NULL,
	CONSTRAINT sys_provisioning_batch_pkey PRIMARY KEY (id)
);
CREATE INDEX idx_sys_p_b_next ON sys_provisioning_batch (next_attempt);
CREATE INDEX idx_sys_p_b_sys_entity ON sys_provisioning_batch (system_entity_id);


CREATE TABLE sys_provisioning_break_config (
	id binary(16) NOT NULL,
	created datetime2(6) NOT NULL,
	creator NVARCHAR(255) NOT NULL,
	creator_id binary(16),
	modified datetime2(6),
	modifier NVARCHAR(255),
	modifier_id binary(16),
	original_creator NVARCHAR(255),
	original_creator_id binary(16),
	original_modifier NVARCHAR(255),
	original_modifier_id binary(16),
	realm_id binary(16),
	transaction_id binary(16),
	disable_limit int,
	disabled bit NOT NULL,
	operation_type NVARCHAR(255) NOT NULL,
	period numeric(19,0) NOT NULL,
	warning_limit int,
	disable_template_id binary(16),
	system_id binary(16) NOT NULL,
	warning_template_id binary(16),
	CONSTRAINT sys_provisioning_break_config_pkey PRIMARY KEY (id)
);
CREATE INDEX idx_sys_prov_br_config_oper_type ON sys_provisioning_break_config (operation_type);
CREATE INDEX idx_sys_prov_br_config_system_id ON sys_provisioning_break_config (system_id);


CREATE TABLE sys_provisioning_break_recipient (
	id binary(16) NOT NULL,
	created datetime2(6) NOT NULL,
	creator NVARCHAR(255) NOT NULL,
	creator_id binary(16),
	modified datetime2(6),
	modifier NVARCHAR(255),
	modifier_id binary(16),
	original_creator NVARCHAR(255),
	original_creator_id binary(16),
	original_modifier NVARCHAR(255),
	original_modifier_id binary(16),
	realm_id binary(16),
	transaction_id binary(16),
	break_config_id binary(16) NOT NULL,
	identity_id binary(16),
	role_id binary(16),
	CONSTRAINT sys_provisioning_break_recipient_pkey PRIMARY KEY (id)
);
CREATE INDEX idx_sys_prov_br_break_id ON sys_provisioning_break_recipient (break_config_id);
CREATE INDEX idx_sys_prov_br_recip_identity_id ON sys_provisioning_break_recipient (identity_id);
CREATE INDEX idx_sys_prov_br_recip_role_id ON sys_provisioning_break_recipient (role_id);


CREATE TABLE sys_provisioning_operation (
	id binary(16) NOT NULL,
	created datetime2(6) NOT NULL,
	creator NVARCHAR(255) NOT NULL,
	creator_id binary(16),
	modified datetime2(6),
	modifier NVARCHAR(255),
	modifier_id binary(16),
	original_creator NVARCHAR(255),
	original_creator_id binary(16),
	original_modifier NVARCHAR(255),
	original_modifier_id binary(16),
	realm_id binary(16),
	transaction_id binary(16),
	current_attempt int,
	entity_identifier binary(255),
	entity_type NVARCHAR(255) NOT NULL,
	max_attempts int,
	operation_type NVARCHAR(255) NOT NULL,
	provisioning_context image NOT NULL,
	result_cause nvarchar(MAX),
	result_code NVARCHAR(255),
	result_model image,
	result_state NVARCHAR(45) NOT NULL,
	provisioning_batch_id binary(16),
	system_id binary(16) NOT NULL,
	system_entity_id binary(16) NOT NULL,
	CONSTRAINT sys_provisioning_operation_pkey PRIMARY KEY (id)
);
CREATE INDEX idx_sys_p_o_created ON sys_provisioning_operation (created);
CREATE INDEX idx_sys_p_o_entity_identifier ON sys_provisioning_operation (entity_identifier);
CREATE INDEX idx_sys_p_o_entity_type ON sys_provisioning_operation (entity_type);
CREATE INDEX idx_sys_p_o_operation_type ON sys_provisioning_operation (operation_type);
CREATE INDEX idx_sys_p_o_sys_entity ON sys_provisioning_operation (system_entity_id);
CREATE INDEX idx_sys_p_o_system ON sys_provisioning_operation (system_id);
CREATE INDEX idx_sys_pro_oper_batch_id ON sys_provisioning_operation (provisioning_batch_id);


CREATE TABLE sys_role_system (
	id binary(16) NOT NULL,
	created datetime2(6) NOT NULL,
	creator NVARCHAR(255) NOT NULL,
	creator_id binary(16),
	modified datetime2(6),
	modifier NVARCHAR(255),
	modifier_id binary(16),
	original_creator NVARCHAR(255),
	original_creator_id binary(16),
	original_modifier NVARCHAR(255),
	original_modifier_id binary(16),
	realm_id binary(16),
	transaction_id binary(16),
	forward_acm_enabled bit NOT NULL,
	role_id binary(16) NOT NULL,
	system_id binary(16) NOT NULL,
	system_mapping_id binary(16) NOT NULL,
	CONSTRAINT sys_role_system_pkey PRIMARY KEY (id)
);
CREATE INDEX idx_sys_role_system_role_id ON sys_role_system (role_id);
CREATE INDEX idx_sys_role_system_system_id ON sys_role_system (system_id);


CREATE TABLE sys_role_system_attribute (
	id binary(16) NOT NULL,
	created datetime2(6) NOT NULL,
	creator NVARCHAR(255) NOT NULL,
	creator_id binary(16),
	modified datetime2(6),
	modifier NVARCHAR(255),
	modifier_id binary(16),
	original_creator NVARCHAR(255),
	original_creator_id binary(16),
	original_modifier NVARCHAR(255),
	original_modifier_id binary(16),
	realm_id binary(16),
	transaction_id binary(16),
	confidential_attribute bit NOT NULL,
	disabled_default_attribute bit NOT NULL,
	entity_attribute bit NOT NULL,
	extended_attribute bit NOT NULL,
	idm_property_name NVARCHAR(255),
	name NVARCHAR(255),
	send_always bit NOT NULL,
	send_only_if_not_null bit NOT NULL,
	strategy_type NVARCHAR(255) NOT NULL,
	transform_script nvarchar(MAX),
	uid bit NOT NULL,
	role_system_id binary(16) NOT NULL,
	system_attr_mapping_id binary(16) NOT NULL,
	CONSTRAINT sys_role_system_attribute_pkey PRIMARY KEY (id)
);
CREATE UNIQUE INDEX ux_role_sys_atth_name ON sys_role_system_attribute (name,role_system_id);
CREATE UNIQUE INDEX ux_role_sys_atth_pname ON sys_role_system_attribute (idm_property_name,role_system_id);


CREATE TABLE sys_schema_attribute (
	id binary(16) NOT NULL,
	created datetime2(6) NOT NULL,
	creator NVARCHAR(255) NOT NULL,
	creator_id binary(16),
	modified datetime2(6),
	modifier NVARCHAR(255),
	modifier_id binary(16),
	original_creator NVARCHAR(255),
	original_creator_id binary(16),
	original_modifier NVARCHAR(255),
	original_modifier_id binary(16),
	realm_id binary(16),
	transaction_id binary(16),
	class_type NVARCHAR(255) NOT NULL,
	createable bit NOT NULL,
	multivalued bit NOT NULL,
	name NVARCHAR(255) NOT NULL,
	native_name NVARCHAR(255),
	readable bit NOT NULL,
	required bit NOT NULL,
	returned_by_default bit NOT NULL,
	updateable bit NOT NULL,
	object_class_id binary(16) NOT NULL,
	CONSTRAINT sys_schema_attribute_pkey PRIMARY KEY (id)
);
CREATE UNIQUE INDEX ux_schema_att_name_objclass ON sys_schema_attribute (name,object_class_id);


CREATE TABLE sys_schema_obj_class (
	id binary(16) NOT NULL,
	created datetime2(6) NOT NULL,
	creator NVARCHAR(255) NOT NULL,
	creator_id binary(16),
	modified datetime2(6),
	modifier NVARCHAR(255),
	modifier_id binary(16),
	original_creator NVARCHAR(255),
	original_creator_id binary(16),
	original_modifier NVARCHAR(255),
	original_modifier_id binary(16),
	realm_id binary(16),
	transaction_id binary(16),
	auxiliary bit NOT NULL,
	container bit NOT NULL,
	object_class_name NVARCHAR(255) NOT NULL,
	system_id binary(16) NOT NULL,
	CONSTRAINT sys_schema_obj_class_pkey PRIMARY KEY (id)
);
CREATE UNIQUE INDEX ux_schema_class_name_sys ON sys_schema_obj_class (object_class_name,system_id);


CREATE TABLE sys_sync_action_log (
	id binary(16) NOT NULL,
	created datetime2(6) NOT NULL,
	creator NVARCHAR(255) NOT NULL,
	creator_id binary(16),
	modified datetime2(6),
	modifier NVARCHAR(255),
	modifier_id binary(16),
	original_creator NVARCHAR(255),
	original_creator_id binary(16),
	original_modifier NVARCHAR(255),
	original_modifier_id binary(16),
	realm_id binary(16),
	transaction_id binary(16),
	operation_count int NOT NULL,
	[result] NVARCHAR(255) NOT NULL,
	sync_action NVARCHAR(255) NOT NULL,
	sync_log_id binary(16) NOT NULL,
	CONSTRAINT sys_sync_action_log_pkey PRIMARY KEY (id)
);


CREATE TABLE sys_sync_config (
	id binary(16) NOT NULL,
	created datetime2(6) NOT NULL,
	creator NVARCHAR(255) NOT NULL,
	creator_id binary(16),
	modified datetime2(6),
	modifier NVARCHAR(255),
	modifier_id binary(16),
	original_creator NVARCHAR(255),
	original_creator_id binary(16),
	original_modifier NVARCHAR(255),
	original_modifier_id binary(16),
	realm_id binary(16),
	transaction_id binary(16),
	custom_filter bit NOT NULL,
	custom_filter_script nvarchar(MAX),
	description NVARCHAR(2000),
	enabled bit NOT NULL,
	filter_operation NVARCHAR(255) NOT NULL,
	linked_action NVARCHAR(255) NOT NULL,
	linked_action_wf NVARCHAR(255),
	missing_account_action NVARCHAR(255) NOT NULL,
	missing_account_action_wf NVARCHAR(255),
	missing_entity_action NVARCHAR(255) NOT NULL,
	missing_entity_action_wf NVARCHAR(255),
	name NVARCHAR(255) NOT NULL,
	reconciliation bit NOT NULL,
	roots_filter_script nvarchar(MAX),
	token nvarchar(MAX),
	unlinked_action NVARCHAR(255) NOT NULL,
	unlinked_action_wf NVARCHAR(255),
	correlation_attribute_id binary(16) NOT NULL,
	filter_attribute_id binary(16),
	system_mapping_id binary(16) NOT NULL,
	token_attribute_id binary(16),
	CONSTRAINT sys_sync_config_pkey PRIMARY KEY (id)
);
CREATE INDEX idx_sys_s_config_correl ON sys_sync_config (correlation_attribute_id);
CREATE INDEX idx_sys_s_config_filter ON sys_sync_config (filter_attribute_id);
CREATE INDEX idx_sys_s_config_mapping ON sys_sync_config (system_mapping_id);
CREATE INDEX idx_sys_s_config_token ON sys_sync_config (token_attribute_id);
CREATE UNIQUE INDEX ux_sys_s_config_name ON sys_sync_config (name,system_mapping_id);


CREATE TABLE sys_sync_contract_config (
	start_auto_role_rec bit NOT NULL,
	start_hr_processes bit NOT NULL,
	id binary(16) NOT NULL,
	default_leader_id binary(16),
	default_tree_node_id binary(16),
	default_tree_type_id binary(16),
	CONSTRAINT sys_sync_contract_config_pkey PRIMARY KEY (id),
	CONSTRAINT fk_bc6q115e4e8r9dautiucnweyi FOREIGN KEY (id) REFERENCES sys_sync_config(id)
);
CREATE INDEX idx_sys_s_cont_conf_lead ON sys_sync_contract_config (default_leader_id);
CREATE INDEX idx_sys_s_cont_conf_node ON sys_sync_contract_config (default_tree_node_id);
CREATE INDEX idx_sys_s_cont_conf_tree ON sys_sync_contract_config (default_tree_type_id);


CREATE TABLE sys_sync_identity_config (
	create_default_contract bit NOT NULL,
	start_auto_role_rec bit NOT NULL,
	id binary(16) NOT NULL,
	default_role_id binary(16),
	CONSTRAINT sys_sync_identity_config_pkey PRIMARY KEY (id),
	CONSTRAINT fk_mf7itnp88831l71bl3tkgcqpo FOREIGN KEY (id) REFERENCES sys_sync_config(id)
);
CREATE INDEX idx_sys_s_iden_conf_role ON sys_sync_identity_config (default_role_id);


CREATE TABLE sys_sync_item_log (
	id binary(16) NOT NULL,
	created datetime2(6) NOT NULL,
	creator NVARCHAR(255) NOT NULL,
	creator_id binary(16),
	modified datetime2(6),
	modifier NVARCHAR(255),
	modifier_id binary(16),
	original_creator NVARCHAR(255),
	original_creator_id binary(16),
	original_modifier NVARCHAR(255),
	original_modifier_id binary(16),
	realm_id binary(16),
	transaction_id binary(16),
	display_name NVARCHAR(255),
	identification NVARCHAR(255) NOT NULL,
	log nvarchar(MAX),
	message NVARCHAR(2000),
	[type] NVARCHAR(255),
	sync_action_log_id binary(16) NOT NULL,
	CONSTRAINT sys_sync_item_log_pkey PRIMARY KEY (id)
);
CREATE INDEX idx_sys_s_i_l_action ON sys_sync_item_log (sync_action_log_id);


CREATE TABLE sys_sync_log (
	id binary(16) NOT NULL,
	created datetime2(6) NOT NULL,
	creator NVARCHAR(255) NOT NULL,
	creator_id binary(16),
	modified datetime2(6),
	modifier NVARCHAR(255),
	modifier_id binary(16),
	original_creator NVARCHAR(255),
	original_creator_id binary(16),
	original_modifier NVARCHAR(255),
	original_modifier_id binary(16),
	realm_id binary(16),
	transaction_id binary(16),
	contains_error bit NOT NULL,
	ended datetime2(6),
	log nvarchar(MAX),
	running bit NOT NULL,
	started datetime2(6),
	token nvarchar(MAX),
	synchronization_config_id binary(16) NOT NULL,
	CONSTRAINT sys_sync_log_pkey PRIMARY KEY (id)
);
CREATE INDEX idx_sys_s_l_config ON sys_sync_log (synchronization_config_id);


CREATE TABLE sys_system (
	id binary(16) NOT NULL,
	created datetime2(6) NOT NULL,
	creator NVARCHAR(255) NOT NULL,
	creator_id binary(16),
	modified datetime2(6),
	modifier NVARCHAR(255),
	modifier_id binary(16),
	original_creator NVARCHAR(255),
	original_creator_id binary(16),
	original_modifier NVARCHAR(255),
	original_modifier_id binary(16),
	realm_id binary(16),
	transaction_id binary(16),
	create_operation bit NOT NULL,
	delete_operation bit NOT NULL,
	update_operation bit NOT NULL,
	connector_bundle_name NVARCHAR(255),
	connector_bundle_version NVARCHAR(30),
	connector_name NVARCHAR(255),
	connector_framework NVARCHAR(255),
	host NVARCHAR(255),
	port int,
	timeout int,
	use_ssl bit NOT NULL,
	description NVARCHAR(2000),
	disabled bit NOT NULL,
	name NVARCHAR(255) NOT NULL,
	queue bit NOT NULL,
	readonly bit NOT NULL,
	remote bit NOT NULL,
	version numeric(19,0),
	virtual bit NOT NULL,
	password_pol_gen_id binary(16),
	password_pol_val_id binary(16),
	CONSTRAINT sys_system_pkey PRIMARY KEY (id)
);
CREATE INDEX idx_idm_password_pol_gen ON sys_system (password_pol_val_id);
CREATE INDEX idx_idm_password_pol_val ON sys_system (password_pol_gen_id);
CREATE UNIQUE INDEX ux_system_name ON sys_system (name);


CREATE TABLE sys_system_attribute_mapping (
	id binary(16) NOT NULL,
	created datetime2(6) NOT NULL,
	creator NVARCHAR(255) NOT NULL,
	creator_id binary(16),
	modified datetime2(6),
	modifier NVARCHAR(255),
	modifier_id binary(16),
	original_creator NVARCHAR(255),
	original_creator_id binary(16),
	original_modifier NVARCHAR(255),
	original_modifier_id binary(16),
	realm_id binary(16),
	transaction_id binary(16),
	authentication_attribute bit NOT NULL,
	attribute_cached bit NOT NULL,
	confidential_attribute bit NOT NULL,
	disabled_attribute bit NOT NULL,
	entity_attribute bit NOT NULL,
	extended_attribute bit NOT NULL,
	idm_property_name NVARCHAR(255),
	name NVARCHAR(255) NOT NULL,
	send_always bit NOT NULL,
	send_on_password_change bit NOT NULL,
	send_only_if_not_null bit NOT NULL,
	strategy_type NVARCHAR(255) NOT NULL,
	transform_from_res_script nvarchar(MAX),
	transform_to_res_script nvarchar(MAX),
	uid bit NOT NULL,
	schema_attribute_id binary(16) NOT NULL,
	system_mapping_id binary(16) NOT NULL,
	CONSTRAINT sys_system_attribute_mapping_pkey PRIMARY KEY (id)
);
CREATE UNIQUE INDEX ux_sys_attr_m_name_enth ON sys_system_attribute_mapping (name,system_mapping_id);


CREATE TABLE sys_system_entity (
	id binary(16) NOT NULL,
	created datetime2(6) NOT NULL,
	creator NVARCHAR(255) NOT NULL,
	creator_id binary(16),
	modified datetime2(6),
	modifier NVARCHAR(255),
	modifier_id binary(16),
	original_creator NVARCHAR(255),
	original_creator_id binary(16),
	original_modifier NVARCHAR(255),
	original_modifier_id binary(16),
	realm_id binary(16),
	transaction_id binary(16),
	entity_type NVARCHAR(255) NOT NULL,
	uid NVARCHAR(1000) NOT NULL,
	wish bit NOT NULL,
	system_id binary(16) NOT NULL,
	CONSTRAINT sys_system_entity_pkey PRIMARY KEY (id)
);
CREATE INDEX idx_sys_system_entity_system ON sys_system_entity (system_id);
CREATE INDEX idx_sys_system_entity_type ON sys_system_entity (entity_type);
CREATE INDEX idx_sys_system_entity_uid ON sys_system_entity (uid);
CREATE UNIQUE INDEX ux_system_entity_type_uid ON sys_system_entity (entity_type,uid,system_id);


CREATE TABLE sys_system_form_value (
	id binary(16) NOT NULL,
	created datetime2(6) NOT NULL,
	creator NVARCHAR(255) NOT NULL,
	creator_id binary(16),
	modified datetime2(6),
	modifier NVARCHAR(255),
	modifier_id binary(16),
	original_creator NVARCHAR(255),
	original_creator_id binary(16),
	original_modifier NVARCHAR(255),
	original_modifier_id binary(16),
	realm_id binary(16),
	transaction_id binary(16),
	boolean_value bit,
	byte_value varbinary(255),
	confidential bit NOT NULL,
	date_value datetime2(6),
	double_value numeric(38,4),
	long_value numeric(19,0),
	persistent_type NVARCHAR(45) NOT NULL,
	seq smallint,
	short_text_value NVARCHAR(2000),
	string_value nvarchar(MAX),
	uuid_value binary(16),
	attribute_id binary(16) NOT NULL,
	owner_id binary(16) NOT NULL,
	CONSTRAINT sys_system_form_value_pkey PRIMARY KEY (id)
);
CREATE INDEX idx_sys_sys_form_a ON sys_system_form_value (owner_id);
CREATE INDEX idx_sys_sys_form_a_def ON sys_system_form_value (attribute_id);
CREATE INDEX idx_sys_sys_form_uuid ON sys_system_form_value (uuid_value);


CREATE TABLE sys_system_mapping (
	id binary(16) NOT NULL,
	created datetime2(6) NOT NULL,
	creator NVARCHAR(255) NOT NULL,
	creator_id binary(16),
	modified datetime2(6),
	modifier NVARCHAR(255),
	modifier_id binary(16),
	original_creator NVARCHAR(255),
	original_creator_id binary(16),
	original_modifier NVARCHAR(255),
	original_modifier_id binary(16),
	realm_id binary(16),
	transaction_id binary(16),
	can_be_acc_created_script nvarchar(MAX),
	entity_type NVARCHAR(255) NOT NULL,
	name NVARCHAR(255) NOT NULL,
	operation_type NVARCHAR(255) NOT NULL,
	protection_enabled bit,
	protection_interval int,
	object_class_id binary(16) NOT NULL,
	tree_type_id binary(16),
	CONSTRAINT sys_system_mapping_pkey PRIMARY KEY (id),
	CONSTRAINT sys_system_mapping_protection_interval_check CHECK ((protection_interval >= 0))
);
CREATE INDEX idx_sys_s_mapping_e_type ON sys_system_mapping (entity_type);
CREATE INDEX idx_sys_s_mapping_o_c_id ON sys_system_mapping (object_class_id);
CREATE INDEX idx_sys_s_mapping_o_type ON sys_system_mapping (operation_type);
CREATE UNIQUE INDEX ux_sys_s_mapping_name ON sys_system_mapping (name,object_class_id);

-- AUDIT TABLES

CREATE TABLE acc_account_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	revtype smallint,
	created datetime2(6),
	created_m bit,
	creator varchar(255),
	creator_m bit,
	creator_id binary(16),
	creator_id_m bit,
	modifier varchar(255),
	modifier_m bit,
	modifier_id binary(16),
	modifier_id_m bit,
	original_creator varchar(255),
	original_creator_m bit,
	original_creator_id binary(16),
	original_creator_id_m bit,
	original_modifier varchar(255),
	original_modifier_m bit,
	original_modifier_id binary(16),
	original_modifier_id_m bit,
	realm_id binary(16),
	realm_id_m bit,
	transaction_id binary(16),
	transaction_id_m bit,
	account_type varchar(255),
	account_type_m bit,
	end_of_protection datetime2(6),
	end_of_protection_m bit,
	in_protection bit,
	in_protection_m bit,
	uid varchar(1000),
	uid_m bit,
	system_id binary(16),
	system_m bit,
	system_entity_id binary(16),
	system_entity_m bit,
	CONSTRAINT acc_account_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_ocfc37k7urgtggoneqm048lyy FOREIGN KEY (rev) REFERENCES idm_audit(id)
);


CREATE TABLE acc_contract_account_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	revtype smallint,
	created datetime2(6),
	created_m bit,
	creator varchar(255),
	creator_m bit,
	creator_id binary(16),
	creator_id_m bit,
	modifier varchar(255),
	modifier_m bit,
	modifier_id binary(16),
	modifier_id_m bit,
	original_creator varchar(255),
	original_creator_m bit,
	original_creator_id binary(16),
	original_creator_id_m bit,
	original_modifier varchar(255),
	original_modifier_m bit,
	original_modifier_id binary(16),
	original_modifier_id_m bit,
	realm_id binary(16),
	realm_id_m bit,
	transaction_id binary(16),
	transaction_id_m bit,
	ownership bit,
	ownership_m bit,
	account_id binary(16),
	account_m bit,
	contract_id binary(16),
	contract_m bit,
	CONSTRAINT acc_contract_account_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_yrumm9gw9dr2xbrbll5m3bd3 FOREIGN KEY (rev) REFERENCES idm_audit(id)
);


CREATE TABLE acc_contract_slice_account_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	revtype smallint,
	created datetime2(6),
	created_m bit,
	creator varchar(255),
	creator_m bit,
	creator_id binary(16),
	creator_id_m bit,
	modifier varchar(255),
	modifier_m bit,
	modifier_id binary(16),
	modifier_id_m bit,
	original_creator varchar(255),
	original_creator_m bit,
	original_creator_id binary(16),
	original_creator_id_m bit,
	original_modifier varchar(255),
	original_modifier_m bit,
	original_modifier_id binary(16),
	original_modifier_id_m bit,
	realm_id binary(16),
	realm_id_m bit,
	transaction_id binary(16),
	transaction_id_m bit,
	ownership bit,
	ownership_m bit,
	account_id binary(16),
	account_m bit,
	contract_slice_id binary(16),
	slice_m bit,
	CONSTRAINT acc_contract_slice_account_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_gfrmpwlq597v1c51v7huftfqj FOREIGN KEY (rev) REFERENCES idm_audit(id)
);


CREATE TABLE acc_identity_account_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	revtype smallint,
	created datetime2(6),
	created_m bit,
	creator varchar(255),
	creator_m bit,
	creator_id binary(16),
	creator_id_m bit,
	modifier varchar(255),
	modifier_m bit,
	modifier_id binary(16),
	modifier_id_m bit,
	original_creator varchar(255),
	original_creator_m bit,
	original_creator_id binary(16),
	original_creator_id_m bit,
	original_modifier varchar(255),
	original_modifier_m bit,
	original_modifier_id binary(16),
	original_modifier_id_m bit,
	realm_id binary(16),
	realm_id_m bit,
	transaction_id binary(16),
	transaction_id_m bit,
	ownership bit,
	ownership_m bit,
	account_id binary(16),
	account_m bit,
	identity_id binary(16),
	identity_m bit,
	identity_role_id binary(16),
	identity_role_m bit,
	role_system_id binary(16),
	role_system_m bit,
	CONSTRAINT acc_identity_account_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_tc0lfendp9bg0vgag7pk0ib3d FOREIGN KEY (rev) REFERENCES idm_audit(id)
);


CREATE TABLE acc_role_account_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	revtype smallint,
	created datetime2(6),
	created_m bit,
	creator varchar(255),
	creator_m bit,
	creator_id binary(16),
	creator_id_m bit,
	modifier varchar(255),
	modifier_m bit,
	modifier_id binary(16),
	modifier_id_m bit,
	original_creator varchar(255),
	original_creator_m bit,
	original_creator_id binary(16),
	original_creator_id_m bit,
	original_modifier varchar(255),
	original_modifier_m bit,
	original_modifier_id binary(16),
	original_modifier_id_m bit,
	realm_id binary(16),
	realm_id_m bit,
	transaction_id binary(16),
	transaction_id_m bit,
	ownership bit,
	ownership_m bit,
	account_id binary(16),
	account_m bit,
	role_id binary(16),
	role_m bit,
	CONSTRAINT acc_role_account_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_dcuth9gweqc4f9gk8c8stgr7 FOREIGN KEY (rev) REFERENCES idm_audit(id)
);


CREATE TABLE acc_role_catalogue_account_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	revtype smallint,
	created datetime2(6),
	created_m bit,
	creator varchar(255),
	creator_m bit,
	creator_id binary(16),
	creator_id_m bit,
	modifier varchar(255),
	modifier_m bit,
	modifier_id binary(16),
	modifier_id_m bit,
	original_creator varchar(255),
	original_creator_m bit,
	original_creator_id binary(16),
	original_creator_id_m bit,
	original_modifier varchar(255),
	original_modifier_m bit,
	original_modifier_id binary(16),
	original_modifier_id_m bit,
	realm_id binary(16),
	realm_id_m bit,
	transaction_id binary(16),
	transaction_id_m bit,
	ownership bit,
	ownership_m bit,
	account_id binary(16),
	account_m bit,
	role_catalogue_id binary(16),
	role_catalogue_m bit,
	role_system_id binary(16),
	role_system_m bit,
	CONSTRAINT acc_role_catalogue_account_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_civ47mx4nlpsvlro1r7nw7ycr FOREIGN KEY (rev) REFERENCES idm_audit(id)
);


CREATE TABLE acc_tree_account_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	revtype smallint,
	created datetime2(6),
	created_m bit,
	creator varchar(255),
	creator_m bit,
	creator_id binary(16),
	creator_id_m bit,
	modifier varchar(255),
	modifier_m bit,
	modifier_id binary(16),
	modifier_id_m bit,
	original_creator varchar(255),
	original_creator_m bit,
	original_creator_id binary(16),
	original_creator_id_m bit,
	original_modifier varchar(255),
	original_modifier_m bit,
	original_modifier_id binary(16),
	original_modifier_id_m bit,
	realm_id binary(16),
	realm_id_m bit,
	transaction_id binary(16),
	transaction_id_m bit,
	ownership bit,
	ownership_m bit,
	account_id binary(16),
	account_m bit,
	role_system_id binary(16),
	role_system_m bit,
	tree_node_id binary(16),
	tree_node_m bit,
	CONSTRAINT acc_tree_account_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_5c3jg826m2x2fq1q677uwk02u FOREIGN KEY (rev) REFERENCES idm_audit(id)
);


CREATE TABLE sys_provisioning_break_config_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	revtype smallint,
	created datetime2(6),
	created_m bit,
	creator varchar(255),
	creator_m bit,
	creator_id binary(16),
	creator_id_m bit,
	modifier varchar(255),
	modifier_m bit,
	modifier_id binary(16),
	modifier_id_m bit,
	original_creator varchar(255),
	original_creator_m bit,
	original_creator_id binary(16),
	original_creator_id_m bit,
	original_modifier varchar(255),
	original_modifier_m bit,
	original_modifier_id binary(16),
	original_modifier_id_m bit,
	realm_id binary(16),
	realm_id_m bit,
	transaction_id binary(16),
	transaction_id_m bit,
	disable_limit int,
	disable_limit_m bit,
	disabled bit,
	disabled_m bit,
	operation_type varchar(255),
	operation_type_m bit,
	period numeric(19,0),
	period_m bit,
	warning_limit int,
	warning_limit_m bit,
	disable_template_id binary(16),
	disable_template_m bit,
	system_id binary(16),
	system_m bit,
	warning_template_id binary(16),
	warning_template_m bit,
	CONSTRAINT sys_provisioning_break_config_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_m6smdd15x3drkpslil9jadh62 FOREIGN KEY (rev) REFERENCES idm_audit(id)
);


CREATE TABLE sys_provisioning_break_recipient_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	revtype smallint,
	created datetime2(6),
	created_m bit,
	creator varchar(255),
	creator_m bit,
	creator_id binary(16),
	creator_id_m bit,
	modifier varchar(255),
	modifier_m bit,
	modifier_id binary(16),
	modifier_id_m bit,
	original_creator varchar(255),
	original_creator_m bit,
	original_creator_id binary(16),
	original_creator_id_m bit,
	original_modifier varchar(255),
	original_modifier_m bit,
	original_modifier_id binary(16),
	original_modifier_id_m bit,
	realm_id binary(16),
	realm_id_m bit,
	transaction_id binary(16),
	transaction_id_m bit,
	break_config_id binary(16),
	break_config_m bit,
	identity_id binary(16),
	identity_m bit,
	role_id binary(16),
	role_m bit,
	CONSTRAINT sys_provisioning_break_recipient_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_cyr1rkx363m9k74llltevx3rp FOREIGN KEY (rev) REFERENCES idm_audit(id)
);


CREATE TABLE sys_role_system_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	revtype smallint,
	created datetime2(6),
	created_m bit,
	creator varchar(255),
	creator_m bit,
	creator_id binary(16),
	creator_id_m bit,
	modifier varchar(255),
	modifier_m bit,
	modifier_id binary(16),
	modifier_id_m bit,
	original_creator varchar(255),
	original_creator_m bit,
	original_creator_id binary(16),
	original_creator_id_m bit,
	original_modifier varchar(255),
	original_modifier_m bit,
	original_modifier_id binary(16),
	original_modifier_id_m bit,
	realm_id binary(16),
	realm_id_m bit,
	transaction_id binary(16),
	transaction_id_m bit,
	forward_acm_enabled bit,
	forward_account_managemen_m bit,
	role_id binary(16),
	role_m bit,
	system_id binary(16),
	system_m bit,
	system_mapping_id binary(16),
	system_mapping_m bit,
	CONSTRAINT sys_role_system_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_n0hfyes79r41p01upa8bkbmu6 FOREIGN KEY (rev) REFERENCES idm_audit(id)
);


CREATE TABLE sys_role_system_attribute_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	revtype smallint,
	created datetime2(6),
	created_m bit,
	creator varchar(255),
	creator_m bit,
	creator_id binary(16),
	creator_id_m bit,
	modifier varchar(255),
	modifier_m bit,
	modifier_id binary(16),
	modifier_id_m bit,
	original_creator varchar(255),
	original_creator_m bit,
	original_creator_id binary(16),
	original_creator_id_m bit,
	original_modifier varchar(255),
	original_modifier_m bit,
	original_modifier_id binary(16),
	original_modifier_id_m bit,
	realm_id binary(16),
	realm_id_m bit,
	transaction_id binary(16),
	transaction_id_m bit,
	confidential_attribute bit,
	confidential_attribute_m bit,
	disabled_default_attribute bit,
	disabled_default_attribute_m bit,
	entity_attribute bit,
	entity_attribute_m bit,
	extended_attribute bit,
	extended_attribute_m bit,
	idm_property_name varchar(255),
	idm_property_name_m bit,
	name varchar(255),
	name_m bit,
	send_always bit,
	send_always_m bit,
	send_only_if_not_null bit,
	send_only_if_not_null_m bit,
	strategy_type varchar(255),
	strategy_type_m bit,
	transform_script nvarchar(MAX),
	transform_script_m bit,
	uid bit,
	uid_m bit,
	role_system_id binary(16),
	role_system_m bit,
	system_attr_mapping_id binary(16),
	system_attribute_mapping_m bit,
	CONSTRAINT sys_role_system_attribute_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_mb7uvabbp62wpmroqbn80nh34 FOREIGN KEY (rev) REFERENCES idm_audit(id)
);


CREATE TABLE sys_schema_attribute_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	revtype smallint,
	created datetime2(6),
	created_m bit,
	creator varchar(255),
	creator_m bit,
	creator_id binary(16),
	creator_id_m bit,
	modifier varchar(255),
	modifier_m bit,
	modifier_id binary(16),
	modifier_id_m bit,
	original_creator varchar(255),
	original_creator_m bit,
	original_creator_id binary(16),
	original_creator_id_m bit,
	original_modifier varchar(255),
	original_modifier_m bit,
	original_modifier_id binary(16),
	original_modifier_id_m bit,
	realm_id binary(16),
	realm_id_m bit,
	transaction_id binary(16),
	transaction_id_m bit,
	class_type varchar(255),
	class_type_m bit,
	createable bit,
	createable_m bit,
	multivalued bit,
	multivalued_m bit,
	name varchar(255),
	name_m bit,
	native_name varchar(255),
	native_name_m bit,
	readable bit,
	readable_m bit,
	required bit,
	required_m bit,
	returned_by_default bit,
	returned_by_default_m bit,
	updateable bit,
	updateable_m bit,
	object_class_id binary(16),
	object_class_m bit,
	CONSTRAINT sys_schema_attribute_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_h227a5dpgs004bu0mf3bxdjdn FOREIGN KEY (rev) REFERENCES idm_audit(id)
);


CREATE TABLE sys_schema_obj_class_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	revtype smallint,
	created datetime2(6),
	created_m bit,
	creator varchar(255),
	creator_m bit,
	creator_id binary(16),
	creator_id_m bit,
	modifier varchar(255),
	modifier_m bit,
	modifier_id binary(16),
	modifier_id_m bit,
	original_creator varchar(255),
	original_creator_m bit,
	original_creator_id binary(16),
	original_creator_id_m bit,
	original_modifier varchar(255),
	original_modifier_m bit,
	original_modifier_id binary(16),
	original_modifier_id_m bit,
	realm_id binary(16),
	realm_id_m bit,
	transaction_id binary(16),
	transaction_id_m bit,
	auxiliary bit,
	auxiliary_m bit,
	container bit,
	container_m bit,
	object_class_name varchar(255),
	object_class_name_m bit,
	system_id binary(16),
	system_m bit,
	CONSTRAINT sys_schema_obj_class_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_jhghwftbl8995o2e1m18dswbq FOREIGN KEY (rev) REFERENCES idm_audit(id)
);


CREATE TABLE sys_sync_config_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	revtype smallint,
	created datetime2(6),
	created_m bit,
	creator varchar(255),
	creator_m bit,
	creator_id binary(16),
	creator_id_m bit,
	modifier varchar(255),
	modifier_m bit,
	modifier_id binary(16),
	modifier_id_m bit,
	original_creator varchar(255),
	original_creator_m bit,
	original_creator_id binary(16),
	original_creator_id_m bit,
	original_modifier varchar(255),
	original_modifier_m bit,
	original_modifier_id binary(16),
	original_modifier_id_m bit,
	realm_id binary(16),
	realm_id_m bit,
	transaction_id binary(16),
	transaction_id_m bit,
	custom_filter bit,
	custom_filter_m bit,
	custom_filter_script nvarchar(MAX),
	custom_filter_script_m bit,
	description varchar(2000),
	description_m bit,
	enabled bit,
	enabled_m bit,
	filter_operation varchar(255),
	filter_operation_m bit,
	linked_action varchar(255),
	linked_action_m bit,
	linked_action_wf varchar(255),
	linked_action_wf_key_m bit,
	missing_account_action varchar(255),
	missing_account_action_m bit,
	missing_account_action_wf varchar(255),
	missing_account_action_wf_key_m bit,
	missing_entity_action varchar(255),
	missing_entity_action_m bit,
	missing_entity_action_wf varchar(255),
	missing_entity_action_wf_key_m bit,
	name varchar(255),
	name_m bit,
	reconciliation bit,
	reconciliation_m bit,
	roots_filter_script nvarchar(MAX),
	roots_filter_script_m bit,
	unlinked_action varchar(255),
	unlinked_action_m bit,
	unlinked_action_wf varchar(255),
	unlinked_action_wf_key_m bit,
	correlation_attribute_id binary(16),
	correlation_attribute_m bit,
	filter_attribute_id binary(16),
	filter_attribute_m bit,
	system_mapping_id binary(16),
	system_mapping_m bit,
	token_attribute_id binary(16),
	token_attribute_m bit,
	CONSTRAINT sys_sync_config_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_qu1u38lrk8vnhkqd5b4ehf2mp FOREIGN KEY (rev) REFERENCES idm_audit(id)
);


CREATE TABLE sys_sync_contract_config_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	start_auto_role_rec bit,
	start_auto_role_rec_m bit,
	start_hr_processes bit,
	start_of_hr_processes_m bit,
	default_leader_id binary(16),
	default_leader_m bit,
	default_tree_node_id binary(16),
	default_tree_node_m bit,
	default_tree_type_id binary(16),
	default_tree_type_m bit,
	CONSTRAINT sys_sync_contract_config_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_ak23lsavvslhvywtevxaq4m2u FOREIGN KEY (id,rev) REFERENCES sys_sync_config_a(id,rev)
);


CREATE TABLE sys_sync_identity_config_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	create_default_contract bit,
	create_default_contract_m bit,
	start_auto_role_rec bit,
	start_auto_role_rec_m bit,
	default_role_id binary(16),
	default_role_m bit,
	CONSTRAINT sys_sync_identity_config_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_jc3sotalvrdqvt6xqh8msx9t3 FOREIGN KEY (id,rev) REFERENCES sys_sync_config_a(id,rev)
);


CREATE TABLE sys_system_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	revtype smallint,
	created datetime2(6),
	created_m bit,
	creator varchar(255),
	creator_m bit,
	creator_id binary(16),
	creator_id_m bit,
	modifier varchar(255),
	modifier_m bit,
	modifier_id binary(16),
	modifier_id_m bit,
	original_creator varchar(255),
	original_creator_m bit,
	original_creator_id binary(16),
	original_creator_id_m bit,
	original_modifier varchar(255),
	original_modifier_m bit,
	original_modifier_id binary(16),
	original_modifier_id_m bit,
	realm_id binary(16),
	realm_id_m bit,
	transaction_id binary(16),
	transaction_id_m bit,
	create_operation bit,
	delete_operation bit,
	update_operation bit,
	blocked_operation_m bit,
	connector_bundle_name varchar(255),
	connector_bundle_version varchar(30),
	connector_name varchar(255),
	connector_framework varchar(255),
	connector_key_m bit,
	host varchar(255),
	port int,
	timeout int,
	use_ssl bit,
	connector_server_m bit,
	description varchar(2000),
	description_m bit,
	disabled bit,
	disabled_m bit,
	name varchar(255),
	name_m bit,
	queue bit,
	queue_m bit,
	readonly bit,
	readonly_m bit,
	remote bit,
	remote_m bit,
	virtual bit,
	virtual_m bit,
	password_pol_gen_id binary(16),
	password_policy_generate_m bit,
	password_pol_val_id binary(16),
	password_policy_validate_m bit,
	CONSTRAINT sys_system_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_khsnjdk8wea24bo32saq8cc14 FOREIGN KEY (rev) REFERENCES idm_audit(id)
);


CREATE TABLE sys_system_attribute_mapping_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	revtype smallint,
	created datetime2(6),
	created_m bit,
	creator varchar(255),
	creator_m bit,
	creator_id binary(16),
	creator_id_m bit,
	modifier varchar(255),
	modifier_m bit,
	modifier_id binary(16),
	modifier_id_m bit,
	original_creator varchar(255),
	original_creator_m bit,
	original_creator_id binary(16),
	original_creator_id_m bit,
	original_modifier varchar(255),
	original_modifier_m bit,
	original_modifier_id binary(16),
	original_modifier_id_m bit,
	realm_id binary(16),
	realm_id_m bit,
	transaction_id binary(16),
	transaction_id_m bit,
	authentication_attribute bit,
	authentication_attribute_m bit,
	attribute_cached bit,
	cached_m bit,
	confidential_attribute bit,
	confidential_attribute_m bit,
	disabled_attribute bit,
	disabled_attribute_m bit,
	entity_attribute bit,
	entity_attribute_m bit,
	extended_attribute bit,
	extended_attribute_m bit,
	idm_property_name varchar(255),
	idm_property_name_m bit,
	name varchar(255),
	name_m bit,
	send_always bit,
	send_always_m bit,
	send_on_password_change bit,
	send_on_password_change_m bit,
	send_only_if_not_null bit,
	send_only_if_not_null_m bit,
	strategy_type varchar(255),
	strategy_type_m bit,
	transform_from_res_script nvarchar(MAX),
	transform_from_resource_script_m bit,
	transform_to_res_script nvarchar(MAX),
	transform_to_resource_script_m bit,
	uid bit,
	uid_m bit,
	schema_attribute_id binary(16),
	schema_attribute_m bit,
	system_mapping_id binary(16),
	system_mapping_m bit,
	CONSTRAINT sys_system_attribute_mapping_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_ncp3og5psyxsw3kr3kyqc49mm FOREIGN KEY (rev) REFERENCES idm_audit(id)
);


CREATE TABLE sys_system_form_value_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	revtype smallint,
	created datetime2(6),
	created_m bit,
	creator varchar(255),
	creator_m bit,
	creator_id binary(16),
	creator_id_m bit,
	modifier varchar(255),
	modifier_m bit,
	modifier_id binary(16),
	modifier_id_m bit,
	original_creator varchar(255),
	original_creator_m bit,
	original_creator_id binary(16),
	original_creator_id_m bit,
	original_modifier varchar(255),
	original_modifier_m bit,
	original_modifier_id binary(16),
	original_modifier_id_m bit,
	realm_id binary(16),
	realm_id_m bit,
	transaction_id binary(16),
	transaction_id_m bit,
	boolean_value bit,
	boolean_value_m bit,
	byte_value varbinary(255),
	byte_value_m bit,
	confidential bit,
	confidential_m bit,
	date_value datetime2(6),
	date_value_m bit,
	double_value numeric(38,4),
	double_value_m bit,
	long_value numeric(19,0),
	long_value_m bit,
	persistent_type varchar(45),
	persistent_type_m bit,
	seq smallint,
	seq_m bit,
	short_text_value varchar(2000),
	short_text_value_m bit,
	string_value nvarchar(MAX),
	string_value_m bit,
	uuid_value binary(16),
	uuid_value_m bit,
	attribute_id binary(16),
	form_attribute_m bit,
	owner_id binary(16),
	owner_m bit,
	CONSTRAINT sys_system_form_value_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_awctj8y0nn7xyocg95xqpsq62 FOREIGN KEY (rev) REFERENCES idm_audit(id)
);


CREATE TABLE sys_system_mapping_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	revtype smallint,
	created datetime2(6),
	created_m bit,
	creator varchar(255),
	creator_m bit,
	creator_id binary(16),
	creator_id_m bit,
	modifier varchar(255),
	modifier_m bit,
	modifier_id binary(16),
	modifier_id_m bit,
	original_creator varchar(255),
	original_creator_m bit,
	original_creator_id binary(16),
	original_creator_id_m bit,
	original_modifier varchar(255),
	original_modifier_m bit,
	original_modifier_id binary(16),
	original_modifier_id_m bit,
	realm_id binary(16),
	realm_id_m bit,
	transaction_id binary(16),
	transaction_id_m bit,
	can_be_acc_created_script nvarchar(MAX),
	can_be_account_created_script_m bit,
	entity_type varchar(255),
	entity_type_m bit,
	name varchar(255),
	name_m bit,
	operation_type varchar(255),
	operation_type_m bit,
	protection_enabled bit,
	protection_enabled_m bit,
	protection_interval int,
	protection_interval_m bit,
	object_class_id binary(16),
	object_class_m bit,
	tree_type_id binary(16),
	tree_type_m bit,
	CONSTRAINT sys_system_mapping_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_8ruymojmoa1l1xv4x1n5tbatv FOREIGN KEY (rev) REFERENCES idm_audit(id)
);
