--
-- CzechIdM 9.0 Flyway script
-- BCV solutions s.r.o.
--
-- This SQL script creates the required audit tables by CzechIdM (module acc)

CREATE TABLE acc_account_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	revtype smallint,
	created datetime,
	created_m bit,
	creator varchar(255),
	creator_m bit,
	creator_id binary(16),
	creator_id_m bit,
	modifier varchar(255),
	modifier_m bit,
	modifier_id binary(16),
	modifier_id_m bit,
	original_creator varchar(255),
	original_creator_m bit,
	original_creator_id binary(16),
	original_creator_id_m bit,
	original_modifier varchar(255),
	original_modifier_m bit,
	original_modifier_id binary(16),
	original_modifier_id_m bit,
	realm_id binary(16),
	realm_id_m bit,
	transaction_id binary(16),
	transaction_id_m bit,
	account_type varchar(255),
	account_type_m bit,
	end_of_protection datetime,
	end_of_protection_m bit,
	in_protection bit,
	in_protection_m bit,
	uid varchar(1000),
	uid_m bit,
	system_id binary(16),
	system_m bit,
	system_entity_id binary(16),
	system_entity_m bit,
	CONSTRAINT acc_account_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_ocfc37k7urgtggoneqm048lyy FOREIGN KEY (rev) REFERENCES idm_audit(id)
);


CREATE TABLE acc_contract_account_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	revtype smallint,
	created datetime,
	created_m bit,
	creator varchar(255),
	creator_m bit,
	creator_id binary(16),
	creator_id_m bit,
	modifier varchar(255),
	modifier_m bit,
	modifier_id binary(16),
	modifier_id_m bit,
	original_creator varchar(255),
	original_creator_m bit,
	original_creator_id binary(16),
	original_creator_id_m bit,
	original_modifier varchar(255),
	original_modifier_m bit,
	original_modifier_id binary(16),
	original_modifier_id_m bit,
	realm_id binary(16),
	realm_id_m bit,
	transaction_id binary(16),
	transaction_id_m bit,
	ownership bit,
	ownership_m bit,
	account_id binary(16),
	account_m bit,
	contract_id binary(16),
	contract_m bit,
	CONSTRAINT acc_contract_account_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_yrumm9gw9dr2xbrbll5m3bd3 FOREIGN KEY (rev) REFERENCES idm_audit(id)
);


CREATE TABLE acc_contract_slice_account_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	revtype smallint,
	created datetime,
	created_m bit,
	creator varchar(255),
	creator_m bit,
	creator_id binary(16),
	creator_id_m bit,
	modifier varchar(255),
	modifier_m bit,
	modifier_id binary(16),
	modifier_id_m bit,
	original_creator varchar(255),
	original_creator_m bit,
	original_creator_id binary(16),
	original_creator_id_m bit,
	original_modifier varchar(255),
	original_modifier_m bit,
	original_modifier_id binary(16),
	original_modifier_id_m bit,
	realm_id binary(16),
	realm_id_m bit,
	transaction_id binary(16),
	transaction_id_m bit,
	ownership bit,
	ownership_m bit,
	account_id binary(16),
	account_m bit,
	contract_slice_id binary(16),
	slice_m bit,
	CONSTRAINT acc_contract_slice_account_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_gfrmpwlq597v1c51v7huftfqj FOREIGN KEY (rev) REFERENCES idm_audit(id)
);


CREATE TABLE acc_identity_account_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	revtype smallint,
	created datetime,
	created_m bit,
	creator varchar(255),
	creator_m bit,
	creator_id binary(16),
	creator_id_m bit,
	modifier varchar(255),
	modifier_m bit,
	modifier_id binary(16),
	modifier_id_m bit,
	original_creator varchar(255),
	original_creator_m bit,
	original_creator_id binary(16),
	original_creator_id_m bit,
	original_modifier varchar(255),
	original_modifier_m bit,
	original_modifier_id binary(16),
	original_modifier_id_m bit,
	realm_id binary(16),
	realm_id_m bit,
	transaction_id binary(16),
	transaction_id_m bit,
	ownership bit,
	ownership_m bit,
	account_id binary(16),
	account_m bit,
	identity_id binary(16),
	identity_m bit,
	identity_role_id binary(16),
	identity_role_m bit,
	role_system_id binary(16),
	role_system_m bit,
	CONSTRAINT acc_identity_account_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_tc0lfendp9bg0vgag7pk0ib3d FOREIGN KEY (rev) REFERENCES idm_audit(id)
);


CREATE TABLE acc_role_account_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	revtype smallint,
	created datetime,
	created_m bit,
	creator varchar(255),
	creator_m bit,
	creator_id binary(16),
	creator_id_m bit,
	modifier varchar(255),
	modifier_m bit,
	modifier_id binary(16),
	modifier_id_m bit,
	original_creator varchar(255),
	original_creator_m bit,
	original_creator_id binary(16),
	original_creator_id_m bit,
	original_modifier varchar(255),
	original_modifier_m bit,
	original_modifier_id binary(16),
	original_modifier_id_m bit,
	realm_id binary(16),
	realm_id_m bit,
	transaction_id binary(16),
	transaction_id_m bit,
	ownership bit,
	ownership_m bit,
	account_id binary(16),
	account_m bit,
	role_id binary(16),
	role_m bit,
	CONSTRAINT acc_role_account_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_dcuth9gweqc4f9gk8c8stgr7 FOREIGN KEY (rev) REFERENCES idm_audit(id)
);


CREATE TABLE acc_role_catalogue_account_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	revtype smallint,
	created datetime,
	created_m bit,
	creator varchar(255),
	creator_m bit,
	creator_id binary(16),
	creator_id_m bit,
	modifier varchar(255),
	modifier_m bit,
	modifier_id binary(16),
	modifier_id_m bit,
	original_creator varchar(255),
	original_creator_m bit,
	original_creator_id binary(16),
	original_creator_id_m bit,
	original_modifier varchar(255),
	original_modifier_m bit,
	original_modifier_id binary(16),
	original_modifier_id_m bit,
	realm_id binary(16),
	realm_id_m bit,
	transaction_id binary(16),
	transaction_id_m bit,
	ownership bit,
	ownership_m bit,
	account_id binary(16),
	account_m bit,
	role_catalogue_id binary(16),
	role_catalogue_m bit,
	role_system_id binary(16),
	role_system_m bit,
	CONSTRAINT acc_role_catalogue_account_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_civ47mx4nlpsvlro1r7nw7ycr FOREIGN KEY (rev) REFERENCES idm_audit(id)
);


CREATE TABLE acc_tree_account_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	revtype smallint,
	created datetime,
	created_m bit,
	creator varchar(255),
	creator_m bit,
	creator_id binary(16),
	creator_id_m bit,
	modifier varchar(255),
	modifier_m bit,
	modifier_id binary(16),
	modifier_id_m bit,
	original_creator varchar(255),
	original_creator_m bit,
	original_creator_id binary(16),
	original_creator_id_m bit,
	original_modifier varchar(255),
	original_modifier_m bit,
	original_modifier_id binary(16),
	original_modifier_id_m bit,
	realm_id binary(16),
	realm_id_m bit,
	transaction_id binary(16),
	transaction_id_m bit,
	ownership bit,
	ownership_m bit,
	account_id binary(16),
	account_m bit,
	role_system_id binary(16),
	role_system_m bit,
	tree_node_id binary(16),
	tree_node_m bit,
	CONSTRAINT acc_tree_account_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_5c3jg826m2x2fq1q677uwk02u FOREIGN KEY (rev) REFERENCES idm_audit(id)
);


CREATE TABLE sys_provisioning_break_config_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	revtype smallint,
	created datetime,
	created_m bit,
	creator varchar(255),
	creator_m bit,
	creator_id binary(16),
	creator_id_m bit,
	modifier varchar(255),
	modifier_m bit,
	modifier_id binary(16),
	modifier_id_m bit,
	original_creator varchar(255),
	original_creator_m bit,
	original_creator_id binary(16),
	original_creator_id_m bit,
	original_modifier varchar(255),
	original_modifier_m bit,
	original_modifier_id binary(16),
	original_modifier_id_m bit,
	realm_id binary(16),
	realm_id_m bit,
	transaction_id binary(16),
	transaction_id_m bit,
	disable_limit int,
	disable_limit_m bit,
	disabled bit,
	disabled_m bit,
	operation_type varchar(255),
	operation_type_m bit,
	period numeric(19,0),
	period_m bit,
	warning_limit int,
	warning_limit_m bit,
	disable_template_id binary(16),
	disable_template_m bit,
	system_id binary(16),
	system_m bit,
	warning_template_id binary(16),
	warning_template_m bit,
	CONSTRAINT sys_provisioning_break_config_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_m6smdd15x3drkpslil9jadh62 FOREIGN KEY (rev) REFERENCES idm_audit(id)
);


CREATE TABLE sys_provisioning_break_recipient_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	revtype smallint,
	created datetime,
	created_m bit,
	creator varchar(255),
	creator_m bit,
	creator_id binary(16),
	creator_id_m bit,
	modifier varchar(255),
	modifier_m bit,
	modifier_id binary(16),
	modifier_id_m bit,
	original_creator varchar(255),
	original_creator_m bit,
	original_creator_id binary(16),
	original_creator_id_m bit,
	original_modifier varchar(255),
	original_modifier_m bit,
	original_modifier_id binary(16),
	original_modifier_id_m bit,
	realm_id binary(16),
	realm_id_m bit,
	transaction_id binary(16),
	transaction_id_m bit,
	break_config_id binary(16),
	break_config_m bit,
	identity_id binary(16),
	identity_m bit,
	role_id binary(16),
	role_m bit,
	CONSTRAINT sys_provisioning_break_recipient_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_cyr1rkx363m9k74llltevx3rp FOREIGN KEY (rev) REFERENCES idm_audit(id)
);


CREATE TABLE sys_role_system_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	revtype smallint,
	created datetime,
	created_m bit,
	creator varchar(255),
	creator_m bit,
	creator_id binary(16),
	creator_id_m bit,
	modifier varchar(255),
	modifier_m bit,
	modifier_id binary(16),
	modifier_id_m bit,
	original_creator varchar(255),
	original_creator_m bit,
	original_creator_id binary(16),
	original_creator_id_m bit,
	original_modifier varchar(255),
	original_modifier_m bit,
	original_modifier_id binary(16),
	original_modifier_id_m bit,
	realm_id binary(16),
	realm_id_m bit,
	transaction_id binary(16),
	transaction_id_m bit,
	forward_acm_enabled bit,
	forward_account_managemen_m bit,
	role_id binary(16),
	role_m bit,
	system_id binary(16),
	system_m bit,
	system_mapping_id binary(16),
	system_mapping_m bit,
	CONSTRAINT sys_role_system_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_n0hfyes79r41p01upa8bkbmu6 FOREIGN KEY (rev) REFERENCES idm_audit(id)
);


CREATE TABLE sys_role_system_attribute_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	revtype smallint,
	created datetime,
	created_m bit,
	creator varchar(255),
	creator_m bit,
	creator_id binary(16),
	creator_id_m bit,
	modifier varchar(255),
	modifier_m bit,
	modifier_id binary(16),
	modifier_id_m bit,
	original_creator varchar(255),
	original_creator_m bit,
	original_creator_id binary(16),
	original_creator_id_m bit,
	original_modifier varchar(255),
	original_modifier_m bit,
	original_modifier_id binary(16),
	original_modifier_id_m bit,
	realm_id binary(16),
	realm_id_m bit,
	transaction_id binary(16),
	transaction_id_m bit,
	confidential_attribute bit,
	confidential_attribute_m bit,
	disabled_default_attribute bit,
	disabled_default_attribute_m bit,
	entity_attribute bit,
	entity_attribute_m bit,
	extended_attribute bit,
	extended_attribute_m bit,
	idm_property_name varchar(255),
	idm_property_name_m bit,
	name varchar(255),
	name_m bit,
	send_always bit,
	send_always_m bit,
	send_only_if_not_null bit,
	send_only_if_not_null_m bit,
	strategy_type varchar(255),
	strategy_type_m bit,
	transform_script text,
	transform_script_m bit,
	uid bit,
	uid_m bit,
	role_system_id binary(16),
	role_system_m bit,
	system_attr_mapping_id binary(16),
	system_attribute_mapping_m bit,
	CONSTRAINT sys_role_system_attribute_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_mb7uvabbp62wpmroqbn80nh34 FOREIGN KEY (rev) REFERENCES idm_audit(id)
);


CREATE TABLE sys_schema_attribute_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	revtype smallint,
	created datetime,
	created_m bit,
	creator varchar(255),
	creator_m bit,
	creator_id binary(16),
	creator_id_m bit,
	modifier varchar(255),
	modifier_m bit,
	modifier_id binary(16),
	modifier_id_m bit,
	original_creator varchar(255),
	original_creator_m bit,
	original_creator_id binary(16),
	original_creator_id_m bit,
	original_modifier varchar(255),
	original_modifier_m bit,
	original_modifier_id binary(16),
	original_modifier_id_m bit,
	realm_id binary(16),
	realm_id_m bit,
	transaction_id binary(16),
	transaction_id_m bit,
	class_type varchar(255),
	class_type_m bit,
	createable bit,
	createable_m bit,
	multivalued bit,
	multivalued_m bit,
	name varchar(255),
	name_m bit,
	native_name varchar(255),
	native_name_m bit,
	readable bit,
	readable_m bit,
	required bit,
	required_m bit,
	returned_by_default bit,
	returned_by_default_m bit,
	updateable bit,
	updateable_m bit,
	object_class_id binary(16),
	object_class_m bit,
	CONSTRAINT sys_schema_attribute_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_h227a5dpgs004bu0mf3bxdjdn FOREIGN KEY (rev) REFERENCES idm_audit(id)
);


CREATE TABLE sys_schema_obj_class_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	revtype smallint,
	created datetime,
	created_m bit,
	creator varchar(255),
	creator_m bit,
	creator_id binary(16),
	creator_id_m bit,
	modifier varchar(255),
	modifier_m bit,
	modifier_id binary(16),
	modifier_id_m bit,
	original_creator varchar(255),
	original_creator_m bit,
	original_creator_id binary(16),
	original_creator_id_m bit,
	original_modifier varchar(255),
	original_modifier_m bit,
	original_modifier_id binary(16),
	original_modifier_id_m bit,
	realm_id binary(16),
	realm_id_m bit,
	transaction_id binary(16),
	transaction_id_m bit,
	auxiliary bit,
	auxiliary_m bit,
	container bit,
	container_m bit,
	object_class_name varchar(255),
	object_class_name_m bit,
	system_id binary(16),
	system_m bit,
	CONSTRAINT sys_schema_obj_class_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_jhghwftbl8995o2e1m18dswbq FOREIGN KEY (rev) REFERENCES idm_audit(id)
);


CREATE TABLE sys_sync_config_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	revtype smallint,
	created datetime,
	created_m bit,
	creator varchar(255),
	creator_m bit,
	creator_id binary(16),
	creator_id_m bit,
	modifier varchar(255),
	modifier_m bit,
	modifier_id binary(16),
	modifier_id_m bit,
	original_creator varchar(255),
	original_creator_m bit,
	original_creator_id binary(16),
	original_creator_id_m bit,
	original_modifier varchar(255),
	original_modifier_m bit,
	original_modifier_id binary(16),
	original_modifier_id_m bit,
	realm_id binary(16),
	realm_id_m bit,
	transaction_id binary(16),
	transaction_id_m bit,
	custom_filter bit,
	custom_filter_m bit,
	custom_filter_script text,
	custom_filter_script_m bit,
	description varchar(2000),
	description_m bit,
	enabled bit,
	enabled_m bit,
	filter_operation varchar(255),
	filter_operation_m bit,
	linked_action varchar(255),
	linked_action_m bit,
	linked_action_wf varchar(255),
	linked_action_wf_key_m bit,
	missing_account_action varchar(255),
	missing_account_action_m bit,
	missing_account_action_wf varchar(255),
	missing_account_action_wf_key_m bit,
	missing_entity_action varchar(255),
	missing_entity_action_m bit,
	missing_entity_action_wf varchar(255),
	missing_entity_action_wf_key_m bit,
	name varchar(255),
	name_m bit,
	reconciliation bit,
	reconciliation_m bit,
	roots_filter_script text,
	roots_filter_script_m bit,
	unlinked_action varchar(255),
	unlinked_action_m bit,
	unlinked_action_wf varchar(255),
	unlinked_action_wf_key_m bit,
	correlation_attribute_id binary(16),
	correlation_attribute_m bit,
	filter_attribute_id binary(16),
	filter_attribute_m bit,
	system_mapping_id binary(16),
	system_mapping_m bit,
	token_attribute_id binary(16),
	token_attribute_m bit,
	CONSTRAINT sys_sync_config_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_qu1u38lrk8vnhkqd5b4ehf2mp FOREIGN KEY (rev) REFERENCES idm_audit(id)
);


CREATE TABLE sys_sync_contract_config_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	start_auto_role_rec bit,
	start_auto_role_rec_m bit,
	start_hr_processes bit,
	start_of_hr_processes_m bit,
	default_leader_id binary(16),
	default_leader_m bit,
	default_tree_node_id binary(16),
	default_tree_node_m bit,
	default_tree_type_id binary(16),
	default_tree_type_m bit,
	CONSTRAINT sys_sync_contract_config_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_ak23lsavvslhvywtevxaq4m2u FOREIGN KEY (id,rev) REFERENCES sys_sync_config_a(id,rev)
);


CREATE TABLE sys_sync_identity_config_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	create_default_contract bit,
	create_default_contract_m bit,
	start_auto_role_rec bit,
	start_auto_role_rec_m bit,
	default_role_id binary(16),
	default_role_m bit,
	CONSTRAINT sys_sync_identity_config_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_jc3sotalvrdqvt6xqh8msx9t3 FOREIGN KEY (id,rev) REFERENCES sys_sync_config_a(id,rev)
);


CREATE TABLE sys_system_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	revtype smallint,
	created datetime,
	created_m bit,
	creator varchar(255),
	creator_m bit,
	creator_id binary(16),
	creator_id_m bit,
	modifier varchar(255),
	modifier_m bit,
	modifier_id binary(16),
	modifier_id_m bit,
	original_creator varchar(255),
	original_creator_m bit,
	original_creator_id binary(16),
	original_creator_id_m bit,
	original_modifier varchar(255),
	original_modifier_m bit,
	original_modifier_id binary(16),
	original_modifier_id_m bit,
	realm_id binary(16),
	realm_id_m bit,
	transaction_id binary(16),
	transaction_id_m bit,
	create_operation bit,
	delete_operation bit,
	update_operation bit,
	blocked_operation_m bit,
	connector_bundle_name varchar(255),
	connector_bundle_version varchar(30),
	connector_name varchar(255),
	connector_framework varchar(255),
	connector_key_m bit,
	host varchar(255),
	port int,
	timeout int,
	use_ssl bit,
	connector_server_m bit,
	description varchar(2000),
	description_m bit,
	disabled bit,
	disabled_m bit,
	name varchar(255),
	name_m bit,
	queue bit,
	queue_m bit,
	readonly bit,
	readonly_m bit,
	remote bit,
	remote_m bit,
	virtual bit,
	virtual_m bit,
	password_pol_gen_id binary(16),
	password_policy_generate_m bit,
	password_pol_val_id binary(16),
	password_policy_validate_m bit,
	CONSTRAINT sys_system_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_khsnjdk8wea24bo32saq8cc14 FOREIGN KEY (rev) REFERENCES idm_audit(id)
);


CREATE TABLE sys_system_attribute_mapping_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	revtype smallint,
	created datetime,
	created_m bit,
	creator varchar(255),
	creator_m bit,
	creator_id binary(16),
	creator_id_m bit,
	modifier varchar(255),
	modifier_m bit,
	modifier_id binary(16),
	modifier_id_m bit,
	original_creator varchar(255),
	original_creator_m bit,
	original_creator_id binary(16),
	original_creator_id_m bit,
	original_modifier varchar(255),
	original_modifier_m bit,
	original_modifier_id binary(16),
	original_modifier_id_m bit,
	realm_id binary(16),
	realm_id_m bit,
	transaction_id binary(16),
	transaction_id_m bit,
	authentication_attribute bit,
	authentication_attribute_m bit,
	attribute_cached bit,
	cached_m bit,
	confidential_attribute bit,
	confidential_attribute_m bit,
	disabled_attribute bit,
	disabled_attribute_m bit,
	entity_attribute bit,
	entity_attribute_m bit,
	extended_attribute bit,
	extended_attribute_m bit,
	idm_property_name varchar(255),
	idm_property_name_m bit,
	name varchar(255),
	name_m bit,
	send_always bit,
	send_always_m bit,
	send_on_password_change bit,
	send_on_password_change_m bit,
	send_only_if_not_null bit,
	send_only_if_not_null_m bit,
	strategy_type varchar(255),
	strategy_type_m bit,
	transform_from_res_script text,
	transform_from_resource_script_m bit,
	transform_to_res_script text,
	transform_to_resource_script_m bit,
	uid bit,
	uid_m bit,
	schema_attribute_id binary(16),
	schema_attribute_m bit,
	system_mapping_id binary(16),
	system_mapping_m bit,
	CONSTRAINT sys_system_attribute_mapping_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_ncp3og5psyxsw3kr3kyqc49mm FOREIGN KEY (rev) REFERENCES idm_audit(id)
);


CREATE TABLE sys_system_form_value_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	revtype smallint,
	created datetime,
	created_m bit,
	creator varchar(255),
	creator_m bit,
	creator_id binary(16),
	creator_id_m bit,
	modifier varchar(255),
	modifier_m bit,
	modifier_id binary(16),
	modifier_id_m bit,
	original_creator varchar(255),
	original_creator_m bit,
	original_creator_id binary(16),
	original_creator_id_m bit,
	original_modifier varchar(255),
	original_modifier_m bit,
	original_modifier_id binary(16),
	original_modifier_id_m bit,
	realm_id binary(16),
	realm_id_m bit,
	transaction_id binary(16),
	transaction_id_m bit,
	boolean_value bit,
	boolean_value_m bit,
	byte_value varbinary(255),
	byte_value_m bit,
	confidential bit,
	confidential_m bit,
	date_value datetime,
	date_value_m bit,
	double_value numeric(38,4),
	double_value_m bit,
	long_value numeric(19,0),
	long_value_m bit,
	persistent_type varchar(45),
	persistent_type_m bit,
	seq smallint,
	seq_m bit,
	short_text_value varchar(2000),
	short_text_value_m bit,
	string_value text,
	string_value_m bit,
	uuid_value binary(16),
	uuid_value_m bit,
	attribute_id binary(16),
	form_attribute_m bit,
	owner_id binary(16),
	owner_m bit,
	CONSTRAINT sys_system_form_value_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_awctj8y0nn7xyocg95xqpsq62 FOREIGN KEY (rev) REFERENCES idm_audit(id)
);


CREATE TABLE sys_system_mapping_a (
	id binary(16) NOT NULL,
	rev numeric(19,0) NOT NULL,
	revtype smallint,
	created datetime,
	created_m bit,
	creator varchar(255),
	creator_m bit,
	creator_id binary(16),
	creator_id_m bit,
	modifier varchar(255),
	modifier_m bit,
	modifier_id binary(16),
	modifier_id_m bit,
	original_creator varchar(255),
	original_creator_m bit,
	original_creator_id binary(16),
	original_creator_id_m bit,
	original_modifier varchar(255),
	original_modifier_m bit,
	original_modifier_id binary(16),
	original_modifier_id_m bit,
	realm_id binary(16),
	realm_id_m bit,
	transaction_id binary(16),
	transaction_id_m bit,
	can_be_acc_created_script text,
	can_be_account_created_script_m bit,
	entity_type varchar(255),
	entity_type_m bit,
	name varchar(255),
	name_m bit,
	operation_type varchar(255),
	operation_type_m bit,
	protection_enabled bit,
	protection_enabled_m bit,
	protection_interval int,
	protection_interval_m bit,
	object_class_id binary(16),
	object_class_m bit,
	tree_type_id binary(16),
	tree_type_m bit,
	CONSTRAINT sys_system_mapping_a_pkey PRIMARY KEY (id,rev),
	CONSTRAINT fk_8ruymojmoa1l1xv4x1n5tbatv FOREIGN KEY (rev) REFERENCES idm_audit(id)
);
