--
-- CzechIdM 10 Flyway script 
-- BCV solutions s.r.o.
--
-- Long running task audit

CREATE TABLE idm_long_running_task_a (
	id bytea NOT NULL,
	rev int8 NOT NULL,
	revtype int2 NULL,
	created timestamp NULL,
	created_m bool NULL,
	creator varchar(255) NULL,
	creator_m bool NULL,
	creator_id bytea NULL,
	creator_id_m bool NULL,
	modifier varchar(255) NULL,
	modifier_m bool NULL,
	modifier_id bytea NULL,
	modifier_id_m bool NULL,
	original_creator varchar(255) NULL,
	original_creator_m bool NULL,
	original_creator_id bytea NULL,
	original_creator_id_m bool NULL,
	original_modifier varchar(255) NULL,
	original_modifier_m bool NULL,
	original_modifier_id bytea NULL,
	original_modifier_id_m bool NULL,
	realm_id bytea NULL,
	realm_id_m bool NULL,
	dry_run bool NULL,
	dry_run_m bool NULL,
	instance_id varchar(255) NULL,
	instance_id_m bool NULL,
	recoverable bool NULL,
	recoverable_m bool NULL,
	result_cause text NULL,
	result_code varchar(255) NULL,
	result_model bytea NULL,
	result_state varchar(45) NULL,
	result_m bool NULL,
	running bool NULL,
	running_m bool NULL,
	stateful bool NULL,
	stateful_m bool NULL,
	task_description varchar(2000) NULL,
	task_description_m bool NULL,
	task_properties bytea NULL,
	task_properties_m bool NULL,
	task_started timestamp NULL,
	task_started_m bool NULL,
	task_type varchar(255) NULL,
	task_type_m bool NULL,
	thread_id int8 NULL,
	thread_id_m bool NULL,
	thread_name varchar(255) NULL,
	thread_name_m bool NULL,
	scheduled_task_id bytea NULL,
	scheduled_task_m bool NULL,
	CONSTRAINT idm_long_running_task_a_pkey PRIMARY KEY (id, rev),
	CONSTRAINT fk6libuw83ga8itsldmrgmc7v0v FOREIGN KEY (rev) REFERENCES idm_audit(id)
);


