--
-- CzechIdM 7.0 Flyway script 
-- BCV solutions s.r.o.
--
-- This SQL script creates the required tables by CzechIdM Audit (module core)


----- TABLE revchanges -----
CREATE TABLE revchanges
(
  rev bigint NOT NULL,
  modified_entity_names character varying(255),
  CONSTRAINT fk_et6b2lrkqkab5mhvxkv861n8h FOREIGN KEY (rev)
      REFERENCES idm_audit (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
);

  
----- TABLE idm_concept_role_request_a -----
CREATE TABLE idm_concept_role_request_a
(
  id bytea NOT NULL,
  rev bigint NOT NULL,
  revtype smallint,
  created timestamp without time zone,
  created_m boolean,
  creator character varying(255),
  creator_m boolean,
  creator_id bytea,
  creator_id_m boolean,
  modified timestamp without time zone,
  modified_m boolean,
  modifier character varying(255),
  modifier_m boolean,
  modifier_id bytea,
  modifier_id_m boolean,
  original_creator character varying(255),
  original_creator_m boolean,
  original_creator_id bytea,
  original_creator_id_m boolean,
  original_modifier character varying(255),
  original_modifier_m boolean,
  original_modifier_id bytea,
  original_modifier_id_m boolean,
  realm_id bytea,
  realm_id_m boolean,
  transaction_id bytea,
  transaction_id_m boolean,
  operation character varying(255),
  operation_m boolean,
  state character varying(255),
  state_m boolean,
  valid_from date,
  valid_from_m boolean,
  valid_till date,
  valid_till_m boolean,
  wf_process_id character varying(255),
  wf_process_id_m boolean,
  identity_contract_id bytea,
  identity_contract_m boolean,
  identity_role_id bytea,
  identity_role_m boolean,
  role_id bytea,
  role_m boolean,
  request_role_id bytea,
  role_request_m boolean,
  role_tree_node_id bytea,
  role_tree_node_m boolean,
  CONSTRAINT idm_concept_role_request_a_pkey PRIMARY KEY (id, rev),
  CONSTRAINT fk_s00svvhj93oge2mlgotun5nuv FOREIGN KEY (rev)
      REFERENCES idm_audit (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
);

  
----- TABLE idm_confidential_storage_a -----
CREATE TABLE idm_confidential_storage_a
(
  id bytea NOT NULL,
  rev bigint NOT NULL,
  revtype smallint,
  created timestamp without time zone,
  created_m boolean,
  creator character varying(255),
  creator_m boolean,
  creator_id bytea,
  creator_id_m boolean,
  modified timestamp without time zone,
  modified_m boolean,
  modifier character varying(255),
  modifier_m boolean,
  modifier_id bytea,
  modifier_id_m boolean,
  original_creator character varying(255),
  original_creator_m boolean,
  original_creator_id bytea,
  original_creator_id_m boolean,
  original_modifier character varying(255),
  original_modifier_m boolean,
  original_modifier_id bytea,
  original_modifier_id_m boolean,
  realm_id bytea,
  realm_id_m boolean,
  transaction_id bytea,
  transaction_id_m boolean,
  storage_key character varying(255),
  key_m boolean,
  owner_id bytea,
  owner_id_m boolean,
  owner_type character varying(255),
  owner_type_m boolean,
  CONSTRAINT idm_confidential_storage_a_pkey PRIMARY KEY (id, rev),
  CONSTRAINT fk_agmqlakgyyjnhyx4up05iim52 FOREIGN KEY (rev)
      REFERENCES idm_audit (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
);

  
----- TABLE idm_configuration_a -----
CREATE TABLE idm_configuration_a
(
  id bytea NOT NULL,
  rev bigint NOT NULL,
  revtype smallint,
  created timestamp without time zone,
  created_m boolean,
  creator character varying(255),
  creator_m boolean,
  creator_id bytea,
  creator_id_m boolean,
  modified timestamp without time zone,
  modified_m boolean,
  modifier character varying(255),
  modifier_m boolean,
  modifier_id bytea,
  modifier_id_m boolean,
  original_creator character varying(255),
  original_creator_m boolean,
  original_creator_id bytea,
  original_creator_id_m boolean,
  original_modifier character varying(255),
  original_modifier_m boolean,
  original_modifier_id bytea,
  original_modifier_id_m boolean,
  realm_id bytea,
  realm_id_m boolean,
  transaction_id bytea,
  transaction_id_m boolean,
  confidential boolean,
  confidential_m boolean,
  name character varying(255),
  name_m boolean,
  secured boolean,
  secured_m boolean,
  value character varying(255),
  value_m boolean,
  CONSTRAINT idm_configuration_a_pkey PRIMARY KEY (id, rev),
  CONSTRAINT fk_i8it9y3yjy5196fbs7cpn7faq FOREIGN KEY (rev)
      REFERENCES idm_audit (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
);

  
----- TABLE idm_audit -----
CREATE TABLE idm_form_attribute_a
(
  id bytea NOT NULL,
  rev bigint NOT NULL,
  revtype smallint,
  created timestamp without time zone,
  created_m boolean,
  creator character varying(255),
  creator_m boolean,
  creator_id bytea,
  creator_id_m boolean,
  modified timestamp without time zone,
  modified_m boolean,
  modifier character varying(255),
  modifier_m boolean,
  modifier_id bytea,
  modifier_id_m boolean,
  original_creator character varying(255),
  original_creator_m boolean,
  original_creator_id bytea,
  original_creator_id_m boolean,
  original_modifier character varying(255),
  original_modifier_m boolean,
  original_modifier_id bytea,
  original_modifier_id_m boolean,
  realm_id bytea,
  realm_id_m boolean,
  transaction_id bytea,
  transaction_id_m boolean,
  confidential boolean,
  confidential_m boolean,
  default_value text,
  default_value_m boolean,
  description character varying(2000),
  description_m boolean,
  display_name character varying(255),
  display_name_m boolean,
  multiple boolean,
  multiple_m boolean,
  name character varying(255),
  name_m boolean,
  persistent_type character varying(45),
  persistent_type_m boolean,
  placeholder character varying(255),
  placeholder_m boolean,
  readonly boolean,
  readonly_m boolean,
  required boolean,
  required_m boolean,
  seq smallint,
  seq_m boolean,
  unmodifiable boolean,
  unmodifiable_m boolean,
  definition_id bytea,
  form_definition_m boolean,
  CONSTRAINT idm_form_attribute_a_pkey PRIMARY KEY (id, rev),
  CONSTRAINT fk_87mqe2oxk3u5udokcqbpmd1s5 FOREIGN KEY (rev)
      REFERENCES idm_audit (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
);


----- TABLE idm_form_definition_a -----
CREATE TABLE idm_form_definition_a
(
  id bytea NOT NULL,
  rev bigint NOT NULL,
  revtype smallint,
  created timestamp without time zone,
  created_m boolean,
  creator character varying(255),
  creator_m boolean,
  creator_id bytea,
  creator_id_m boolean,
  modified timestamp without time zone,
  modified_m boolean,
  modifier character varying(255),
  modifier_m boolean,
  modifier_id bytea,
  modifier_id_m boolean,
  original_creator character varying(255),
  original_creator_m boolean,
  original_creator_id bytea,
  original_creator_id_m boolean,
  original_modifier character varying(255),
  original_modifier_m boolean,
  original_modifier_id bytea,
  original_modifier_id_m boolean,
  realm_id bytea,
  realm_id_m boolean,
  transaction_id bytea,
  transaction_id_m boolean,
  name character varying(255),
  name_m boolean,
  definition_type character varying(255),
  type_m boolean,
  form_attributes_m boolean,
  CONSTRAINT idm_form_definition_a_pkey PRIMARY KEY (id, rev),
  CONSTRAINT fk_mpbe9mt8v8mbmomjiftoxftlf FOREIGN KEY (rev)
      REFERENCES idm_audit (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
);

  
----- TABLE idm_i_contract_form_value_a -----
CREATE TABLE idm_i_contract_form_value_a
(
  id bytea NOT NULL,
  rev bigint NOT NULL,
  revtype smallint,
  created timestamp without time zone,
  created_m boolean,
  creator character varying(255),
  creator_m boolean,
  creator_id bytea,
  creator_id_m boolean,
  modified timestamp without time zone,
  modified_m boolean,
  modifier character varying(255),
  modifier_m boolean,
  modifier_id bytea,
  modifier_id_m boolean,
  original_creator character varying(255),
  original_creator_m boolean,
  original_creator_id bytea,
  original_creator_id_m boolean,
  original_modifier character varying(255),
  original_modifier_m boolean,
  original_modifier_id bytea,
  original_modifier_id_m boolean,
  realm_id bytea,
  realm_id_m boolean,
  transaction_id bytea,
  transaction_id_m boolean,
  boolean_value boolean,
  boolean_value_m boolean,
  byte_value bytea,
  byte_value_m boolean,
  confidential boolean,
  confidential_m boolean,
  date_value timestamp without time zone,
  date_value_m boolean,
  double_value numeric(38,4),
  double_value_m boolean,
  long_value bigint,
  long_value_m boolean,
  persistent_type character varying(45),
  persistent_type_m boolean,
  seq smallint,
  seq_m boolean,
  string_value text,
  string_value_m boolean,
  attribute_id bytea,
  form_attribute_m boolean,
  owner_id bytea,
  owner_m boolean,
  CONSTRAINT idm_i_contract_form_value_a_pkey PRIMARY KEY (id, rev),
  CONSTRAINT fk_qu8vg2k1wembpdp2jj1smb5s5 FOREIGN KEY (rev)
      REFERENCES idm_audit (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
);

  
----- TABLE idm_identity_a -----
CREATE TABLE idm_identity_a
(
  id bytea NOT NULL,
  rev bigint NOT NULL,
  revtype smallint,
  created timestamp without time zone,
  created_m boolean,
  creator character varying(255),
  creator_m boolean,
  creator_id bytea,
  creator_id_m boolean,
  modified timestamp without time zone,
  modified_m boolean,
  modifier character varying(255),
  modifier_m boolean,
  modifier_id bytea,
  modifier_id_m boolean,
  original_creator character varying(255),
  original_creator_m boolean,
  original_creator_id bytea,
  original_creator_id_m boolean,
  original_modifier character varying(255),
  original_modifier_m boolean,
  original_modifier_id bytea,
  original_modifier_id_m boolean,
  realm_id bytea,
  realm_id_m boolean,
  transaction_id bytea,
  transaction_id_m boolean,
  description character varying(2000),
  description_m boolean,
  disabled boolean,
  disabled_m boolean,
  email character varying(255),
  email_m boolean,
  first_name character varying(255),
  first_name_m boolean,
  last_name character varying(255),
  last_name_m boolean,
  phone character varying(30),
  phone_m boolean,
  title_after character varying(100),
  title_after_m boolean,
  title_before character varying(100),
  title_before_m boolean,
  username character varying(255),
  username_m boolean,
  CONSTRAINT idm_identity_a_pkey PRIMARY KEY (id, rev),
  CONSTRAINT fk_4pm45eprpsmhy5qnrkbgua56c FOREIGN KEY (rev)
      REFERENCES idm_audit (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
);

  
----- TABLE idm_identity_contract_a -----
CREATE TABLE idm_identity_contract_a
(
  id bytea NOT NULL,
  rev bigint NOT NULL,
  revtype smallint,
  created timestamp without time zone,
  created_m boolean,
  creator character varying(255),
  creator_m boolean,
  creator_id bytea,
  creator_id_m boolean,
  modified timestamp without time zone,
  modified_m boolean,
  modifier character varying(255),
  modifier_m boolean,
  modifier_id bytea,
  modifier_id_m boolean,
  original_creator character varying(255),
  original_creator_m boolean,
  original_creator_id bytea,
  original_creator_id_m boolean,
  original_modifier character varying(255),
  original_modifier_m boolean,
  original_modifier_id bytea,
  original_modifier_id_m boolean,
  realm_id bytea,
  realm_id_m boolean,
  transaction_id bytea,
  transaction_id_m boolean,
  description character varying(2000),
  description_m boolean,
  disabled boolean,
  disabled_m boolean,
  externe boolean,
  externe_m boolean,
  main boolean,
  main_m boolean,
  "position" character varying(255),
  position_m boolean,
  valid_from date,
  valid_from_m boolean,
  valid_till date,
  valid_till_m boolean,
  guarantee_id bytea,
  guarantee_m boolean,
  identity_id bytea,
  identity_m boolean,
  work_position_id bytea,
  work_position_m boolean,
  CONSTRAINT idm_identity_contract_a_pkey PRIMARY KEY (id, rev),
  CONSTRAINT fk_o27u52ytamblwynwf958a7rna FOREIGN KEY (rev)
      REFERENCES idm_audit (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
);


----- TABLE idm_identity_form_value_a -----
CREATE TABLE idm_identity_form_value_a
(
  id bytea NOT NULL,
  rev bigint NOT NULL,
  revtype smallint,
  created timestamp without time zone,
  created_m boolean,
  creator character varying(255),
  creator_m boolean,
  creator_id bytea,
  creator_id_m boolean,
  modified timestamp without time zone,
  modified_m boolean,
  modifier character varying(255),
  modifier_m boolean,
  modifier_id bytea,
  modifier_id_m boolean,
  original_creator character varying(255),
  original_creator_m boolean,
  original_creator_id bytea,
  original_creator_id_m boolean,
  original_modifier character varying(255),
  original_modifier_m boolean,
  original_modifier_id bytea,
  original_modifier_id_m boolean,
  realm_id bytea,
  realm_id_m boolean,
  transaction_id bytea,
  transaction_id_m boolean,
  boolean_value boolean,
  boolean_value_m boolean,
  byte_value bytea,
  byte_value_m boolean,
  confidential boolean,
  confidential_m boolean,
  date_value timestamp without time zone,
  date_value_m boolean,
  double_value numeric(38,4),
  double_value_m boolean,
  long_value bigint,
  long_value_m boolean,
  persistent_type character varying(45),
  persistent_type_m boolean,
  seq smallint,
  seq_m boolean,
  string_value text,
  string_value_m boolean,
  attribute_id bytea,
  form_attribute_m boolean,
  owner_id bytea,
  owner_m boolean,
  CONSTRAINT idm_identity_form_value_a_pkey PRIMARY KEY (id, rev),
  CONSTRAINT fk_j85k7gu9fuv136lcim1yf442d FOREIGN KEY (rev)
      REFERENCES idm_audit (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
);


----- TABLE idm_identity_role_a -----
CREATE TABLE idm_identity_role_a
(
  id bytea NOT NULL,
  rev bigint NOT NULL,
  revtype smallint,
  created timestamp without time zone,
  created_m boolean,
  creator character varying(255),
  creator_m boolean,
  creator_id bytea,
  creator_id_m boolean,
  modified timestamp without time zone,
  modified_m boolean,
  modifier character varying(255),
  modifier_m boolean,
  modifier_id bytea,
  modifier_id_m boolean,
  original_creator character varying(255),
  original_creator_m boolean,
  original_creator_id bytea,
  original_creator_id_m boolean,
  original_modifier character varying(255),
  original_modifier_m boolean,
  original_modifier_id bytea,
  original_modifier_id_m boolean,
  realm_id bytea,
  realm_id_m boolean,
  transaction_id bytea,
  transaction_id_m boolean,
  valid_from date,
  valid_from_m boolean,
  valid_till date,
  valid_till_m boolean,
  identity_contract_id bytea,
  identity_contract_m boolean,
  role_id bytea,
  role_m boolean,
  role_tree_node_id bytea,
  role_tree_node_m boolean,
  CONSTRAINT idm_identity_role_a_pkey PRIMARY KEY (id, rev),
  CONSTRAINT fk_6f8hi53e37sxhyti4xlxx0k34 FOREIGN KEY (rev)
      REFERENCES idm_audit (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
);

  
----- TABLE idm_notification_configuration_a -----
CREATE TABLE idm_notification_configuration_a
(
  id bytea NOT NULL,
  rev bigint NOT NULL,
  revtype smallint,
  created timestamp without time zone,
  created_m boolean,
  creator character varying(255),
  creator_m boolean,
  creator_id bytea,
  creator_id_m boolean,
  modified timestamp without time zone,
  modified_m boolean,
  modifier character varying(255),
  modifier_m boolean,
  modifier_id bytea,
  modifier_id_m boolean,
  original_creator character varying(255),
  original_creator_m boolean,
  original_creator_id bytea,
  original_creator_id_m boolean,
  original_modifier character varying(255),
  original_modifier_m boolean,
  original_modifier_id bytea,
  original_modifier_id_m boolean,
  realm_id bytea,
  realm_id_m boolean,
  transaction_id bytea,
  transaction_id_m boolean,
  description character varying(2000),
  description_m boolean,
  notification_type character varying(255),
  notification_type_m boolean,
  topic character varying(255),
  topic_m boolean,
  template_id bytea,
  template_m boolean,
  CONSTRAINT idm_notification_configuration_a_pkey PRIMARY KEY (id, rev),
  CONSTRAINT fk_198fj5oy8o3fejsnhvryul3p8 FOREIGN KEY (rev)
      REFERENCES idm_audit (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
);

  
----- TABLE idm_notification_template_a -----
CREATE TABLE idm_notification_template_a
(
  id bytea NOT NULL,
  rev bigint NOT NULL,
  revtype smallint,
  created timestamp without time zone,
  created_m boolean,
  creator character varying(255),
  creator_m boolean,
  creator_id bytea,
  creator_id_m boolean,
  modified timestamp without time zone,
  modified_m boolean,
  modifier character varying(255),
  modifier_m boolean,
  modifier_id bytea,
  modifier_id_m boolean,
  original_creator character varying(255),
  original_creator_m boolean,
  original_creator_id bytea,
  original_creator_id_m boolean,
  original_modifier character varying(255),
  original_modifier_m boolean,
  original_modifier_id bytea,
  original_modifier_id_m boolean,
  realm_id bytea,
  realm_id_m boolean,
  transaction_id bytea,
  transaction_id_m boolean,
  body_html text,
  body_html_m boolean,
  body_text text,
  body_text_m boolean,
  code character varying(255),
  code_m boolean,
  module character varying(255),
  module_m boolean,
  name character varying(255),
  name_m boolean,
  parameter character varying(255),
  parameter_m boolean,
  subject character varying(255),
  subject_m boolean,
  CONSTRAINT idm_notification_template_a_pkey PRIMARY KEY (id, rev),
  CONSTRAINT fk_pxuc0kajt3bs0malyc4iy86tt FOREIGN KEY (rev)
      REFERENCES idm_audit (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
);

  
----- TABLE idm_password_policy_a -----
CREATE TABLE idm_password_policy_a
(
  id bytea NOT NULL,
  rev bigint NOT NULL,
  revtype smallint,
  created timestamp without time zone,
  created_m boolean,
  creator character varying(255),
  creator_m boolean,
  creator_id bytea,
  creator_id_m boolean,
  modified timestamp without time zone,
  modified_m boolean,
  modifier character varying(255),
  modifier_m boolean,
  modifier_id bytea,
  modifier_id_m boolean,
  original_creator character varying(255),
  original_creator_m boolean,
  original_creator_id bytea,
  original_creator_id_m boolean,
  original_modifier character varying(255),
  original_modifier_m boolean,
  original_modifier_id bytea,
  original_modifier_id_m boolean,
  realm_id bytea,
  realm_id_m boolean,
  transaction_id bytea,
  transaction_id_m boolean,
  default_policy boolean,
  default_policy_m boolean,
  description character varying(2000),
  description_m boolean,
  disabled boolean,
  disabled_m boolean,
  enchanced_control boolean,
  enchanced_control_m boolean,
  generate_type character varying(255),
  generate_type_m boolean,
  identity_attribute_check character varying(255),
  identity_attribute_check_m boolean,
  lower_char_base character varying(255),
  lower_char_base_m boolean,
  lower_char_required boolean,
  lower_char_required_m boolean,
  max_history_similar integer,
  max_history_similar_m boolean,
  max_password_age integer,
  max_password_age_m boolean,
  max_password_length integer,
  max_password_length_m boolean,
  min_lower_char integer,
  min_lower_char_m boolean,
  min_number integer,
  min_number_m boolean,
  min_password_age integer,
  min_password_age_m boolean,
  min_password_length integer,
  min_password_length_m boolean,
  min_rules_to_fulfill integer,
  min_rules_to_fulfill_m boolean,
  min_special_char integer,
  min_special_char_m boolean,
  min_upper_char integer,
  min_upper_char_m boolean,
  name character varying(255),
  name_m boolean,
  number_base character varying(255),
  number_base_m boolean,
  number_required boolean,
  number_required_m boolean,
  passphrase_words integer,
  passphrase_words_m boolean,
  password_length_required boolean,
  password_length_required_m boolean,
  prohibited_characters character varying(255),
  prohibited_characters_m boolean,
  special_char_base character varying(255),
  special_char_base_m boolean,
  special_char_required boolean,
  special_char_required_m boolean,
  type character varying(255),
  type_m boolean,
  upper_char_base character varying(255),
  upper_char_base_m boolean,
  upper_char_required boolean,
  upper_char_required_m boolean,
  weak_pass character varying(255),
  weak_pass_m boolean,
  weak_pass_required boolean,
  weak_pass_required_m boolean,
  CONSTRAINT idm_password_policy_a_pkey PRIMARY KEY (id, rev),
  CONSTRAINT fk_swya50ugpjfiuh5hdw1k1wgbm FOREIGN KEY (rev)
      REFERENCES idm_audit (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
);

  
----- TABLE idm_role_a -----
CREATE TABLE idm_role_a
(
  id bytea NOT NULL,
  rev bigint NOT NULL,
  revtype smallint,
  created timestamp without time zone,
  created_m boolean,
  creator character varying(255),
  creator_m boolean,
  creator_id bytea,
  creator_id_m boolean,
  modified timestamp without time zone,
  modified_m boolean,
  modifier character varying(255),
  modifier_m boolean,
  modifier_id bytea,
  modifier_id_m boolean,
  original_creator character varying(255),
  original_creator_m boolean,
  original_creator_id bytea,
  original_creator_id_m boolean,
  original_modifier character varying(255),
  original_modifier_m boolean,
  original_modifier_id bytea,
  original_modifier_id_m boolean,
  realm_id bytea,
  realm_id_m boolean,
  transaction_id bytea,
  transaction_id_m boolean,
  approve_add_workflow character varying(255),
  approve_add_workflow_m boolean,
  approve_remove_workflow character varying(255),
  approve_remove_workflow_m boolean,
  description character varying(2000),
  description_m boolean,
  disabled boolean,
  disabled_m boolean,
  name character varying(255),
  name_m boolean,
  priority integer,
  priority_m boolean,
  role_type character varying(255),
  role_type_m boolean,
  CONSTRAINT idm_role_a_pkey PRIMARY KEY (id, rev),
  CONSTRAINT fk_nwuujf2vpbphudbfcvxdj3exp FOREIGN KEY (rev)
      REFERENCES idm_audit (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
);

  
----- TABLE idm_role_authority_a -----
CREATE TABLE idm_role_authority_a
(
  id bytea NOT NULL,
  rev bigint NOT NULL,
  revtype smallint,
  created timestamp without time zone,
  created_m boolean,
  creator character varying(255),
  creator_m boolean,
  creator_id bytea,
  creator_id_m boolean,
  modified timestamp without time zone,
  modified_m boolean,
  modifier character varying(255),
  modifier_m boolean,
  modifier_id bytea,
  modifier_id_m boolean,
  original_creator character varying(255),
  original_creator_m boolean,
  original_creator_id bytea,
  original_creator_id_m boolean,
  original_modifier character varying(255),
  original_modifier_m boolean,
  original_modifier_id bytea,
  original_modifier_id_m boolean,
  realm_id bytea,
  realm_id_m boolean,
  transaction_id bytea,
  transaction_id_m boolean,
  action_permission character varying(255),
  action_m boolean,
  target_permission character varying(255),
  target_m boolean,
  role_id bytea,
  role_m boolean,
  CONSTRAINT idm_role_authority_a_pkey PRIMARY KEY (id, rev),
  CONSTRAINT fk_m2jv7l78tqaunrwmk2jr6p0ib FOREIGN KEY (rev)
      REFERENCES idm_audit (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
);

  
----- TABLE idm_role_catalogue_a -----
CREATE TABLE idm_role_catalogue_a
(
  id bytea NOT NULL,
  rev bigint NOT NULL,
  revtype smallint,
  created timestamp without time zone,
  created_m boolean,
  creator character varying(255),
  creator_m boolean,
  creator_id bytea,
  creator_id_m boolean,
  modified timestamp without time zone,
  modified_m boolean,
  modifier character varying(255),
  modifier_m boolean,
  modifier_id bytea,
  modifier_id_m boolean,
  original_creator character varying(255),
  original_creator_m boolean,
  original_creator_id bytea,
  original_creator_id_m boolean,
  original_modifier character varying(255),
  original_modifier_m boolean,
  original_modifier_id bytea,
  original_modifier_id_m boolean,
  realm_id bytea,
  realm_id_m boolean,
  transaction_id bytea,
  transaction_id_m boolean,
  code character varying(255),
  code_m boolean,
  description character varying(2000),
  description_m boolean,
  name character varying(255),
  name_m boolean,
  url character varying(255),
  url_m boolean,
  url_title character varying(255),
  url_title_m boolean,
  parent_id bytea,
  parent_m boolean,
  CONSTRAINT idm_role_catalogue_a_pkey PRIMARY KEY (id, rev),
  CONSTRAINT fk_pirc5x13v836h3hmyt0cc42kv FOREIGN KEY (rev)
      REFERENCES idm_audit (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
);


----- TABLE idm_role_catalogue_role_a -----
CREATE TABLE idm_role_catalogue_role_a
(
  id bytea NOT NULL,
  rev bigint NOT NULL,
  revtype smallint,
  created timestamp without time zone,
  created_m boolean,
  creator character varying(255),
  creator_m boolean,
  creator_id bytea,
  creator_id_m boolean,
  modified timestamp without time zone,
  modified_m boolean,
  modifier character varying(255),
  modifier_m boolean,
  modifier_id bytea,
  modifier_id_m boolean,
  original_creator character varying(255),
  original_creator_m boolean,
  original_creator_id bytea,
  original_creator_id_m boolean,
  original_modifier character varying(255),
  original_modifier_m boolean,
  original_modifier_id bytea,
  original_modifier_id_m boolean,
  realm_id bytea,
  realm_id_m boolean,
  transaction_id bytea,
  transaction_id_m boolean,
  role_id bytea,
  role_m boolean,
  role_catalogue_id bytea,
  role_catalogue_m boolean,
  CONSTRAINT idm_role_catalogue_role_a_pkey PRIMARY KEY (id, rev),
  CONSTRAINT fk_l085dvgnnwk6e46daedndy6sr FOREIGN KEY (rev)
      REFERENCES idm_audit (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
);

  
----- TABLE idm_role_composition_a -----
CREATE TABLE idm_role_composition_a
(
  id bytea NOT NULL,
  rev bigint NOT NULL,
  revtype smallint,
  created timestamp without time zone,
  created_m boolean,
  creator character varying(255),
  creator_m boolean,
  creator_id bytea,
  creator_id_m boolean,
  modified timestamp without time zone,
  modified_m boolean,
  modifier character varying(255),
  modifier_m boolean,
  modifier_id bytea,
  modifier_id_m boolean,
  original_creator character varying(255),
  original_creator_m boolean,
  original_creator_id bytea,
  original_creator_id_m boolean,
  original_modifier character varying(255),
  original_modifier_m boolean,
  original_modifier_id bytea,
  original_modifier_id_m boolean,
  realm_id bytea,
  realm_id_m boolean,
  transaction_id bytea,
  transaction_id_m boolean,
  sub_id bytea,
  sub_m boolean,
  superior_id bytea,
  superior_m boolean,
  CONSTRAINT idm_role_composition_a_pkey PRIMARY KEY (id, rev),
  CONSTRAINT fk_a8jshb3t1vrfp1vp0819x6h8q FOREIGN KEY (rev)
      REFERENCES idm_audit (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
);

  
----- TABLE idm_role_form_value_a -----
CREATE TABLE idm_role_form_value_a
(
  id bytea NOT NULL,
  rev bigint NOT NULL,
  revtype smallint,
  created timestamp without time zone,
  created_m boolean,
  creator character varying(255),
  creator_m boolean,
  creator_id bytea,
  creator_id_m boolean,
  modified timestamp without time zone,
  modified_m boolean,
  modifier character varying(255),
  modifier_m boolean,
  modifier_id bytea,
  modifier_id_m boolean,
  original_creator character varying(255),
  original_creator_m boolean,
  original_creator_id bytea,
  original_creator_id_m boolean,
  original_modifier character varying(255),
  original_modifier_m boolean,
  original_modifier_id bytea,
  original_modifier_id_m boolean,
  realm_id bytea,
  realm_id_m boolean,
  transaction_id bytea,
  transaction_id_m boolean,
  boolean_value boolean,
  boolean_value_m boolean,
  byte_value bytea,
  byte_value_m boolean,
  confidential boolean,
  confidential_m boolean,
  date_value timestamp without time zone,
  date_value_m boolean,
  double_value numeric(38,4),
  double_value_m boolean,
  long_value bigint,
  long_value_m boolean,
  persistent_type character varying(45),
  persistent_type_m boolean,
  seq smallint,
  seq_m boolean,
  string_value text,
  string_value_m boolean,
  attribute_id bytea,
  form_attribute_m boolean,
  owner_id bytea,
  owner_m boolean,
  CONSTRAINT idm_role_form_value_a_pkey PRIMARY KEY (id, rev),
  CONSTRAINT fk_gfx77xleqng5i3jipnm4648sr FOREIGN KEY (rev)
      REFERENCES idm_audit (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
);


----- TABLE idm_role_guarantee_a -----
CREATE TABLE idm_role_guarantee_a
(
  id bytea NOT NULL,
  rev bigint NOT NULL,
  revtype smallint,
  created timestamp without time zone,
  created_m boolean,
  creator character varying(255),
  creator_m boolean,
  creator_id bytea,
  creator_id_m boolean,
  modified timestamp without time zone,
  modified_m boolean,
  modifier character varying(255),
  modifier_m boolean,
  modifier_id bytea,
  modifier_id_m boolean,
  original_creator character varying(255),
  original_creator_m boolean,
  original_creator_id bytea,
  original_creator_id_m boolean,
  original_modifier character varying(255),
  original_modifier_m boolean,
  original_modifier_id bytea,
  original_modifier_id_m boolean,
  realm_id bytea,
  realm_id_m boolean,
  transaction_id bytea,
  transaction_id_m boolean,
  guarantee_id bytea,
  guarantee_m boolean,
  role_id bytea,
  role_m boolean,
  CONSTRAINT idm_role_guarantee_a_pkey PRIMARY KEY (id, rev),
  CONSTRAINT fk_spgix52wl4u4ajm06ha9jiajv FOREIGN KEY (rev)
      REFERENCES idm_audit (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
);

  
----- TABLE idm_role_request_a -----
CREATE TABLE idm_role_request_a
(
  id bytea NOT NULL,
  rev bigint NOT NULL,
  revtype smallint,
  created timestamp without time zone,
  created_m boolean,
  creator character varying(255),
  creator_m boolean,
  creator_id bytea,
  creator_id_m boolean,
  modified timestamp without time zone,
  modified_m boolean,
  modifier character varying(255),
  modifier_m boolean,
  modifier_id bytea,
  modifier_id_m boolean,
  original_creator character varying(255),
  original_creator_m boolean,
  original_creator_id bytea,
  original_creator_id_m boolean,
  original_modifier character varying(255),
  original_modifier_m boolean,
  original_modifier_id bytea,
  original_modifier_id_m boolean,
  realm_id bytea,
  realm_id_m boolean,
  transaction_id bytea,
  transaction_id_m boolean,
  description character varying(255),
  description_m boolean,
  execute_immediately boolean,
  execute_immediately_m boolean,
  requested_by_type character varying(255),
  requested_by_type_m boolean,
  state character varying(255),
  state_m boolean,
  wf_process_id character varying(255),
  wf_process_id_m boolean,
  applicant_id bytea,
  applicant_m boolean,
  duplicated_to_request bytea,
  duplicated_to_request_m boolean,
  CONSTRAINT idm_role_request_a_pkey PRIMARY KEY (id, rev),
  CONSTRAINT fk_o61enmny8d3wffg87pvfhi2m3 FOREIGN KEY (rev)
      REFERENCES idm_audit (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
);

  
----- TABLE idm_role_tree_node_a -----
CREATE TABLE idm_role_tree_node_a
(
  id bytea NOT NULL,
  rev bigint NOT NULL,
  revtype smallint,
  created timestamp without time zone,
  created_m boolean,
  creator character varying(255),
  creator_m boolean,
  creator_id bytea,
  creator_id_m boolean,
  modified timestamp without time zone,
  modified_m boolean,
  modifier character varying(255),
  modifier_m boolean,
  modifier_id bytea,
  modifier_id_m boolean,
  original_creator character varying(255),
  original_creator_m boolean,
  original_creator_id bytea,
  original_creator_id_m boolean,
  original_modifier character varying(255),
  original_modifier_m boolean,
  original_modifier_id bytea,
  original_modifier_id_m boolean,
  realm_id bytea,
  realm_id_m boolean,
  transaction_id bytea,
  transaction_id_m boolean,
  recursion_type character varying(255),
  recursion_type_m boolean,
  role_id bytea,
  role_m boolean,
  tree_node_id bytea,
  tree_node_m boolean,
  CONSTRAINT idm_role_tree_node_a_pkey PRIMARY KEY (id, rev),
  CONSTRAINT fk_d7dskfheq429uafvuesh6bje7 FOREIGN KEY (rev)
      REFERENCES idm_audit (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
);

  
----- TABLE idm_script_a -----
CREATE TABLE idm_script_a
(
  id bytea NOT NULL,
  rev bigint NOT NULL,
  revtype smallint,
  created timestamp without time zone,
  created_m boolean,
  creator character varying(255),
  creator_m boolean,
  creator_id bytea,
  creator_id_m boolean,
  modified timestamp without time zone,
  modified_m boolean,
  modifier character varying(255),
  modifier_m boolean,
  modifier_id bytea,
  modifier_id_m boolean,
  original_creator character varying(255),
  original_creator_m boolean,
  original_creator_id bytea,
  original_creator_id_m boolean,
  original_modifier character varying(255),
  original_modifier_m boolean,
  original_modifier_id bytea,
  original_modifier_id_m boolean,
  realm_id bytea,
  realm_id_m boolean,
  transaction_id bytea,
  transaction_id_m boolean,
  category character varying(255),
  category_m boolean,
  description character varying(2000),
  description_m boolean,
  name character varying(255),
  name_m boolean,
  script text,
  script_m boolean,
  CONSTRAINT idm_script_a_pkey PRIMARY KEY (id, rev),
  CONSTRAINT fk_a0o0bhr6om9dd80tdawuennqp FOREIGN KEY (rev)
      REFERENCES idm_audit (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
);

  
----- TABLE idm_tree_node_a -----
CREATE TABLE idm_tree_node_a
(
  id bytea NOT NULL,
  rev bigint NOT NULL,
  revtype smallint,
  created timestamp without time zone,
  created_m boolean,
  creator character varying(255),
  creator_m boolean,
  creator_id bytea,
  creator_id_m boolean,
  modified timestamp without time zone,
  modified_m boolean,
  modifier character varying(255),
  modifier_m boolean,
  modifier_id bytea,
  modifier_id_m boolean,
  original_creator character varying(255),
  original_creator_m boolean,
  original_creator_id bytea,
  original_creator_id_m boolean,
  original_modifier character varying(255),
  original_modifier_m boolean,
  original_modifier_id bytea,
  original_modifier_id_m boolean,
  realm_id bytea,
  realm_id_m boolean,
  transaction_id bytea,
  transaction_id_m boolean,
  code character varying(255),
  code_m boolean,
  disabled boolean,
  disabled_m boolean,
  name character varying(255),
  name_m boolean,
  parent_id bytea,
  parent_m boolean,
  tree_type_id bytea,
  tree_type_m boolean,
  CONSTRAINT idm_tree_node_a_pkey PRIMARY KEY (id, rev),
  CONSTRAINT fk_pfe3d9yuunnvu0caum686sji8 FOREIGN KEY (rev)
      REFERENCES idm_audit (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
);

  
----- TABLE idm_tree_node_form_value_a -----
CREATE TABLE idm_tree_node_form_value_a
(
  id bytea NOT NULL,
  rev bigint NOT NULL,
  revtype smallint,
  created timestamp without time zone,
  created_m boolean,
  creator character varying(255),
  creator_m boolean,
  creator_id bytea,
  creator_id_m boolean,
  modified timestamp without time zone,
  modified_m boolean,
  modifier character varying(255),
  modifier_m boolean,
  modifier_id bytea,
  modifier_id_m boolean,
  original_creator character varying(255),
  original_creator_m boolean,
  original_creator_id bytea,
  original_creator_id_m boolean,
  original_modifier character varying(255),
  original_modifier_m boolean,
  original_modifier_id bytea,
  original_modifier_id_m boolean,
  realm_id bytea,
  realm_id_m boolean,
  transaction_id bytea,
  transaction_id_m boolean,
  boolean_value boolean,
  boolean_value_m boolean,
  byte_value bytea,
  byte_value_m boolean,
  confidential boolean,
  confidential_m boolean,
  date_value timestamp without time zone,
  date_value_m boolean,
  double_value numeric(38,4),
  double_value_m boolean,
  long_value bigint,
  long_value_m boolean,
  persistent_type character varying(45),
  persistent_type_m boolean,
  seq smallint,
  seq_m boolean,
  string_value text,
  string_value_m boolean,
  attribute_id bytea,
  form_attribute_m boolean,
  owner_id bytea,
  owner_m boolean,
  CONSTRAINT idm_tree_node_form_value_a_pkey PRIMARY KEY (id, rev),
  CONSTRAINT fk_82r94pui8abb9sapy4y2a07g7 FOREIGN KEY (rev)
      REFERENCES idm_audit (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
);

  
----- TABLE idm_tree_type_a -----
CREATE TABLE idm_tree_type_a
(
  id bytea NOT NULL,
  rev bigint NOT NULL,
  revtype smallint,
  created timestamp without time zone,
  created_m boolean,
  creator character varying(255),
  creator_m boolean,
  creator_id bytea,
  creator_id_m boolean,
  modified timestamp without time zone,
  modified_m boolean,
  modifier character varying(255),
  modifier_m boolean,
  modifier_id bytea,
  modifier_id_m boolean,
  original_creator character varying(255),
  original_creator_m boolean,
  original_creator_id bytea,
  original_creator_id_m boolean,
  original_modifier character varying(255),
  original_modifier_m boolean,
  original_modifier_id bytea,
  original_modifier_id_m boolean,
  realm_id bytea,
  realm_id_m boolean,
  transaction_id bytea,
  transaction_id_m boolean,
  code character varying(255),
  code_m boolean,
  default_tree_type boolean,
  default_tree_type_m boolean,
  name character varying(255),
  name_m boolean,
  default_tree_node_id bytea,
  default_tree_node_m boolean,
  CONSTRAINT idm_tree_type_a_pkey PRIMARY KEY (id, rev),
  CONSTRAINT fk_f9ipost6xa40kv7bu5gqti3sa FOREIGN KEY (rev)
      REFERENCES idm_audit (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
);
