--
-- CzechIdM 9 Flyway script 
-- BCV solutions s.r.o.
--
-- Add code lists agenda

CREATE TABLE idm_code_list (
	id bytea NOT NULL,
	created timestamp NOT NULL,
	creator varchar(255) NOT NULL,
	creator_id bytea NULL,
	modified timestamp NULL,
	modifier varchar(255) NULL,
	modifier_id bytea NULL,
	original_creator varchar(255) NULL,
	original_creator_id bytea NULL,
	original_modifier varchar(255) NULL,
	original_modifier_id bytea NULL,
	realm_id bytea NULL,
	transaction_id bytea NULL,
	code varchar(255) NOT NULL,
	name varchar(255) NOT NULL,
	form_definition_id bytea NOT NULL,
	description varchar(2000) NULL,
	external_id varchar(255) NULL,
	CONSTRAINT idm_code_list_pkey PRIMARY KEY (id),
	CONSTRAINT ux_idm_code_list_code UNIQUE (code)
);
CREATE INDEX idx_idm_code_list_ext_id ON idm_code_list USING btree (external_id) ;
CREATE INDEX idx_idm_code_list_f_def_id ON idm_code_list USING btree (form_definition_id) ;

CREATE TABLE idm_code_list_a (
	id bytea NOT NULL,
	rev int8 NOT NULL,
	revtype int2 NULL,
	created timestamp NULL,
	created_m bool NULL,
	creator varchar(255) NULL,
	creator_m bool NULL,
	creator_id bytea NULL,
	creator_id_m bool NULL,
	modifier varchar(255) NULL,
	modifier_m bool NULL,
	modifier_id bytea NULL,
	modifier_id_m bool NULL,
	original_creator varchar(255) NULL,
	original_creator_m bool NULL,
	original_creator_id bytea NULL,
	original_creator_id_m bool NULL,
	original_modifier varchar(255) NULL,
	original_modifier_m bool NULL,
	original_modifier_id bytea NULL,
	original_modifier_id_m bool NULL,
	realm_id bytea NULL,
	realm_id_m bool NULL,
	transaction_id bytea NULL,
	transaction_id_m bool NULL,
	code varchar(255) NULL,
	code_m bool NULL,
	name varchar(255) NULL,
	name_m bool NULL,
	description varchar(2000) NULL,
	description_m bool NULL,
	external_id varchar(255) NULL,
	external_id_m bool NULL,
	CONSTRAINT idm_code_list_a_pkey PRIMARY KEY (id, rev),
	CONSTRAINT fk_mjxqvq89ih5fakk9ri8v56v6r FOREIGN KEY (rev) REFERENCES idm_audit(id)
);

CREATE TABLE idm_code_list_item (
	id bytea NOT NULL,
	created timestamp NOT NULL,
	creator varchar(255) NOT NULL,
	creator_id bytea NULL,
	modified timestamp NULL,
	modifier varchar(255) NULL,
	modifier_id bytea NULL,
	original_creator varchar(255) NULL,
	original_creator_id bytea NULL,
	original_modifier varchar(255) NULL,
	original_modifier_id bytea NULL,
	realm_id bytea NULL,
	transaction_id bytea NULL,
	code varchar(255) NOT NULL,
	name varchar(255) NOT NULL,
	code_list_id bytea NOT NULL,
	description varchar(2000) NULL,
	external_id varchar(255) NULL,
	"level" varchar(45) NULL,
	icon varchar(255) NULL,
	CONSTRAINT idm_code_list_item_pkey PRIMARY KEY (id),
	CONSTRAINT ux_idm_code_l_i_list_code UNIQUE (code_list_id, code)
);
CREATE INDEX idx_idm_code_l_i_code ON idm_code_list_item USING btree (code) ;
CREATE INDEX idx_idm_code_l_i_codelist ON idm_code_list_item USING btree (code_list_id) ;
CREATE INDEX idx_idm_code_l_i_ext_id ON idm_code_list_item USING btree (external_id) ;

CREATE TABLE idm_code_list_item_a (
	id bytea NOT NULL,
	rev int8 NOT NULL,
	revtype int2 NULL,
	created timestamp NULL,
	created_m bool NULL,
	creator varchar(255) NULL,
	creator_m bool NULL,
	creator_id bytea NULL,
	creator_id_m bool NULL,
	modifier varchar(255) NULL,
	modifier_m bool NULL,
	modifier_id bytea NULL,
	modifier_id_m bool NULL,
	original_creator varchar(255) NULL,
	original_creator_m bool NULL,
	original_creator_id bytea NULL,
	original_creator_id_m bool NULL,
	original_modifier varchar(255) NULL,
	original_modifier_m bool NULL,
	original_modifier_id bytea NULL,
	original_modifier_id_m bool NULL,
	realm_id bytea NULL,
	realm_id_m bool NULL,
	transaction_id bytea NULL,
	transaction_id_m bool NULL,
	code varchar(255) NULL,
	code_m bool NULL,
	name varchar(255) NULL,
	name_m bool NULL,
	description varchar(2000) NULL,
	description_m bool NULL,
	external_id varchar(255) NULL,
	external_id_m bool NULL,
	"level" varchar(45) NULL,
	level_m bool NULL,
	icon varchar(255) NULL,
	icon_m bool NULL,
	CONSTRAINT idm_code_list_item_a_pkey PRIMARY KEY (id, rev),
	CONSTRAINT fk_8gw0vr5qekosc9edf0defhtig FOREIGN KEY (rev) REFERENCES idm_audit(id)
);

CREATE TABLE idm_code_list_item_value (
	id bytea NOT NULL,
	created timestamp NOT NULL,
	creator varchar(255) NOT NULL,
	creator_id bytea NULL,
	modified timestamp NULL,
	modifier varchar(255) NULL,
	modifier_id bytea NULL,
	original_creator varchar(255) NULL,
	original_creator_id bytea NULL,
	original_modifier varchar(255) NULL,
	original_modifier_id bytea NULL,
	realm_id bytea NULL,
	transaction_id bytea NULL,
	boolean_value bool NULL,
	byte_value bytea NULL,
	confidential bool NOT NULL,
	date_value timestamp NULL,
	double_value numeric(38,4) NULL,
	long_value int8 NULL,
	persistent_type varchar(45) NOT NULL,
	seq int2 NULL,
	short_text_value varchar(2000) NULL,
	string_value text NULL,
	uuid_value bytea NULL,
	attribute_id bytea NOT NULL,
	owner_id bytea NOT NULL,
	CONSTRAINT idm_code_list_item_value_pkey PRIMARY KEY (id),
	CONSTRAINT idm_code_list_item_value_seq_check CHECK ((seq <= 99999))
);
CREATE INDEX idx_idm_code_l_i_value_a ON idm_code_list_item_value USING btree (owner_id) ;
CREATE INDEX idx_idm_code_l_i_value_a_def ON idm_code_list_item_value USING btree (attribute_id) ;
CREATE INDEX idx_idm_code_l_i_value_stxt ON idm_code_list_item_value USING btree (short_text_value) ;
CREATE INDEX idx_idm_code_l_i_value_uuid ON idm_code_list_item_value USING btree (uuid_value) ;

CREATE TABLE idm_code_list_item_value_a (
	id bytea NOT NULL,
	rev int8 NOT NULL,
	revtype int2 NULL,
	created timestamp NULL,
	created_m bool NULL,
	creator varchar(255) NULL,
	creator_m bool NULL,
	creator_id bytea NULL,
	creator_id_m bool NULL,
	modifier varchar(255) NULL,
	modifier_m bool NULL,
	modifier_id bytea NULL,
	modifier_id_m bool NULL,
	original_creator varchar(255) NULL,
	original_creator_m bool NULL,
	original_creator_id bytea NULL,
	original_creator_id_m bool NULL,
	original_modifier varchar(255) NULL,
	original_modifier_m bool NULL,
	original_modifier_id bytea NULL,
	original_modifier_id_m bool NULL,
	realm_id bytea NULL,
	realm_id_m bool NULL,
	transaction_id bytea NULL,
	transaction_id_m bool NULL,
	boolean_value bool NULL,
	boolean_value_m bool NULL,
	byte_value bytea NULL,
	byte_value_m bool NULL,
	confidential bool NULL,
	confidential_m bool NULL,
	date_value timestamp NULL,
	date_value_m bool NULL,
	double_value numeric(38,4) NULL,
	double_value_m bool NULL,
	long_value int8 NULL,
	long_value_m bool NULL,
	persistent_type varchar(45) NULL,
	persistent_type_m bool NULL,
	seq int2 NULL,
	seq_m bool NULL,
	short_text_value varchar(2000) NULL,
	short_text_value_m bool NULL,
	string_value text NULL,
	string_value_m bool NULL,
	uuid_value bytea NULL,
	uuid_value_m bool NULL,
	attribute_id bytea NULL,
	form_attribute_m bool NULL,
	owner_id bytea NULL,
	owner_m bool NULL,
	CONSTRAINT idm_code_list_item_value_a_pkey PRIMARY KEY (id, rev),
	CONSTRAINT fk_q5g131cvhcewy2or0tp4acar5 FOREIGN KEY (rev) REFERENCES idm_audit(id)
);
