package eu.bcvsolutions.idm.core.model.event.processor.identity;

import java.util.ArrayList;
import java.util.List;

import org.apache.commons.lang.StringUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Description;
import org.springframework.stereotype.Component;
import org.springframework.util.Assert;

import eu.bcvsolutions.idm.core.CoreModuleDescriptor;
import eu.bcvsolutions.idm.core.api.domain.CoreResultCode;
import eu.bcvsolutions.idm.core.api.dto.IdmAccountDto;
import eu.bcvsolutions.idm.core.api.dto.IdmIdentityDto;
import eu.bcvsolutions.idm.core.api.entity.OperationResult;
import eu.bcvsolutions.idm.core.api.event.CoreEventProcessor;
import eu.bcvsolutions.idm.core.api.event.DefaultEventResult;
import eu.bcvsolutions.idm.core.api.event.EntityEvent;
import eu.bcvsolutions.idm.core.api.event.EventContext;
import eu.bcvsolutions.idm.core.api.event.EventResult;
import eu.bcvsolutions.idm.core.api.event.processor.IdentityProcessor;
import eu.bcvsolutions.idm.core.api.service.EntityEventManager;
import eu.bcvsolutions.idm.core.api.service.IdmIdentityService;
import eu.bcvsolutions.idm.core.model.event.IdentityEvent.IdentityEventType;
import eu.bcvsolutions.idm.core.notification.api.domain.NotificationLevel;
import eu.bcvsolutions.idm.core.notification.api.dto.IdmMessageDto;
import eu.bcvsolutions.idm.core.notification.api.service.NotificationManager;
import eu.bcvsolutions.idm.core.security.api.domain.GuardedString;

/**
 * Identity's password change notification
 * 
 * @author Patrik Stloukal
 * @author Radek Tomiška
 *
 */
@Component
@Description("Sends notification to identity of changed password.")
public class IdentityPasswordChangeNotificationProcessor extends CoreEventProcessor<IdmIdentityDto>
		implements IdentityProcessor {

	public static final String PROCESSOR_NAME = "identity-password-change-notification";
	//
	@Autowired private IdmIdentityService identityService;
	@Autowired private NotificationManager notificationManager;

	public IdentityPasswordChangeNotificationProcessor() {
		super(IdentityEventType.PASSWORD);
	}
	
	@Override
	public String getName() {
		return PROCESSOR_NAME;
	}
	
	@Override
	public boolean conditional(EntityEvent<IdmIdentityDto> event) {
		return super.conditional(event) 
				&& !getBooleanProperty(EntityEventManager.EVENT_PROPERTY_SKIP_NOTIFICATION, event.getProperties());
	}

	@Override
	public EventResult<IdmIdentityDto> process(EntityEvent<IdmIdentityDto> event) {
		sendNotification(event.getContext(), CoreModuleDescriptor.TOPIC_PASSWORD_CHANGED, null);
		//
		return new DefaultEventResult<>(event, this);

	}
	
	/**
	 * Send notification about password was changed / set
	 * 
	 * @param context processed event context
	 * @param topic e.g. CoreModuleDescriptor.TOPIC_PASSWORD_CHANGED
	 * @param newPassword [optional] if password is generated by IdM
	 */
	public void sendNotification(EventContext<IdmIdentityDto> context, String topic, GuardedString newPassword) {
		Assert.notNull(topic);
		//
		IdmIdentityDto identity = context.getContent();
		//
		List<IdmAccountDto> successAccounts = new ArrayList<>();
		List<OperationResult> failureResults = new ArrayList<>();	
		List<String> systemNames = new ArrayList<>();
		for (EventResult<IdmIdentityDto> eventResult : context.getResults()) {
			eventResult.getResults().forEach(result -> {
				if (result.getModel() != null) {
					boolean success = result.getModel().getStatusEnum().equals(CoreResultCode.PASSWORD_CHANGE_ACCOUNT_SUCCESS.name());
					if (success) {	
						IdmAccountDto account = (IdmAccountDto) result.getModel().getParameters().get(IdmAccountDto.PARAMETER_NAME);
						systemNames.add(account.getSystemName());
						successAccounts.add(account);
					} else {
						// exception is logged before
						failureResults.add(result);
					}
				}
			});
		}
		//
		// send notification if at least one system success
		if (!successAccounts.isEmpty()) {
			notificationManager.send(
					topic,
					new IdmMessageDto.Builder()
					.setLevel(NotificationLevel.SUCCESS)
					.addParameter("successSystemNames", StringUtils.join(systemNames, ", "))
					.addParameter("successAccounts", successAccounts)
					.addParameter("failureResults", failureResults)
					.addParameter("name", identityService.getNiceLabel(identity))
					.addParameter("username", identity.getUsername())					
					.addParameter("password", newPassword)
					.build(),
					identity);
		}	
	}

	@Override
	public int getOrder() {
		return super.getOrder() + 1500;
	}
}
